SELECT  DISTINCT
    'IMS' AS    SOURCE_SYS  --  来源系统 
    ,CCC.CUSTOMER_CODE  AS ID --  ID 
    ,CCC.CUSTOMER_CODE  AS CUSTOMER_CODE  --  客户编码 
    ,CCC.CUSTOMER_NAME  AS CUSTOMER_NAME  --  客户名称 
    ,CCC.CUSTOMER_SHORT_NAME AS CUSTOMER_NAME_SN  --  客户简称 
    ,CCC.ENTERPRISE_LEGAL_PERSON  AS CUSTOMER_TYPE  --  客户类型 
    ,NVL(OE.EMPNAME ,OE2.EMPNAME) AS FOLLOWER_NAME --  跟进人名称 
    ,DEPT.DEPARTMENT_NAME_1 AS ORG_NAME1  --  一级组织全称 
    ,DEPT.DEPARTMENT_NAME_2 AS ORG_NAME2  --  二级组织全称 
    ,DEPT.DEPARTMENT_NAME_3  AS ORG_NAME3 --  三级组织全称 
    ,DEPT.DEPARTMENT_NAME_4  AS ORG_NAME4 --  四级组织全称 
    ,DEPT.DEPARTMENT_NAME_5 AS ORG_NAME5  --  五级组织全称 
    ,CCC.CREATION_DATE  AS FILLING_DATE --  建档时间 
    ,SYSDATE  AS CHECK_TIME --  检查时间 
    ,'否'  AS IS_HX  --  是否核销 
    ,NULL AS HX_TIME  --  核销时间 
    ,NULL AS HX_PS_UID  --  核销人PS账号 
    ,NULL AS HX_NAME  --  核销人姓名 
    ,'R250425004' AS RULE_CODE  --  规则编码 
    ,'R250425004_J02' AS JOB_CODE --  作业编码 
    ,SYSDATE AS ETL_CRT_DT  --  创建时间 
    ,SYSDATE AS ETL_UPD_DT  --  更新时间
	,'是' AS IS_NEW_DATA --是否最新数据 
FROM    MDDWD.DWD_SALE_REVENUE                      DSR  --销售业绩表
JOIN   ODS_IMS.CRM_CTM_CUSTOMER                     CCC  --客户表

ON  DSR.CUSTOMER_CODE = CCC.CUSTOMER_CODE     
    AND CCC.CUSTOMER_FLAG ='N'
    AND CCC.STATUS = 'C'
LEFT JOIN   ODS_IMS.ODS_CRM_CTM_CUST_SALESMAN       CCS  --客户业务员表
ON      CCC.CUSTOMER_ID = CCS.CUSTOMER_ID 

LEFT JOIN   ODS_IMS.OM_EMPLOYEE                     OE2  --IMS员工表
ON      CCS.SALESMAN = OE2.EMPID

LEFT JOIN ODS_IMS.ODS_CRM_CTM_CUST_RECEIVE_INFO             CRI--客户收货信息
ON DSR.DELIVERY_ADDRESS_ID = CRI.CUST_RECEIVE_INFO_ID

LEFT JOIN   ODS_IMS.OM_EMPLOYEE                     OE  --IMS员工表
ON      CRI.ATTRIBUTE8 = OE.EMPCODE
LEFT JOIN   MDDWI.TF_DWI_EMPLOYEE                   EMP  --员工表
ON      NVL(OE.EMPCODE,OE2.EMPCODE) = EMP.EMPLID
LEFT JOIN   MDDIM.DIM_DEPARTMENT_D                  DEPT  --部门表
ON      EMP.UNIT_CODE = DEPT.DEPARTMENT_CODE

WHERE   DSR.SALE_PLATFORM_NAME = '国内销售平台'
    AND TRUNC(DSR.PERIOD_DAY, 'YYYY') BETWEEN ADD_MONTHS(TRUNC(SYSDATE - 1, 'YYYY'), -36) AND TRUNC(SYSDATE - 1, 'YYYY')
    
    AND (CCC.ENTERPRISE_LEGAL_PERSON IS NULL)