-- 创建表语句
CREATE TABLE MDDWD.DWD_TPC_HWJCB (
    PERIOD DATE,
    WAREHOUSE_CODE VARCHAR2(4000),
    WAREHOUSE_NAME VARCHAR2(4000),
    SHIP_TIME VARCHAR2(4000),
    ORDER_ID VARCHAR2(4000),
    SHIP_ID VARCHAR2(4000),
    CUSTOMER_NAME VARCHAR2(4000),
    PRODUCT_VARIETY VARCHAR2(4000),
    PRODUCT_SPECIFICATION VARCHAR2(4000),
    PRODUCT_FORM VARCHAR2(4000),
    LOCATION_CODE VARCHAR2(4000),
    BEGINNING_INVENTORY NUMBER,
    TZLQ NUMBER,
    LQ NUMBER,
    PY NUMBER,
    PK NUMBER,
    ZC NUMBER,
    TZZC NUMBER,
    NOW_INVENTORY NUMBER,
    ORDER_RELEASE_CNT NUMBER,
    ACC_SELECTED_GOODS NUMBER,
    UPDATE_TIME DATE,
    ETL_CRT_DT DATE,
    ETL_UPD_DT DATE
);

-- 添加字段注释
COMMENT ON COLUMN MDDWD.DWD_TPC_HWJCB.PERIOD IS '日期';
COMMENT ON COLUMN MDDWD.DWD_TPC_HWJCB.WAREHOUSE_CODE IS '仓库编码';
COMMENT ON COLUMN MDDWD.DWD_TPC_HWJCB.WAREHOUSE_NAME IS '仓库名称';
COMMENT ON COLUMN MDDWD.DWD_TPC_HWJCB.SHIP_TIME IS '交货期';
COMMENT ON COLUMN MDDWD.DWD_TPC_HWJCB.ORDER_ID IS '订单号';
COMMENT ON COLUMN MDDWD.DWD_TPC_HWJCB.SHIP_ID IS '发货单号';
COMMENT ON COLUMN MDDWD.DWD_TPC_HWJCB.CUSTOMER_NAME IS '客户名称';
COMMENT ON COLUMN MDDWD.DWD_TPC_HWJCB.PRODUCT_VARIETY IS '品种';
COMMENT ON COLUMN MDDWD.DWD_TPC_HWJCB.PRODUCT_SPECIFICATION IS '规格';
COMMENT ON COLUMN MDDWD.DWD_TPC_HWJCB.PRODUCT_FORM IS '形式';
COMMENT ON COLUMN MDDWD.DWD_TPC_HWJCB.LOCATION_CODE IS '货位号';
COMMENT ON COLUMN MDDWD.DWD_TPC_HWJCB.BEGINNING_INVENTORY IS '昨结存(期初)';
COMMENT ON COLUMN MDDWD.DWD_TPC_HWJCB.TZLQ IS '调整领取';
COMMENT ON COLUMN MDDWD.DWD_TPC_HWJCB.LQ IS '领取';
COMMENT ON COLUMN MDDWD.DWD_TPC_HWJCB.PY IS '盘盈';
COMMENT ON COLUMN MDDWD.DWD_TPC_HWJCB.PK IS '盘亏';
COMMENT ON COLUMN MDDWD.DWD_TPC_HWJCB.ZC IS '转出';
COMMENT ON COLUMN MDDWD.DWD_TPC_HWJCB.TZZC IS '调整转出';
COMMENT ON COLUMN MDDWD.DWD_TPC_HWJCB.NOW_INVENTORY IS '今结存';
COMMENT ON COLUMN MDDWD.DWD_TPC_HWJCB.ORDER_RELEASE_CNT IS '订单下发件数';
COMMENT ON COLUMN MDDWD.DWD_TPC_HWJCB.ACC_SELECTED_GOODS IS '累计已选货(已选货物结存)';
COMMENT ON COLUMN MDDWD.DWD_TPC_HWJCB.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN MDDWD.DWD_TPC_HWJCB.ETL_CRT_DT IS 'ETL创建日期';
COMMENT ON COLUMN MDDWD.DWD_TPC_HWJCB.ETL_UPD_DT IS 'ETL更新日期';