CREATE TABLE DWS_INVENTORY_OPS_RK (
    PERIOD_DATE DATE,                          -- 日期
    PRODUCT_TYPE_SC VARCHAR2(4000),            -- 产品类型
    PRODUCT_CODE VARCHAR2(4000),               -- 产品编码
    MONTHLY_IN_QUANTITY NUMBER,                -- 月入库量
    SAMEP_MONTH_IN_QUANTITY NUMBER,            -- 同期入库量
    LAST_MONTH_IN_QUANTITY NUMBER              -- 上月入库量
);

COMMENT ON TABLE DWS_INVENTORY_OPS_RK IS '入库量月度统计（适用于庚辰库存运营）';
COMMENT ON COLUMN DWS_INVENTORY_OPS_RK.PERIOD_DATE IS '日期';
COMMENT ON COLUMN DWS_INVENTORY_OPS_RK.PRODUCT_TYPE_SC IS '产品类型分类';
COMMENT ON COLUMN DWS_INVENTORY_OPS_RK.PRODUCT_CODE IS '产品编码';
COMMENT ON COLUMN DWS_INVENTORY_OPS_RK.MONTHLY_IN_QUANTITY IS '当月入库量';
COMMENT ON COLUMN DWS_INVENTORY_OPS_RK.SAMEP_MONTH_IN_QUANTITY IS '上年同月入库量';
COMMENT ON COLUMN DWS_INVENTORY_OPS_RK.LAST_MONTH_IN_QUANTITY IS '上月入库量';









SELECT 
    TRUNC(TO_DATE(D.RQ,'YY.MM.DD')+1,'MM') AS PERIOD_DATE
    ,A.PRODUCT_TYPE_SC        --类型  
    ,A.PRODUCT_CODE           --产品编码
    ,SUM(D.ZL) AS MONTHLY_IN_QUANTITY                ---重量入库  ODS_ERP2013.ODS_TPC_BZRKB 
FROM 
    MDDWD.DWD_STKCFLB A
    LEFT JOIN ODS_ERP2013.ODS_TPC_BZRKB D --取入库ZL
    ON A.PRODUCT_CODE = (CASE WHEN D.GG IS NULL OR D.GG='' THEN D.PZ ELSE D.PZ ||'_'|| D.GG END)  
WHERE
A.PRODUCT_CODE IN (
    SELECT PRODUCT_CODE
    FROM MDDWD.DWD_XSGXDYB C
    WHERE
        C.PRODUCT_SORT1 = '球铁'
        AND C.START_TIME <= SYSDATE
        AND C.END_TIME >= SYSDATE       --作为限制
) 

GROUP BY TRUNC(TO_DATE(D.RQ,'YY.MM.DD')+1,'MM'),A.PRODUCT_TYPE_SC,A.PRODUCT_CODE




TRUNCATE TEBLE MDDWS.DWS_INVENTORY_OPS_RK;
INSERT INTO MDDWS.DWS_INVENTORY_OPS_RK(
    PERIOD ,                              -- 日期
    PRODUCT_TYPE_SC           -- 产品类型
    PRODUCT_CODE ,             -- 产品编码
    MONTHLY_IN_QUANTITY ,              -- 月出库量
    SAMEP_MONTH_IN_QUANTITY ,          -- 同期出库量
    LAST_MONTH_IN_QUANTITY             -- 上月出库量

)

WITH TMP AS (
    SELECT 
        TRUNC(TO_DATE(D.RQ,'YY.MM.DD')+1,'MM') AS PERIOD_DATE,
        A.PRODUCT_TYPE_SC,
        A.PRODUCT_CODE,
        SUM(D.ZL) AS MONTHLY_IN_QUANTITY
    FROM 
        MDDWD.DWD_STKCFLB A
        LEFT JOIN ODS_ERP2013.ODS_TPC_BZRKB D
        ON A.PRODUCT_CODE = (CASE WHEN D.GG IS NULL OR D.GG='' THEN D.PZ ELSE D.PZ ||'_'|| D.GG END)  
    WHERE
        A.PRODUCT_CODE IN (
            SELECT PRODUCT_CODE
            FROM MDDWD.DWD_XSGXDYB C
            WHERE
                C.PRODUCT_SORT1 = '球铁'
                AND C.START_TIME <= SYSDATE
                AND C.END_TIME >= SYSDATE
        )
    GROUP BY 
        TRUNC(TO_DATE(D.RQ,'YY.MM.DD')+1,'MM'),
        A.PRODUCT_TYPE_SC,
        A.PRODUCT_CODE
)
SELECT 
    PERIOD_DATE,  --日期
    PRODUCT_TYPE_SC,--产品类型
    PRODUCT_CODE,--产品编码
    MONTHLY_IN_QUANTITY,--月入库量
    LAG(MONTHLY_IN_QUANTITY, 12) OVER (PARTITION BY PRODUCT_TYPE_SC, PRODUCT_CODE ORDER BY PERIOD_DATE) AS SAMEP_MONTH_IN_QUANTITY,--同期入库量
    LAG(MONTHLY_IN_QUANTITY, 1) OVER (PARTITION BY PRODUCT_TYPE_SC, PRODUCT_CODE ORDER BY PERIOD_DATE) AS LAST_MONTH_IN_QUANTITY--上月入库量
FROM TMP
