TRUNCATE TABLE MDDWS.DWS_INVENTORY_OPS_END;
INSERT INTO MDDWS.DWS_INVENTORY_OPS_END(
    PERIOD ,                              -- 日期
    PRODUCT_TYPE_SC ,          -- 产品类型
    PRODUCT_CODE ,             -- 产品编码
    ENDING_INVENTORY ,              
    SAMEP_MONTH_END_INVENTORY ,          
    LAST_MONTH_END_INVENTORY             

)


WITH TMP AS (
    SELECT 
        B.PERIOD,
        A.PRODUCT_TYPE_SC,
        A.PRODUCT_CODE,
        SUM(B.jjc) AS ENDING_INVENTORY
    FROM 
        MDDWD.DWD_STKCFLB A
        LEFT JOIN MDDWD.DWD_TPC_HWJCB B
        ON A.PRODUCT_CODE = (CASE WHEN B.PRODUCT_SPECIFICATION IS NULL OR B.PRODUCT_SPECIFICATION='' 
                               THEN B.PRODUCT_VARIETY 
                               ELSE B.PRODUCT_VARIETY ||'_'|| B.PRODUCT_SPECIFICATION END)  
    WHERE
        A.PRODUCT_CODE IN (
            SELECT PRODUCT_CODE
            FROM MDDWD.DWD_XSGXDYB C
            WHERE
                C.PRODUCT_SORT1 = '球铁'
                AND C.START_TIME <= SYSDATE
                AND C.END_TIME >= SYSDATE
        )
    GROUP BY 
        B.PERIOD,
        A.PRODUCT_TYPE_SC,
        A.PRODUCT_CODE
)



SELECT 
    PERIOD,             --日期
    PRODUCT_TYPE_SC,    --产品类型
    PRODUCT_CODE,
    ENDING_INVENTORY, --期末结存
    LAG(ENDING_INVENTORY, 12) OVER (PARTITION BY PRODUCT_TYPE_SC, PRODUCT_CODE ORDER BY PERIOD) AS SAMEP_MONTH_END_INVENTORY,  --同期期末结存
    LAG(ENDING_INVENTORY, 1) OVER (PARTITION BY PRODUCT_TYPE_SC, PRODUCT_CODE ORDER BY PERIOD) AS LAST_MONTH_END_INVENTORY       --上月期末结存  
FROM TMP




CREATE TABLE "MDDWS"."DWS_INVENTORY_OPS_END" 
   (	"PERIOD" DATE, 
	"PRODUCT_TYPE_SC" VARCHAR2(4000), 
	"PRODUCT_CODE" VARCHAR2(4000), 
	"ENDNING_INVENTORY" NUMBER, 
	"SAMEP_MONTH_END_INVENTORY" NUMBER, 
	"LAST_MONTH_END_INVENTORY" NUMBER, 
	"ETL_CRT_DT" DATE DEFAULT SYSDATE, 
	"ETL_UPD_DT" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MDDWS_DAT" ;
   COMMENT ON COLUMN "MDDWS"."DWS_INVENTORY_OPS_END"."PERIOD" IS '统计日期';
   COMMENT ON COLUMN "MDDWS"."DWS_INVENTORY_OPS_END"."PRODUCT_TYPE_SC" IS '产品类型分类';
   COMMENT ON COLUMN "MDDWS"."DWS_INVENTORY_OPS_END"."PRODUCT_CODE" IS '产品编码';
   COMMENT ON COLUMN "MDDWS"."DWS_INVENTORY_OPS_END"."ENDNING_INVENTORY" IS '当月期末结存量';
   COMMENT ON COLUMN "MDDWS"."DWS_INVENTORY_OPS_END"."SAMEP_MONTH_END_INVENTORY" IS '上年同月期末结存量';
   COMMENT ON COLUMN "MDDWS"."DWS_INVENTORY_OPS_END"."LAST_MONTH_END_INVENTORY" IS '上月期末结存量';
   COMMENT ON TABLE "MDDWS"."DWS_INVENTORY_OPS_END"  IS '期末结存量月度统计表（适用于庚辰库存运营）';
  GRANT SELECT ON "MDDWS"."DWS_INVENTORY_OPS_END" TO "MDADS";