WITH TMP AS (
    SELECT 
        B.PERIOD,
        A.PRODUCT_TYPE_SC,
        A.PRODUCT_CODE,
        SUM(lq) AS MONTHLY_IN_QUANTITY
    FROM 
        MDDWD.DWD_STKCFLB A
        LEFT JOIN MDDWD.DWD_TPC_HWJCB B
        ON A.PRODUCT_CODE = (CASE WHEN B.PRODUCT_SPECIFICATION IS NULL OR B.PRODUCT_SPECIFICATION='' 
                               THEN B.PRODUCT_VARIETY 
                               ELSE B.PRODUCT_VARIETY ||'_'|| B.PRODUCT_SPECIFICATION END)  
    WHERE
        A.PRODUCT_CODE IN (
            SELECT PRODUCT_CODE
            FROM MDDWD.DWD_XSGXDYB C
            WHERE
                C.PRODUCT_SORT1 = '球铁'
                AND C.START_TIME <= SYSDATE
                AND C.END_TIME >= SYSDATE
        )
    GROUP BY 
        B.PERIOD,
        A.PRODUCT_TYPE_SC,
        A.PRODUCT_CODE
)



SELECT 
    PERIOD_DATE,  --日期
    PRODUCT_TYPE_SC,--产品类型
    PRODUCT_CODE,--产品编码
    MONTHLY_IN_QUANTITY,--月入库量
    LAG(MONTHLY_IN_QUANTITY, 12) OVER (PARTITION BY PRODUCT_TYPE_SC, PRODUCT_CODE ORDER BY PERIOD_DATE) AS SAMEP_MONTH_IN_QUANTITY,--同期入库量
    LAG(MONTHLY_IN_QUANTITY, 1) OVER (PARTITION BY PRODUCT_TYPE_SC, PRODUCT_CODE ORDER BY PERIOD_DATE) AS LAST_MONTH_IN_QUANTITY--上月入库量
FROM TMP
