CREATE TABLE ODS_ERP.ODS_TPC_BZRKB (
    ID NUMBER,
    RQ VARCHAR2(2000),
    RKBM VARCHAR2(2000),
    RKDW VARCHAR2(2000),
    DDH VARCHAR2(2000),
    JHQ VARCHAR2(2000),
    KHM VARCHAR2(2000),
    LH VARCHAR2(2000),
    LH VARCHAR2(2000),
    PZ VARCHAR2(2000),
    GG VARCHAR2(2000),
    XS VARCHAR2(2000),
    ZL NUMBER,
    ZCBM VARCHAR2(2000),
    ZCDW VARCHAR2(2000),
    CKBM VARCHAR2(2000),
    CKMC VARCHAR2(2000),
    LQHWH VARCHAR2(2000),
    DJLSH VARCHAR2(2000),
    SJLY VARCHAR2(2000),
    LRY VARCHAR2(2000),
    GXSJ DATE,
    CH VARCHAR2(2000),
    CDBS NUMBER,
    LRFSYY VARCHAR2(2000),
    TL NUMBER,
    WG NUMBER,
    TSGH VARCHAR2(2000),
    ETL_CRT_DT DATE,
    ETL_UPD_DT DATE
);

SELECT
    ,id
    ,rq
    ,rkbm
    ,rkdw
    ,ddh
    ,jhq
    ,khm
    ,lh
    ,lch
    ,pz
    ,gg
    ,xs
    ,zl
    ,zcbm
    ,zcdw
    ,ckbm
    ,ckmc
    ,lqhwh
    ,djlsh
    ,sjly
    ,lry
    ,gxsj
    ,ch
    ,cdbs
    ,lrfsyy
    ,tl
    ,wg
    ,tsgh
    ,ztjh
    ,bc
FROM 
