CREATE TABLE "ODS_ERP"."ODS_FPSJB_CKYW_ALL" 
   (	"ID" NUMBER, 
	"RQ" VARCHAR2(2000), 
	"TFPBM" VARCHAR2(2000), 
	"TFPDW" VARCHAR2(2000), 
	"ZFKBM" VARCHAR2(2000), 
	"ZFKDW" VARCHAR2(2000), 
	"JJCBM" VARCHAR2(2000), 
	"JJCDW" VARCHAR2(2000), 
	"LXBS" VARCHAR2(2000), 
	"FPLX" VARCHAR2(2000), 
	"PZ" VARCHAR2(2000), 
	"GG" VARCHAR2(2000), 
	"XS" VARCHAR2(2000), 
	"DZ" NUMBER, 
	"JS" NUMBER, 
	"LRY" VARCHAR2(2000), 
	"GXSJ" DATE, 
	"ZJGH" VARCHAR2(2000), 
	"ZJGXM" VARCHAR2(2000), 
	"KFG" VARCHAR2(2000), 
	"LCH" VARCHAR2(2000), 
	"JH" VARCHAR2(2000), 
	"CZZDM" VARCHAR2(2000), 
	"FKBM1" VARCHAR2(2000), 
	"FKDW1" VARCHAR2(2000), 
	"BC" VARCHAR2(2000), 
	"MPDZ" NUMBER, 
	"SPFP" VARCHAR2(2000), 
	"MH" VARCHAR2(2000), 
	"MJBH" VARCHAR2(2000), 
	"XJS" NUMBER, 
	"FPLX1" VARCHAR2(2000), 
	"BS" VARCHAR2(2000), 
	"DJ" NUMBER, 
	"SSDJ1" NUMBER, 
	"SSDJ2" NUMBER, 
	"JE" NUMBER, 
	"FPSSE" NUMBER, 
	"FPSSE1" NUMBER, 
	"ZXS" VARCHAR2(2000), 
	"LJTDD" NUMBER, 
	"ZFKDWSCRQ" VARCHAR2(2000), 
	"CD" NUMBER, 
	"JSRQ" VARCHAR2(2000), 
	"FPH" VARCHAR2(2000), 
	"JSBJ" VARCHAR2(2000), 
	"JSDH" VARCHAR2(2000), 
	"HWH" VARCHAR2(2000), 
	"CZFL" VARCHAR2(2000), 
	"BMCL" VARCHAR2(2000), 
	"SCGY" VARCHAR2(2000), 
	"SCX" VARCHAR2(2000), 
	"DYJS" NUMBER, 
	"ZL" NUMBER, 
	"SPDJ" NUMBER, 
	"SPE" NUMBER, 
	"DJGXBZ" VARCHAR2(2000), 
	"FPSSDJ" NUMBER, 
	"SSDJGXBZ" VARCHAR2(2000), 
	"BZ" VARCHAR2(2000), 
	"ZZHGLDW" VARCHAR2(2000), 
	"ZFDW" VARCHAR2(2000), 
	"KJ" NUMBER, 
	"ZLCZFL" VARCHAR2(2000), 
	"TFPGX" VARCHAR2(2000), 
	"ZZHGLJSDW" VARCHAR2(2000), 
	"BZWLX" VARCHAR2(2000), 
	"GDH" VARCHAR2(2000), 
	"KBH" VARCHAR2(2000), 
	"SJLY" VARCHAR2(2000), 
	"CDBS" NUMBER, 
	"CPBM" VARCHAR2(2000), 
	"GYS" VARCHAR2(2000), 
	"ZJBID" NUMBER, 
	"UT" VARCHAR2(2000), 
	"TCXMLX" VARCHAR2(2000), 
	"ETL_CRT_DT" DATE DEFAULT SYSDATE, 
	"ETL_UPD_DT" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ODS_ERP_DAT" ;
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."ID" IS '序号';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."RQ" IS '日期';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."TFPBM" IS '退废品编码';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."TFPDW" IS '退废品单位';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."ZFKBM" IS '支罚款编码';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."ZFKDW" IS '支罚款单位';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."JJCBM" IS '减结存编码';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."JJCDW" IS '减结存单位';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."LXBS" IS '类型标示';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."FPLX" IS '废品类型';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."PZ" IS '品种';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."GG" IS '规格';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."XS" IS '形式';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."DZ" IS '单重';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."JS" IS '件数';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."LRY" IS '录入员';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."GXSJ" IS '更新时间';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."ZJGH" IS '质检工号';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."ZJGXM" IS '质检工姓名';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."KFG" IS '库分工';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."LCH" IS '炉次号';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."JH" IS '件号';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."CZZDM" IS '操作者代码';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."FKBM1" IS '罚款编码1';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."FKDW1" IS '罚款单位1';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."BC" IS '班次';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."MPDZ" IS '毛坯单重';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."SPFP" IS '生坯废品';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."MH" IS '模号';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."MJBH" IS '模具编号';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."XJS" IS '箱件数';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."FPLX1" IS '废品类型1';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."BS" IS '标示';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."DJ" IS '单价';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."SSDJ1" IS '损失单价1';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."SSDJ2" IS '损失单价2';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."JE" IS '罚款额1';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."FPSSE" IS '废品损失额';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."FPSSE1" IS '废品损失1';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."ZXS" IS '主形式';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."LJTDD" IS '累计投订单';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."ZFKDWSCRQ" IS '';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."CD" IS '长度';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."JSRQ" IS '';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."FPH" IS '';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."JSBJ" IS '';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."JSDH" IS '结算单号';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."HWH" IS '货位号';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."CZFL" IS '材质分类';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."BMCL" IS '表面处理';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."SCGY" IS '';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."SCX" IS '生产线';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."DYJS" IS '';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."ZL" IS '重量';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."SPDJ" IS '索赔单价';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."SPE" IS '索赔额';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."DJGXBZ" IS '单价更新备注';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."FPSSDJ" IS '废品损失单价';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."SSDJGXBZ" IS '损失单价更新备注';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."BZ" IS '班组';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."ZZHGLDW" IS '铸造合格率单位';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."ZFDW" IS '支付单位';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."KJ" IS '口径';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."ZLCZFL" IS '质量材质分类';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."TFPGX" IS '退废品工序';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."ZZHGLJSDW" IS '合格率单位';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."BZWLX" IS '';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."GDH" IS '工单号';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."KBH" IS '看板号';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."SJLY" IS '';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."CDBS" IS '';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."CPBM" IS '产品编码';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."GYS" IS '';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."ZJBID" IS '';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."UT" IS '';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."TCXMLX" IS '';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."ETL_CRT_DT" IS '';
   COMMENT ON COLUMN "ODS_ERP"."ODS_FPSJB_CKYW_ALL"."ETL_UPD_DT" IS '';
   COMMENT ON TABLE "ODS_ERP"."ODS_FPSJB_CKYW_ALL"  IS '废品数据表';