WITH PS AS(

     SELECT A.SCX,A.CQ,A.GW,A.XM,B.PS_USER_ID AS PSID
     FROM ODS_ERP.ODS_TSRYJCK A LEFT JOIN MDDWI.TF_DWI_EMPLOYEE B 
     ON B.EMPLID=A.ID  
 )


  SELECT 
      SCX AS 生产线,
      CQ AS 厂区,
      LISTAGG(CASE WHEN GW = '科长' THEN XM END, ',') WITHIN GROUP (ORDER BY XM) AS 科长级别预警,
      LISTAGG(CASE WHEN GW = '总裁' THEN XM END, ',') WITHIN GROUP (ORDER BY XM) AS 总裁级别预警,
      LISTAGG(CASE WHEN GW = '主席' THEN XM END, ',') WITHIN GROUP (ORDER BY XM) AS 主席级别预警
  FROM PS
  WHERE SCX NOT IN ('董事局主席团','生产管理中心','质量运营及流程IT部')
  GROUP BY SCX, CQ


  ---------------------------------------------------------------------
  
  
  
-- 第一步：插入基础数据（排除三个特殊部门）
INSERT INTO ADS_ORDER_OVERDUE_WARNING (
    PRODUCTION_LINE,
    PLANT,
    MANAGER_LEVEL_WARNING,
    PRESIDENT_LEVEL_WARNING,
    CHAIRMAN_LEVEL_WARNING,
    ETL_CRT_DT,
    ETL_UPD_DT
)
WITH PS AS (
    SELECT 
        A.SCX,
        A.CQ,
        A.GW,
        A.XM,
        B.PS_USER_ID AS PSID
    FROM ODS_ERP.ODS_TSRYJCK A 
    LEFT JOIN MDDWI.TF_DWI_EMPLOYEE B ON B.EMPLID = A.ID  
)
SELECT 
    SCX AS PRODUCTION_LINE,
    CQ AS PLANT,
    LISTAGG(CASE WHEN GW = '科长' THEN PSID END, ',') WITHIN GROUP (ORDER BY XM) AS MANAGER_LEVEL_WARNING,
    LISTAGG(CASE WHEN GW = '总裁' THEN PSID END, ',') WITHIN GROUP (ORDER BY XM) AS PRESIDENT_LEVEL_WARNING,
    LISTAGG(CASE WHEN GW = '主席' THEN PSID END, ',') WITHIN GROUP (ORDER BY XM) AS CHAIRMAN_LEVEL_WARNING,
    SYSDATE,
    SYSDATE
FROM PS
WHERE SCX NOT IN ('董事局主席团', '生产管理中心', '质量运营及流程IT部')
GROUP BY SCX, CQ;

-- 第二步：追加三个特殊部门的告警人员
MERGE INTO ADS_ORDER_OVERDUE_WARNING TGT
USING (
    WITH SPECIAL_DEPT AS (
        SELECT 
            GW,
            LISTAGG(PSID, ',') WITHIN GROUP (ORDER BY XM) AS PSIDS
        FROM (
            SELECT 
                A.GW,
                A.XM,
                B.PS_USER_ID AS PSID
            FROM ODS_ERP.ODS_TSRYJCK A 
            LEFT JOIN MDDWI.TF_DWI_EMPLOYEE B ON B.EMPLID = A.ID
            WHERE A.SCX IN ('董事局主席团', '生产管理中心', '质量运营及流程IT部')
        )
        GROUP BY GW
    )
    SELECT 
        NVL(MAX(CASE WHEN GW = '科长' THEN PSIDS END), '') AS MANAGER_PSIDS,
        NVL(MAX(CASE WHEN GW = '总裁' THEN PSIDS END), '') AS PRESIDENT_PSIDS,
        NVL(MAX(CASE WHEN GW = '主席' THEN PSIDS END), '') AS CHAIRMAN_PSIDS
    FROM SPECIAL_DEPT
) SRC
ON (1=1)
WHEN MATCHED THEN UPDATE SET 
    MANAGER_LEVEL_WARNING = 
        CASE 
            WHEN TGT.MANAGER_LEVEL_WARNING IS NULL THEN SRC.MANAGER_PSIDS
            ELSE TGT.MANAGER_LEVEL_WARNING || ',' || SRC.MANAGER_PSIDS 
        END,
    PRESIDENT_LEVEL_WARNING = 
        CASE 
            WHEN TGT.PRESIDENT_LEVEL_WARNING IS NULL THEN SRC.PRESIDENT_PSIDS
            ELSE TGT.PRESIDENT_LEVEL_WARNING || ',' || SRC.PRESIDENT_PSIDS 
        END,
    CHAIRMAN_LEVEL_WARNING = 
        CASE 
            WHEN TGT.CHAIRMAN_LEVEL_WARNING IS NULL THEN SRC.CHAIRMAN_PSIDS
            ELSE TGT.CHAIRMAN_LEVEL_WARNING || ',' || SRC.CHAIRMAN_PSIDS 
        END,
    ETL_UPD_DT = SYSDATE;