CREATE TABLE ADS_CQWDLYL (
    ID NUMBER,
    MONTH VARCHAR2(2000),
    ENTERPRISE_TYPE VARCHAR2(2000),
    PRODUCTION_LINE VARCHAR2(2000),
    PLANT VARCHAR2(2000),
    TOTAL_ORDERS NUMBER,
    TOTAL_ADJUSTED_ORDERS NUMBER,
    ORDER_ADJUSTMENT_RATE VARCHAR2(2000),
    TOTAL_DELAYED_ORDERS NUMBER,
    ORDER_DELAY_RATE VARCHAR2(2000),
    DEDUPLICATED_ISSUES NUMBER,
    FULFILLMENT_RATE VARCHAR2(2000),
    MONTH_ON_MONTH VARCHAR2(2000),
    YEAR_ON_YEAR VARCHAR2(2000),
    ETL_CRT_DT DATE,
    ETL_UPD_DT DATE
);


COMMENT ON COLUMN ADS_CQWDLYL.ID IS '序号';
COMMENT ON COLUMN ADS_CQWDLYL.MONTH IS '月份';
COMMENT ON COLUMN ADS_CQWDLYL.ENTERPRISE_TYPE IS '企业类型';
COMMENT ON COLUMN ADS_CQWDLYL.PRODUCTION_LINE IS '生产线';
COMMENT ON COLUMN ADS_CQWDLYL.PLANT IS '厂区';
COMMENT ON COLUMN ADS_CQWDLYL.TOTAL_ORDERS IS '订单总个数';
COMMENT ON COLUMN ADS_CQWDLYL.TOTAL_ADJUSTED_ORDERS IS '订单调整总个数';
COMMENT ON COLUMN ADS_CQWDLYL.ORDER_ADJUSTMENT_RATE IS '订单调整率';
COMMENT ON COLUMN ADS_CQWDLYL.TOTAL_DELAYED_ORDERS IS '订单拖期总个数';
COMMENT ON COLUMN ADS_CQWDLYL.ORDER_DELAY_RATE IS '订单拖期率';
COMMENT ON COLUMN ADS_CQWDLYL.DEDUPLICATED_ISSUES IS '调整和拖期去重后个数';
COMMENT ON COLUMN ADS_CQWDLYL.FULFILLMENT_RATE IS '订单履约率';
COMMENT ON COLUMN ADS_CQWDLYL.MONTH_ON_MONTH IS '环比';
COMMENT ON COLUMN ADS_CQWDLYL.YEAR_ON_YEAR IS '同比';