INSERT INTO ADS_OVERDUE_DETAIL (
    PERIOD,
    PRODUCTION_LINE,
    FACTORY,
    CUSTOMER_NAME,
    DELIVERY_DATE,
    ORDER_ID,
    DELAY_DAYS,
    PACKING_CHANGE_REASON,
    ETL_CRT_DT,
    ETL_UPD_DT
)
WITH TMP AS (
    SELECT 
        NVL(TRUNC(ASSESSMENT_DATE,'MM'),TRUNC(DELIVERY_DATE,'MM')) AS PERIOD,
        PRODUCTION_LINE,
        FACTORY,
        CUSTOMER_NAME,
        DELIVERY_DATE,
        ORDER_ID,
        DELAY_DAYS,
        PACKING_CHANGE_REASON
    FROM (
        SELECT 
            T.*,
            ROW_NUMBER() OVER (PARTITION BY ORDER_ID ORDER BY ASSESSMENT_DATE DESC) AS RN
        FROM MDDWD.DWD_DDTQKHHZB T
    )
    WHERE RN = 1 AND TRUNC(ASSESSMENT_DATE,'MM')!=TRUNC(DELIVERY_DATE,'MM')
    AND DELAY_TYPE IN (
        SELECT DISTINCT TQLB FROM ODS_ERP.ODS_DDTQZRBMJCK
    )
    AND DELAY_TYPE NOT LIKE '剔除%'
    AND DELAY_TYPE !='漏收托'
    AND DELAY_TYPE !='晚核销'
)
SELECT 
    PERIOD,
    PRODUCTION_LINE,
    FACTORY,
    CUSTOMER_NAME,
    DELIVERY_DATE,
    ORDER_ID,
    DELAY_DAYS,
    PACKING_CHANGE_REASON,
    SYSDATE,
    SYSDATE
FROM TMP;