INSERT INTO ADS_OVERDUE_DETAIL (
    PERIOD,
    PRODUCTION_LINE,
    FACTORY,
    CUSTOMER_NAME,
    DELIVERY_DATE,
    ORDER_ID,
    DELAY_DAYS,
    PACKING_CHANGE_REASON,
    REAL_FINISH_DATE
    ETL_CRT_DT,
    ETL_UPD_DT
)
WITH TMP AS (
    SELECT 
        NVL(TRUNC(ASSESSMENT_DATE,'MM'),TRUNC(DELIVERY_DATE,'MM')) AS PERIOD,
        PRODUCTION_LINE,
        FACTORY,
        CUSTOMER_NAME,
        DELIVERY_DATE,
        ORDER_ID,
        DELAY_DAYS,
        PACKING_CHANGE_REASON
    FROM (
        SELECT 
            T.*,
            ROW_NUMBER() OVER (PARTITION BY ORDER_ID ORDER BY ASSESSMENT_DATE DESC) AS RN
        FROM MDDWD.DWD_DDTQKHHZB T
    )
    WHERE RN = 1 AND TRUNC(ASSESSMENT_DATE,'MM')!=TRUNC(DELIVERY_DATE,'MM')
    AND DELAY_TYPE IN (
        SELECT DISTINCT TQLB FROM ODS_ERP.ODS_DDTQZRBMJCK
    )
    AND DELAY_TYPE NOT LIKE '剔除%'
    AND DELAY_TYPE !='漏收托'
    AND DELAY_TYPE !='晚核销'
)
SELECT 
    PERIOD,
    PRODUCTION_LINE,
    FACTORY,
    CUSTOMER_NAME,
    DELIVERY_DATE,
    ORDER_ID,
    DELAY_DAYS,
    PACKING_CHANGE_REASON,
    SYSDATE,
    SYSDATE
FROM TMP;
-------------------------------------------------------------------------------------------20250909

truncate table ADS_OVERDUE_DETAIL;
INSERT INTO ADS_OVERDUE_DETAIL (
    PERIOD,
    PRODUCTION_LINE,
    FACTORY,
    CUSTOMER_NAME,
    DELIVERY_DATE,
    ORDER_ID,
    DELAY_DAYS,
    REAL_FINISH_DATE,
    PACKING_CHANGE_REASON,
    ETL_CRT_DT,
    ETL_UPD_DT
)
WITH TMP AS (
    SELECT 
        NVL(TRUNC(ASSESSMENT_DATE,'MM'),TRUNC(DELIVERY_DATE,'MM')) AS PERIOD,
        PRODUCTION_LINE,
        FACTORY,
        CUSTOMER_NAME,
        DELIVERY_DATE,
        ORDER_ID,
        DELAY_DAYS,
        WAREHOUSE_ADJUST_DATE,
        PACKING_CHANGE_REASON
/*
    FROM (
        SELECT 
            T.*,
            ROW_NUMBER() OVER (PARTITION BY ORDER_ID ORDER BY ASSESSMENT_DATE DESC) AS RN
        FROM MDDWD.DWD_DDTQKHHZB T
    )
    WHERE RN = 1 AND TRUNC(ASSESSMENT_DATE,'MM')=TRUNC(DELIVERY_DATE,'MM')
    AND DELAY_TYPE IN (
        SELECT DISTINCT TQLB FROM ODS_ERP.ODS_DDTQZRBMJCK
    )
    AND DELAY_TYPE NOT LIKE '剔除%'
    AND DELAY_TYPE !='漏收托'
    AND DELAY_TYPE !='晚核销'
*/
    FROM (
        SELECT 
            T.*,
            ROW_NUMBER() OVER (PARTITION BY ORDER_ID ORDER BY ASSESSMENT_DATE DESC) AS RN
        FROM MDDWD.DWD_DDTQKHHZB T
    ) A
    LEFT JOIN (
        SELECT DISTINCT TQLB,BMLX FROM ODS_ERP.ODS_DDTQZRBMJCK
    ) B ON A.DELAY_TYPE=B.TQLB
    WHERE 
    A.RN = 1 
    AND TRUNC(ASSESSMENT_DATE,'MM')=TRUNC(DELIVERY_DATE,'MM')
     AND DELAY_TYPE not like '剔除%'
     AND DELAY_TYPE !='漏收托'
     AND DELAY_TYPE !='晚核销'
    AND B.TQLB IS NOT NULL
)
SELECT 
    PERIOD,
    PRODUCTION_LINE,
    FACTORY,
    CUSTOMER_NAME,
    DELIVERY_DATE,
    ORDER_ID,
    DELAY_DAYS,
    WAREHOUSE_ADJUST_DATE,
    PACKING_CHANGE_REASON,
    SYSDATE,
    SYSDATE
FROM TMP;





-----------------------------------------------20250910

truncate table ADS_OVERDUE_DETAIL;
INSERT INTO ADS_OVERDUE_DETAIL (
    PERIOD,
    PRODUCTION_LINE,
    FACTORY,
    CUSTOMER_NAME,
    DELIVERY_DATE,
    ORDER_ID,
    DELAY_DAYS,
    REAL_FINISH_DATE,
    PACKING_CHANGE_REASON,
    ETL_CRT_DT,
    ETL_UPD_DT
)
WITH TMP AS (
    SELECT 
        NVL(TRUNC(ASSESSMENT_DATE,'MM'),TRUNC(DELIVERY_DATE,'MM')) AS PERIOD,
        PRODUCTION_LINE,
        FACTORY,
        CUSTOMER_NAME,
        DELIVERY_DATE,
        ORDER_ID,
        DELAY_DAYS,
        WAREHOUSE_ADJUST_DATE,
        PACKING_CHANGE_REASON

    FROM (
        SELECT 
            T.*,
            ROW_NUMBER() OVER (PARTITION BY ORDER_ID ORDER BY ASSESSMENT_DATE DESC) AS RN
        FROM MDDWD.DWD_DDTQKHHZB T
    )
    WHERE RN = 1 AND TRUNC(ASSESSMENT_DATE,'MM')=TRUNC(DELIVERY_DATE,'MM')
    AND DELAY_TYPE IN (
        SELECT DISTINCT TQLB FROM ODS_ERP.ODS_DDTQZRBMJCK
    )
    AND DELAY_TYPE NOT LIKE '%剔除%'
    AND DELAY_TYPE !='漏收托'
    AND DELAY_TYPE !='晚核销'
/*
    FROM (
        SELECT 
            T.*,
            ROW_NUMBER() OVER (PARTITION BY ORDER_ID ORDER BY ASSESSMENT_DATE DESC) AS RN
        FROM MDDWD.DWD_DDTQKHHZB T
    ) A
    LEFT JOIN (
        SELECT DISTINCT TQLB,BMLX FROM ODS_ERP.ODS_DDTQZRBMJCK
    ) B ON A.DELAY_TYPE=B.TQLB
    WHERE 
    A.RN = 1 
    AND TRUNC(ASSESSMENT_DATE,'MM')=TRUNC(DELIVERY_DATE,'MM')
     AND DELAY_TYPE not like '剔除%'
     AND DELAY_TYPE !='漏收托'
     AND DELAY_TYPE !='晚核销'
    AND B.TQLB IS NOT NULL
    */
)
SELECT 
    PERIOD,
    PRODUCTION_LINE,
    FACTORY,
    CUSTOMER_NAME,
    DELIVERY_DATE,
    ORDER_ID,
    DELAY_DAYS,
    WAREHOUSE_ADJUST_DATE,
    PACKING_CHANGE_REASON,
    SYSDATE,
    SYSDATE
FROM TMP;