CREATE TABLE ADS_SCXWDLYL (
    ID NUMBER,
    MONTH VARCHAR2(2000),
    ENTERPRISE_TYPE VARCHAR2(2000),
    PRODUCTION_LINE VARCHAR2(2000),
    TOTAL_ORDERS NUMBER,
    TOTAL_ADJUSTED_ORDERS NUMBER,
    ORDER_ADJUSTMENT_RATE VARCHAR2(2000),
    TOTAL_DELAYED_ORDERS NUMBER,
    ORDER_DELAY_RATE VARCHAR2(2000),
    DEDUPLICATED_ISSUES NUMBER,
    FULFILLMENT_RATE VARCHAR2(2000),
    MONTH_ON_MONTH VARCHAR2(2000),
    YEAR_ON_YEAR VARCHAR2(2000),
    ETL_CRT_DT DATE,
    ETL_UPD_DT DATE
);
COMMENT ON COLUMN ADS_SCXWDLYL.ID IS '序号';
COMMENT ON COLUMN ADS_SCXWDLYL.MONTH IS '月份';
COMMENT ON COLUMN ADS_SCXWDLYL.ENTERPRISE_TYPE IS '企业类型';
COMMENT ON COLUMN ADS_SCXWDLYL.PRODUCTION_LINE IS '生产线';
COMMENT ON COLUMN ADS_SCXWDLYL.TOTAL_ORDERS IS '订单总个数';
COMMENT ON COLUMN ADS_SCXWDLYL.TOTAL_ADJUSTED_ORDERS IS '订单调整总个数';
COMMENT ON COLUMN ADS_SCXWDLYL.ORDER_ADJUSTMENT_RATE IS '订单调整率';
COMMENT ON COLUMN ADS_SCXWDLYL.TOTAL_DELAYED_ORDERS IS '订单拖期总个数';
COMMENT ON COLUMN ADS_SCXWDLYL.ORDER_DELAY_RATE IS '订单拖期率';
COMMENT ON COLUMN ADS_SCXWDLYL.DEDUPLICATED_ISSUES IS '调整和拖期去重后个数';
COMMENT ON COLUMN ADS_SCXWDLYL.FULFILLMENT_RATE IS '订单履约率';
COMMENT ON COLUMN ADS_SCXWDLYL.MONTH_ON_MONTH IS '环比';
COMMENT ON COLUMN ADS_SCXWDLYL.YEAR_ON_YEAR IS '同比';

TRUNCATE TABLE MDADS.ADS_SCXWDLYL;

INSERT INTO MDADS.ADS_SCXWDLYL (
    ID,
    MONTH,
    ENTERPRISE_TYPE,
    PRODUCTION_LINE,
    TOTAL_ORDERS,
    TOTAL_ADJUSTED_ORDERS,
    ORDER_ADJUSTMENT_RATE,
    TOTAL_DELAYED_ORDERS,
    ORDER_DELAY_RATE,
    DEDUPLICATED_ISSUES,
    FULFILLMENT_RATE,
    MONTH_ON_MONTH,
    YEAR_ON_YEAR,
    ETL_CRT_DT,
    ETL_UPD_DT
)

  SELECT 
    ID,
    YF,
    QYLX,
    SCX,
    DDGS,
    DDTZZGS,
    DDTZTZL,
    DDTQZGS,
    DDTQTQL,
    TQJTZ,
    LYL,
    HB,
    TB,
    ETL_CRT_DT,
    ETL_UPD_DT
FROM ODS_ERP.ODS_SCXWDLYL

UNION ALL
    
SELECT 
    null AS ID,
    YF,
    '合计' AS QYLX,
    '合计' AS SCX,
    SUM(DDGS),
    SUM(DDTZZGS),
    null,
    SUM(DDTQZGS),
    null,
    SUM(TQJTZ),
    to_char( round(CASE WHEN SUM(DDGS) = 0 THEN 0 ELSE (SUM(DDGS)-SUM(TQJTZ))/SUM(DDGS)  END,4)*100)||'%',
    NULL,
    NULL,
    MAX(ETL_CRT_DT),
    MAX(ETL_UPD_DT)
FROM ODS_ERP.ODS_SCXWDLYL
GROUP BY YF;