-- 创建结果表
CREATE TABLE DWD_LYLCQJCK (
    PERIOD_DATE DATE,
    SCX VARCHAR2(2000),
    CQ VARCHAR2(2000),
    LRY VARCHAR2(2000),
    GXSJ DATE,
    ETL_CRT_DT DATE DEFAULT SYSDATE,
    ETL_UPD_DT DATE DEFAULT SYSDATE
);

COMMENT ON TABLE DWD_LYLCQJCK IS '厂区基础信息查询结果表';

COMMENT ON COLUMN DWD_LYLCQJCK.PERIOD_DATE IS '期间日期';
COMMENT ON COLUMN DWD_LYLCQJCK.SCX IS '生产线';
COMMENT ON COLUMN DWD_LYLCQJCK.CQ IS '厂区';
COMMENT ON COLUMN DWD_LYLCQJCK.LRY IS '录入人';
COMMENT ON COLUMN DWD_LYLCQJCK.GXSJ IS '更新时间';
COMMENT ON COLUMN DWD_LYLCQJCK.ETL_CRT_DT IS 'ETL创建时间';
COMMENT ON COLUMN DWD_LYLCQJCK.ETL_UPD_DT IS 'ETL更新时间';

-- INSERT语句（插入查询结果）
INSERT INTO DWD_LYLCQJCK (
    PERIOD_DATE,
    SCX,
    CQ,
)

SELECT 
    DISTINCT
    B.PERIOD_DATE,
    A.SCX,
    A.CQ

FROM ODS_ERP.ODS_LYLCQJCK A
CROSS JOIN MDDIM.DIM_MONTH_D B
WHERE 
    B.PERIOD_DATE > DATE '2023-12-01'
    AND B.PERIOD_DATE < SYSDATE
    AND A.SCX NOT IN ('迈科管业','波兰EE');










SELECT 
    B.PERIOD_DATE,
    A.SCX ,
    A.CQ ,
    A.LRY ,
    A.GXSJ
FROM ODS_ERP.ODS_LYLCQJCK A
    CROSS JOIN MDDIM.DIM_MONTH_D B
WHERE 
    B.PERIOD_DATE > DATE '2023-12-1'
    AND B.PERIOD_DATE < SYSDATE