CREATE TABLE ODS_LYLCQJCK (
    ID NUMBER,
    SCX VARCHAR2(2000),
    CQ VARCHAR2(2000),
    LRY VARCHAR2(2000),
    GXSJ DATE,
    ETL_CRT_DT DATE,
    ETL_UPD_DT DATE
);

COMMENT ON TABLE ODS_LYLCQJCK IS '履约率厂区基础信息表';

COMMENT ON COLUMN ODS_LYLCQJCK.ID IS '序号';
COMMENT ON COLUMN ODS_LYLCQJCK.SCX IS '生产线';
COMMENT ON COLUMN ODS_LYLCQJCK.CQ IS '厂区';
COMMENT ON COLUMN ODS_LYLCQJCK.LRY IS '录入人';
COMMENT ON COLUMN ODS_LYLCQJCK.GXSJ IS '更新时间';
COMMENT ON COLUMN ODS_LYLCQJCK.ETL_CRT_DT IS 'ETL创建时间';
COMMENT ON COLUMN ODS_LYLCQJCK.ETL_UPD_DT IS 'ETL更新时间';