CREATE TABLE "MDADS"."ADS_ORDER_OVERDUE_WARNING2" 
   (	"PRODUCTION_LINE" VARCHAR2(2000), 
	"PLANT" VARCHAR2(2000), 
	"MANAGER_LEVEL_WARNING" VARCHAR2(4000), 
	"PRESIDENT_LEVEL_WARNING" VARCHAR2(4000), 
	"CHAIRMAN_LEVEL_WARNING" VARCHAR2(4000), 
	"ETL_CRT_DT" DATE, 
	"ETL_UPD_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MDADS_DAT" ;
   COMMENT ON COLUMN "MDADS"."ADS_ORDER_OVERDUE_WARNING2"."PRODUCTION_LINE" IS '生产线';
   COMMENT ON COLUMN "MDADS"."ADS_ORDER_OVERDUE_WARNING2"."PLANT" IS '厂区';
   COMMENT ON COLUMN "MDADS"."ADS_ORDER_OVERDUE_WARNING2"."MANAGER_LEVEL_WARNING" IS '科长级别预警人员';
   COMMENT ON COLUMN "MDADS"."ADS_ORDER_OVERDUE_WARNING2"."PRESIDENT_LEVEL_WARNING" IS '总裁级别预警人员';
   COMMENT ON COLUMN "MDADS"."ADS_ORDER_OVERDUE_WARNING2"."CHAIRMAN_LEVEL_WARNING" IS '主席级别预警人员';



   INSERT INTO ADS_ORDER_OVERDUE_WARNING2 (
    PRODUCTION_LINE,
    PLANT,
    MANAGER_LEVEL_WARNING,
    PRESIDENT_LEVEL_WARNING,
    CHAIRMAN_LEVEL_WARNING,
    ETL_CRT_DT,
    ETL_UPD_DT
)
WITH PS AS (
    SELECT 
        A.SCX,
        A.CQ,
        A.GW,
        A.XM,
        B.PS_USER_ID AS PSID
    FROM ODS_ERP.ODS_TSRYJCK A 
    LEFT JOIN MDDWI.TF_DWI_EMPLOYEE B ON B.EMPLID = A.ID  
)
SELECT 
    SCX AS PRODUCTION_LINE,
    CQ AS PLANT,
    LISTAGG(CASE WHEN GW = '科长' THEN PSID END, ',') WITHIN GROUP (ORDER BY XM) AS MANAGER_LEVEL_WARNING,
    LISTAGG(CASE WHEN GW = '总裁' THEN PSID END, ',') WITHIN GROUP (ORDER BY XM) AS PRESIDENT_LEVEL_WARNING,
    LISTAGG(CASE WHEN GW = '主席' THEN PSID END, ',') WITHIN GROUP (ORDER BY XM) AS CHAIRMAN_LEVEL_WARNING,
    SYSDATE,
    SYSDATE
FROM PS
WHERE SCX NOT IN ('董事局主席团', '生产管理中心', '质量运营及流程IT部')
GROUP BY SCX, CQ;