BEGIN
IF EXTRACT(MONTH FROM SYSDATE) IN ('1', '7') THEN
  

EXECUTE IMMEDIATE 'TRUNCATE TABLE MDADS.ADS_CAPACITY_1';
INSERT INTO MDADS.ADS_CAPACITY_1
(
    PERIOD
    ,PRODUCE_COMPANY_NAME_SN
    ,PRODUCTION_LINE
    ,CAPACITY_TYPE
    ,WORKING_DAYS
    ,MONTHLY_CAPACITY
    ,YEAR_CAPACITY
    ,UNIT
    ,IN_SALE_BEGIN
    ,OVER_SALE_BEGIN
    ,IN_SALE_MID
    ,OVER_SALE_MID
    ,ETL_CRT_DT
    ,ETL_UPD_DT

)
WITH MIN_DT AS (
    SELECT  SALE_PLATFORM_NAME
            ,TRUNC(MIN(CASE WHEN TO_CHAR(ETL_CRT_DT, 'MM') >= '01' AND TO_CHAR(ETL_CRT_DT, 'MM') <= '06' THEN ETL_CRT_DT END)) AS BEG_YEAR
            ,TRUNC(MIN(CASE WHEN TO_CHAR(ETL_CRT_DT, 'MM') >= '07' AND TO_CHAR(ETL_CRT_DT, 'MM') <= '12' THEN ETL_CRT_DT END)) AS MID_YEAR
    FROM    ODS_APD.ODS_APD_SALES_TARGET
    WHERE   INDEX_TYPE = '收入'
        AND SALES_TARGET_TYPE = '挑战'
        AND SALE_PLATFORM_NAME IN ('国内销售平台', '海外销售平台')
        AND YEAR = TO_CHAR(TRUNC(SYSDATE, 'YYYY'), 'YYYY')
    GROUP BY    SALE_PLATFORM_NAME
)
,
TAR AS (
    SELECT  ST.CORPORATE_ENTITY_NAME_SN
            ,ST.PRODUCT_SORT1
            ,ST.PRODUCT_SORT2
            ,ST.PRODUCT_SORT3
            ,SUM(CASE WHEN ST.SALE_PLATFORM_NAME = '国内销售平台' THEN ST.ANNUAL_TARGET_TON ELSE 0 END) AS SALE_TARGET_TON_GN_BEG
            ,SUM(CASE WHEN ST.SALE_PLATFORM_NAME = '海外销售平台' THEN ST.ANNUAL_TARGET_TON ELSE 0 END) AS SALE_TARGET_TON_HW_BEG
            ,0 AS SALE_TARGET_TON_GN_MID
            ,0 AS SALE_TARGET_TON_HW_MID
    FROM    MIN_DT
    LEFT JOIN   ODS_APD.ODS_APD_SALES_TARGET    ST
    ON  MIN_DT.BEG_YEAR = TRUNC(ST.ETL_CRT_DT)
        AND ST.SALE_PLATFORM_NAME = MIN_DT.SALE_PLATFORM_NAME
        AND ST.YEAR = TO_CHAR(TRUNC(SYSDATE, 'YYYY'), 'YYYY')
    WHERE INDEX_TYPE = '收入'
    AND SALES_TARGET_TYPE = '挑战'
    GROUP BY    ST.CORPORATE_ENTITY_NAME_SN
                ,ST.PRODUCT_SORT1
                ,ST.PRODUCT_SORT2
                ,ST.PRODUCT_SORT3

    UNION ALL

    SELECT  ST.CORPORATE_ENTITY_NAME_SN
            ,ST.PRODUCT_SORT1
            ,ST.PRODUCT_SORT2
            ,ST.PRODUCT_SORT3
            ,0 AS SALE_TARGET_TON_GN_BEG
            ,0 AS SALE_TARGET_TON_HW_BEG
            ,SUM(CASE WHEN ST.SALE_PLATFORM_NAME = '国内销售平台' THEN ST.ANNUAL_TARGET_TON ELSE 0 END) AS SALE_TARGET_TON_GN_MID
            ,SUM(CASE WHEN ST.SALE_PLATFORM_NAME = '海外销售平台' THEN ST.ANNUAL_TARGET_TON ELSE 0 END) AS SALE_TARGET_TON_HW_MID
    FROM    MIN_DT
    LEFT JOIN   ODS_APD.ODS_APD_SALES_TARGET    ST
    ON  MIN_DT.MID_YEAR = TRUNC(ST.ETL_CRT_DT)
        AND ST.SALE_PLATFORM_NAME = MIN_DT.SALE_PLATFORM_NAME
        AND ST.YEAR = TO_CHAR(TRUNC(SYSDATE, 'YYYY'), 'YYYY')
    WHERE INDEX_TYPE = '收入'
    AND SALES_TARGET_TYPE = '挑战'
    GROUP BY    ST.CORPORATE_ENTITY_NAME_SN
                ,ST.PRODUCT_SORT1
                ,ST.PRODUCT_SORT2
                ,ST.PRODUCT_SORT3
)
SELECT  TRUNC(SYSDATE, 'YYYY')
        ,DCA.PRODUCE_COMPANY_NAME_SN
        ,DCA.PRODUCTION_LINE
        ,DCA.CAPACITY_TYPE
        ,max(DCA.WORKING_DAYS)
        ,max(DCA.MONTHLY_CAPACITY)
        ,max(DCA.MONTHLY_CAPACITY * 12)
        ,DCA.UNIT
        ,sum(TAR.SALE_TARGET_TON_GN_BEG)
        ,sum(TAR.SALE_TARGET_TON_HW_BEG)
        ,sum(TAR.SALE_TARGET_TON_GN_MID)
        ,sum(TAR.SALE_TARGET_TON_HW_MID)
        ,SYSDATE
        ,SYSDATE
FROM    (
    SELECT  DISTINCT
            PRODUCE_COMPANY_NAME_SN
            ,PRODUCTION_LINE
            ,CAPACITY_TYPE
            ,PRODUCT_SORT1
            ,PRODUCT_SORT2
            ,PRODUCT_SORT3
            ,WORKING_DAYS
            ,MONTHLY_CAPACITY
            ,UNIT
    FROM    MDDWS.DWS_CAPACITY_ALL
    WHERE   TRUNC(PERIOD, 'MM') = TRUNC(SYSDATE, 'YYYY')  --只取今年第一个月的数据（全部且唯一）
    AND PRODUCTION_LINE NOT IN ('金润德','泰国达美','越南对焊管件')
)                                       DCA
LEFT JOIN   TAR
ON  TAR.CORPORATE_ENTITY_NAME_SN = DCA.PRODUCE_COMPANY_NAME_SN
    AND TAR.PRODUCT_SORT1 = DCA.PRODUCT_SORT1
    AND TAR.PRODUCT_SORT2 = DCA.PRODUCT_SORT2
    AND TAR.PRODUCT_SORT3 = DCA.PRODUCT_SORT3
group by DCA.PRODUCE_COMPANY_NAME_SN
        ,DCA.PRODUCTION_LINE
        ,DCA.CAPACITY_TYPE
        ,DCA.UNIT

;
COMMIT;

END IF;
END;






