-- 创建表
CREATE TABLE DWS_CAPACITY_ALL (
    PERIOD DATE,
    PRODUCE_COMPANY_NAME_SN VARCHAR2(2000),
    PRODUCTION_LINE VARCHAR2(2000),
    CAPACITY_TYPE VARCHAR2(2000),
    WORKING_DAYS NUMBER,
    MONTHLY_CAPACITY NUMBER,
    UNIT VARCHAR2(2000),
    MIN_CAPACITY_RATE NUMBER,
    MIN_CAPACITY_T NUMBER,
    CAPACITY_RESPONSIBLE VARCHAR2(2000),
    PRODUCT_SORT1 VARCHAR2(2000),
    PRODUCT_SORT2 VARCHAR2(2000),
    PRODUCT_SORT3 VARCHAR2(2000),
    PRODUCT_SORT4 VARCHAR2(2000),
    ETL_CRT_DT DATE,
    ETL_UPD_DT DATE
);

COMMENT ON TABLE DWS_CAPACITY_ALL IS '产能总表（适用于产能负荷率报表）';


COMMENT ON COLUMN DWS_CAPACITY_ALL.PERIOD IS '日期';
COMMENT ON COLUMN DWS_CAPACITY_ALL.PRODUCE_COMPANY_NAME_SN IS '生产公司';
COMMENT ON COLUMN DWS_CAPACITY_ALL.PRODUCTION_LINE IS '生产线';
COMMENT ON COLUMN DWS_CAPACITY_ALL.CAPACITY_TYPE IS '产能类型';
COMMENT ON COLUMN DWS_CAPACITY_ALL.WORKING_DAYS IS '生产天数';
COMMENT ON COLUMN DWS_CAPACITY_ALL.MONTHLY_CAPACITY IS '月产能';
COMMENT ON COLUMN DWS_CAPACITY_ALL.UNIT IS '产能单位';
COMMENT ON COLUMN DWS_CAPACITY_ALL.MIN_CAPACITY_RATE IS '最低产能负荷率';
COMMENT ON COLUMN DWS_CAPACITY_ALL.MIN_CAPACITY_T IS '最低产能（吨）';
COMMENT ON COLUMN DWS_CAPACITY_ALL.CAPACITY_RESPONSIBLE IS '产能责任人';
COMMENT ON COLUMN DWS_CAPACITY_ALL.PRODUCT_SORT1 IS '产品大类';
COMMENT ON COLUMN DWS_CAPACITY_ALL.PRODUCT_SORT2 IS '产品中类';
COMMENT ON COLUMN DWS_CAPACITY_ALL.PRODUCT_SORT3 IS '产品小类';
COMMENT ON COLUMN DWS_CAPACITY_ALL.PRODUCT_SORT4 IS '品类';
COMMENT ON COLUMN DWS_CAPACITY_ALL.ETL_CRT_DT IS 'ETL创建日期';
COMMENT ON COLUMN DWS_CAPACITY_ALL.ETL_UPD_DT IS 'ETL更新日期';






SELECT 
       C.PERIOD_DATE
       ,A.PRODUCE_COMPANY_NAME_SN 
       ,A.PRODUCTION_LINE 
       ,A.CAPACITY_TYPE 
       ,B.WORKING_DAYS 
       ,B.MONTHLY_CAPACITY 
       ,B.UNIT 
       ,B.MIN_CAPACITY_RATE 
       ,B.MIN_CAPACITY_T 
       ,A.PRODUCT_SORT1 
       ,A.PRODUCT_SORT2 
       ,A.PRODUCT_SORT3 
       ,A.PRODUCT_SORT4 
       ,A.ETL_CRT_DT 
       ,A.ETL_UPD_DT 

FROM MDDWD.DWD_CNLXDZB A
LEFT JOIN MDDWD.DWD_CNJCB B ON  A.PRODUCTION_LINE=B.PRODUCTION_LINE AND A.CAPACITY_TYPE=B.CAPACITY_TYPE
CROSS JOIN MDDIM.DIM_MONTH_D C ON C.PERIOD_DATE > DATE '2023-12-1'AND C.PERIOD_DATE < SYSDATE