
---更新作业表问题行数、最后执行时间
UPDATE DWD_DATA_CHECK_JOB 
    SET ISSUE_LINE_COUNT = (
        SELECT  COUNT(1) FROM  DWD_R250425001_J01  A 
        WHERE CHECK_TIME =( SELECT MAX(CHECK_TIME) FROM  DWD_R250425001_J01 ) AND A.IS_HX='否'
        ) 
    ,JOB_LAST_RUN_TIME = SYSDATE
WHERE JOB_CODE = 'R250425001_J01'
;

UPDATE DWD_DATA_CHECK_JOB 
    SET ISSUE_LINE_COUNT = (
        SELECT  COUNT(1) FROM  DWD_R250425001_J02  A 
        WHERE CHECK_TIME =( SELECT MAX(CHECK_TIME) FROM  DWD_R250425001_J02 ) AND A.IS_HX='否'
        ) 
    ,JOB_LAST_RUN_TIME = SYSDATE
WHERE JOB_CODE = 'R250425001_J02'
;

UPDATE DWD_DATA_CHECK_JOB 
    SET ISSUE_LINE_COUNT = (
        SELECT  COUNT(1) FROM  DWD_R250425001_J03  A 
        WHERE CHECK_TIME =( SELECT MAX(CHECK_TIME) FROM  DWD_R250425001_J03 ) AND A.IS_HX='否'
        ) 
    ,JOB_LAST_RUN_TIME = SYSDATE
WHERE JOB_CODE = 'R250425001_J03'
;

UPDATE DWD_DATA_CHECK_JOB 
    SET ISSUE_LINE_COUNT = (
        SELECT  COUNT(1) FROM  DWD_R250425001_J04  A 
        WHERE CHECK_TIME =( SELECT MAX(CHECK_TIME) FROM  DWD_R250425001_J04 ) AND A.IS_HX='否'
        ) 
    ,  IS_LAST_EXC='是' 
    ,JOB_LAST_RUN_TIME = SYSDATE
WHERE JOB_CODE = 'R250425001_J04'
;

---更新规则表问题行数、最后执行时间
UPDATE DWD_DATA_CHECK_RULE 
    SET ISSUE_LINE_COUNT = (
        SELECT  SUM(ISSUE_LINE_COUNT) FROM  DWD_DATA_CHECK_JOB   A 
        WHERE   RULE_CODE = 'R250425001'
        ) 
，RULE_CHECK_LAST_TIME =  (
        SELECT  JOB_LAST_RUN_TIME FROM  DWD_DATA_CHECK_JOB   A 
        WHERE   IS_LAST_EXC = '是' AND RULE_CODE = 'R250425001'
        ) 
,RULE_ALERT = (
	SELECT 
	CASE
		WHEN SUM(ISSUE_LINE_COUNT) > 0 THEN 1
		ELSE 0
	END
	FROM DWD_DATA_CHECK_JOB   A 
	WHERE RULE_CODE = 'R250425001'
)
,ETL_UPD_DT = SYSDATE
WHERE RULE_CODE = 'R250425001'
;



DECLARE
    v_new_data_count NUMBER; 
BEGIN
    SELECT COUNT(1) INTO v_new_data_count 
    FROM DWD_R250412001_J01 
    WHERE IS_NEW_DATA = '是';  

    IF v_new_data_count = 0 THEN
        UPDATE DWD_DATA_CHECK_JOB 
        SET ISSUE_LINE_COUNT = 0,
        IS_LAST_EXC = '是',  
        JOB_LAST_RUN_TIME = SYSDATE
        WHERE JOB_CODE = 'R250412001_J01';
    ELSE
        UPDATE DWD_DATA_CHECK_JOB 
        SET ISSUE_LINE_COUNT = (
            SELECT COUNT(1) 
            FROM DWD_R250412001_J01 
            WHERE CHECK_TIME = (SELECT MAX(CHECK_TIME) FROM DWD_R250412001_J01) 
              AND IS_HX = '否'
        ),
        IS_LAST_EXC = '是',
        JOB_LAST_RUN_TIME = (SELECT MAX(CHECK_TIME) FROM DWD_R250412001_J01)
        WHERE JOB_CODE = 'R250412001_J01';
    END IF;

    UPDATE DWD_DATA_CHECK_RULE 
    SET ISSUE_LINE_COUNT = (
        SELECT SUM(ISSUE_LINE_COUNT) 
        FROM DWD_DATA_CHECK_JOB 
        WHERE RULE_CODE = 'R250412001'
    ),
    RULE_CHECK_LAST_TIME = (
        SELECT MAX(JOB_LAST_RUN_TIME) 
        FROM DWD_DATA_CHECK_JOB 
        WHERE IS_LAST_EXC = '是' 
          AND RULE_CODE = 'R250412001'
    )
    WHERE RULE_CODE = 'R250412001';
END;