select * from DIM_DAY_D order by period_code desc;

CREATE TABLE DIM_DAY_D_TMP202506 AS 
SELECT 
    PERIOD_WID,
    PERIOD_CODE,
    PERIOD_NAME,
    PERIOD_DATE,
    CASE 
        WHEN TO_CHAR(PERIOD_DATE, 'D') BETWEEN 2 AND 6 THEN 1  -- 周一到周五默认为工作日
        ELSE 0
    END AS IS_WORKDAY  -- 是否为工作日初始值
FROM DIM_DAY_D
WHERE PERIOD_WID > 20250600 
  AND PERIOD_WID < 20260000;





UPDATE DIM_DAY_D_TMP202506
SET IS_WORKDAY = CASE 
    WHEN TO_CHAR(PERIOD_DATE, 'D') = 7 AND  -- 周六（Oracle中周日=1，周六=7）
         MOD(TO_NUMBER(TO_CHAR(PERIOD_DATE, 'IW')), 2) = 1 -- 小周（使用ISO周）
         THEN 1  -- 小周周六上班
    WHEN TO_CHAR(PERIOD_DATE, 'D') = 7 AND  -- 周六
         MOD(TO_NUMBER(TO_CHAR(PERIOD_DATE, 'IW')), 2) = 0 -- 大周
         THEN 0  -- 大周周六休息
    ELSE IS_WORKDAY
END
WHERE TO_CHAR(PERIOD_DATE, 'D') = 7;  -- 只更新周六




UPDATE DIM_DAY_D_TMP202506
SET IS_WORKDAY = 0  -- 标记为休息日
WHERE PERIOD_DATE IN (
    DATE '2025-10-01', 
    DATE '2025-10-02',
    DATE '2025-10-03',
    DATE '2025-10-04',
    DATE '2025-10-05',
    DATE '2025-10-06',
    DATE '2025-10-07',
    DATE '2025-10-08'
);




ALTER TABLE DIM_DAY_D ADD IS_WORKDAY NUMBER(1) DEFAULT 1;

COMMENT ON COLUMN DIM_DAY_D.IS_WORKDAY IS '是否为工作日（1=是，0=否）';





-- 从临时表更新主表的工作日状态
UPDATE DIM_DAY_D d
SET d.IS_WORKDAY = (
    SELECT t.IS_WORKDAY 
    FROM DIM_DAY_D_TMP202506 t
    WHERE t.PERIOD_DATE = d.PERIOD_DATE
)
WHERE d.PERIOD_DATE IN (
    SELECT PERIOD_DATE 
    FROM DIM_DAY_D_TMP202506
);

