DELETE FROM  ADS_REGION_SALTGT_SUM;
INSERT INTO ADS_REGION_SALTGT_SUM
  (YPERIOD,
   PERIOD_TYPE,
   CUSTOMER_BG,
   PRODUCT_SORT_H,
   PRODUCT_SORT_M,
   ACTUAL_SALES_COMPANY,
   CUR_WGT_D_FACT,
   CUR_WGT_FACT,
   YOY_WGT_FACT,
   CUR_WGT_TGT,
   Y_WGT_TGT,
   CUR_AMT_D_FACT,
   CUR_AMT_FACT,
   YOY_AMT_FACT,
   CUR_AMT_TGT,
   Y_AMT_TGT,
   WEIGHT_Y_SAMEP,
   AMOUNT_Y_SAMEP,
   SALE_PLATFORM_NAME, --销售平台 2025-2-27邱治钧新增
   SALE_REGION_NAME, --销售大区 2025-2-27邱治钧新增
   ETL_CRT_DT,
   ETL_UPD_DT)
  SELECT YPERIOD,
        PERIOD_TYPE,
        CUSTOMER_BG,
        PRODUCT_SORT_H,
        PRODUCT_SORT_M,
        ACTUAL_SALES_COMPANY,
        SUM(CUR_WGT_D_FACT) CUR_WGT_D_FACT,
        SUM(CUR_WGT_FACT) CUR_WGT_FACT,
        SUM(YOY_WGT_FACT) YOY_WGT_FACT,
        SUM(CASE PERIOD_TYPE WHEN 'Y' THEN Y_WGT_TGT WHEN 'M'THEN CUR_WGT_TGT ELSE 0 END ) CUR_WGT_TGT, --当period_type = y 档期目标改为当年目标
        SUM(Y_WGT_TGT) Y_WGT_TGT,
        SUM(CUR_AMT_D_FACT) CUR_AMT_D_FACT,
        SUM(CUR_AMT_FACT) CUR_AMT_FACT,
        SUM(YOY_AMT_FACT) YOY_AMT_FACT,
        SUM(CASE PERIOD_TYPE WHEN 'Y' THEN Y_AMT_TGT WHEN 'M'THEN CUR_AMT_TGT ELSE 0 END ) CUR_AMT_TGT, --当period_type = y 档期目标改为当年目标
        SUM(Y_AMT_TGT) Y_AMT_TGT,
        SUM(WEIGHT_Y_SAMEP) WEIGHT_Y_SAMEP,
        SUM(AMOUNT_Y_SAMEP) AMOUNT_Y_SAMEP,
        SALE_PLATFORM_NAME, --销售平台 2025-2-27邱治钧新增
        SALE_REGION_NAME, --销售大区 2025-2-27邱治钧新增
        SYSDATE ETL_CRT_DT,
        SYSDATE ETL_UPD_DT
    FROM ADS_REGION_SALTGT
    WHERE SALE_REGION_NAME <> '回收物资销售'   -- 2025-04-02   回收物资销售不计入排名    修改人：常耀辉
		AND ACTUAL_SALES_COMPANY LIKE '%）%公司%'
   GROUP BY YPERIOD,
            PERIOD_TYPE,
            CUSTOMER_BG,
            PRODUCT_SORT_H,
            PRODUCT_SORT_M,
            ACTUAL_SALES_COMPANY      ,
            SALE_PLATFORM_NAME, --销售平台 2025-2-27邱治钧新增
            SALE_REGION_NAME --销售大区 2025-2-27邱治钧新增 ;