CREATE TABLE ADS_ORDER_PACKAGING_TABLE
(
  ORDER_NUM    VARCHAR2(2000),
  SONOSYS      NUMBER,
  FITEMNO      VARCHAR2(2000),
  SONO         VARCHAR2(2000),
  FHH          NVARCHAR2(2000),
  FJHXS        NUMBER,
  FJHSL        NUMBER,
  FMXJS        NUMBER,
  FMXXHS       NUMBER,
  FMXHJS       NUMBER,
  FMTXS        NUMBER,
  FMXTJ        NUMBER,
  FWXNO        VARCHAR2(2000),
  FWXSL        NUMBER,
  FWXTYPE      VARCHAR2(2000),
  FNHNO        VARCHAR2(2000),
  FNHSL        NUMBER,
  FNHTYPE      VARCHAR2(2000),
  FJTMNO       NVARCHAR2(2000),
  FNHTMNO      NVARCHAR2(2000),
  FWXTMNO      NVARCHAR2(2000),
  FTPTMNO      NVARCHAR2(2000),
  FJTMTYPE     VARCHAR2(2000),
  FJTMSL       NUMBER,
  FNHTMTYPE    VARCHAR2(2000),
  FNHTMSL      NUMBER,
  FWHTMNO      NVARCHAR2(2000),
  FWHTMTYPE    VARCHAR2(2000),
  FWHTMSL      NUMBER,
  FWXTMTYPE    VARCHAR2(2000),
  FWXTMSL      NUMBER,
  FTPTYPE      VARCHAR2(2000),
  FTPTMTYPE    VARCHAR2(2000),
  FTPTMSL      NUMBER,
  FDBQTYPE     VARCHAR2(2000),
  FDBQSL       NUMBER,
  FNHBQTYPE    VARCHAR2(2000),
  FNHBQSL      NUMBER,
  FWHBQTYPE    VARCHAR2(2000),
  FWHBQSL      NUMBER,
  FWXBQTYPE    VARCHAR2(2000),
  FWXBQSL      NUMBER,
  FJZMTYPE     VARCHAR2(2000),
  FJZMSL       NUMBER,
  FDZMTYPE     VARCHAR2(2000),
  FDZMSL       NUMBER,
  FJSLTYPE     VARCHAR2(2000),
  FJSLSL       NUMBER,
  FDSLTYPE     VARCHAR2(2000),
  FDSLSL       NUMBER,
  FSELFTMNO    NVARCHAR2(2000),
  FSELFTMTYPE  VARCHAR2(2000),
  FSELFTMNO1   NVARCHAR2(2000),
  FSELFTMTYPE1 VARCHAR2(2000),
  FSELFTMSL    NUMBER,
  FSELFTMSL1   NUMBER,
  FSELFBQNO    VARCHAR2(2000),
  FSELFBQTYPE  VARCHAR2(2000),
  FSELFBQNO1   VARCHAR2(2000),
  FSELFBQTYPE1 VARCHAR2(2000),
  FSELFBQSL    NUMBER,
  FSELFBQSL1   NUMBER,
  FTPSL        NUMBER,
  FNCTYPE      VARCHAR2(2000),
  NCLX         VARCHAR2(2000),
  NCSL         NUMBER,
  FHH1         NVARCHAR2(2000),
  UT           VARCHAR2(2000),
  SLMLX        VARCHAR2(2000),
  SLMSL        NUMBER,
  CZFL         VARCHAR2(2000),
  BMCL         VARCHAR2(2000),
  SCGY         VARCHAR2(2000),
  SCX          VARCHAR2(2000),
  FFDLX        VARCHAR2(2000),
  FFDSL        NUMBER,
  FMPLX        VARCHAR2(2000),
  FMPSL        NUMBER,
  FULMPLX      VARCHAR2(2000),
  FULMPSL      NUMBER,
  FZDYMPLX     VARCHAR2(2000),
  FZDYMPSL     NUMBER,
  FDPLX        VARCHAR2(2000),
  FDPSL        NUMBER,
  FHGZLX       VARCHAR2(2000),
  FHGZSL       NUMBER,
  FCPAZLX      VARCHAR2(2000),
  FCPAZSL      NUMBER,
  FGCLX        VARCHAR2(2000),
  FGCSL        NUMBER,
  SDLX         VARCHAR2(2000),
  SDSL         NUMBER,
  DBDLX        VARCHAR2(2000),
  DBDSL        NUMBER,
  FSBLX        VARCHAR2(2000),
  FSBSL        NUMBER,
  DZDLX        VARCHAR2(2000),
  DZDSL        NUMBER,
  KBQLX        VARCHAR2(2000),
  KBQSL        NUMBER,
  ZTMH         VARCHAR2(2000),
  ZTBLX        VARCHAR2(2000),
  ZTMSL        NUMBER,
  KTMH         VARCHAR2(2000),
  KTMLX        VARCHAR2(2000),
  KTMSL        NUMBER,
  WXGGXH       VARCHAR2(2000),
  TPGGXH       VARCHAR2(2000),
  WHTMH        VARCHAR2(2000),
  DTMH         VARCHAR2(2000),
  IMSBZMXID    NUMBER,
  IMSMXID      NUMBER,
  IMSDTID      NUMBER,
  XDBQSL       NUMBER,
  CPMS1        VARCHAR2(2000),
  CPMS2        VARCHAR2(2000),
  CPMS3        VARCHAR2(2000),
  CPMS4        VARCHAR2(2000),
  CPMS5        VARCHAR2(2000),
  CPMS6        VARCHAR2(2000),
  CPMS7        VARCHAR2(2000),
  CPMS8        VARCHAR2(2000),
  ETL_CRT_DT   DATE DEFAULT SYSDATE,
  ETL_UPD_DT   DATE DEFAULT SYSDATE  -- ETL更新日期
)
;
-- ADD COMMENTS TO THE TABLE 
COMMENT ON TABLE ODS_SODTL5
  IS '包装参数表';
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN ODS_SODTL5.SONOSYS
  IS '标识列';
COMMENT ON COLUMN ODS_SODTL5.FITEMNO
  IS '产品名称';
COMMENT ON COLUMN ODS_SODTL5.SONO
  IS '合同号';
COMMENT ON COLUMN ODS_SODTL5.FHH
  IS '货号';
COMMENT ON COLUMN ODS_SODTL5.FJHXS
  IS '计划箱数';
COMMENT ON COLUMN ODS_SODTL5.FJHSL
  IS '计划件数';
COMMENT ON COLUMN ODS_SODTL5.FMXJS
  IS '每箱件数';
COMMENT ON COLUMN ODS_SODTL5.FMXXHS
  IS '每箱小盒数';
COMMENT ON COLUMN ODS_SODTL5.FMXHJS
  IS '每小盒件数';
COMMENT ON COLUMN ODS_SODTL5.FMTXS
  IS '每托箱数';
COMMENT ON COLUMN ODS_SODTL5.FMXTJ
  IS '每箱体积';
COMMENT ON COLUMN ODS_SODTL5.FWXNO
  IS '外箱标号';
COMMENT ON COLUMN ODS_SODTL5.FWXSL
  IS '外箱数量';
COMMENT ON COLUMN ODS_SODTL5.FWXTYPE
  IS '外箱说明';
COMMENT ON COLUMN ODS_SODTL5.FNHNO
  IS '内盒标号';
COMMENT ON COLUMN ODS_SODTL5.FNHSL
  IS '内盒数量';
COMMENT ON COLUMN ODS_SODTL5.FNHTYPE
  IS '内盒说明';
COMMENT ON COLUMN ODS_SODTL5.FJTMNO
  IS '件条码编号';
COMMENT ON COLUMN ODS_SODTL5.FNHTMNO
  IS '内盒码编号';
COMMENT ON COLUMN ODS_SODTL5.FWXTMNO
  IS '外箱码编号';
COMMENT ON COLUMN ODS_SODTL5.FTPTMNO
  IS '托盘条码编号';
COMMENT ON COLUMN ODS_SODTL5.FJTMTYPE
  IS '件条码类型';
COMMENT ON COLUMN ODS_SODTL5.FJTMSL
  IS '件条码数量';
COMMENT ON COLUMN ODS_SODTL5.FNHTMTYPE
  IS '内盒码类型';
COMMENT ON COLUMN ODS_SODTL5.FNHTMSL
  IS '内盒码数量';
COMMENT ON COLUMN ODS_SODTL5.FWHTMNO
  IS 'FWHTMNO';
COMMENT ON COLUMN ODS_SODTL5.FWHTMTYPE
  IS '外盒码类型';
COMMENT ON COLUMN ODS_SODTL5.FWHTMSL
  IS '外盒码数量';
COMMENT ON COLUMN ODS_SODTL5.FWXTMTYPE
  IS '外箱码类型';
COMMENT ON COLUMN ODS_SODTL5.FWXTMSL
  IS '外箱码数量';
COMMENT ON COLUMN ODS_SODTL5.FTPTYPE
  IS '托盘类型';
COMMENT ON COLUMN ODS_SODTL5.FTPTMTYPE
  IS '托盘码类型';
COMMENT ON COLUMN ODS_SODTL5.FTPTMSL
  IS '托盘码数量';
COMMENT ON COLUMN ODS_SODTL5.FDBQTYPE
  IS '袋标签类型';
COMMENT ON COLUMN ODS_SODTL5.FDBQSL
  IS '袋标签数量';
COMMENT ON COLUMN ODS_SODTL5.FNHBQTYPE
  IS '内盒签类型';
COMMENT ON COLUMN ODS_SODTL5.FNHBQSL
  IS '内盒签数量';
COMMENT ON COLUMN ODS_SODTL5.FWHBQTYPE
  IS '外盒签类型';
COMMENT ON COLUMN ODS_SODTL5.FWHBQSL
  IS '外盒签数量';
COMMENT ON COLUMN ODS_SODTL5.FWXBQTYPE
  IS '外箱签类型';
COMMENT ON COLUMN ODS_SODTL5.FWXBQSL
  IS '外箱签数量';
COMMENT ON COLUMN ODS_SODTL5.FJZMTYPE
  IS '件子母类型';
COMMENT ON COLUMN ODS_SODTL5.FJZMSL
  IS '件子母数量';
COMMENT ON COLUMN ODS_SODTL5.FDZMTYPE
  IS '袋子母类型';
COMMENT ON COLUMN ODS_SODTL5.FDZMSL
  IS '袋子母数量';
COMMENT ON COLUMN ODS_SODTL5.FJSLTYPE
  IS '件塑料类型';
COMMENT ON COLUMN ODS_SODTL5.FJSLSL
  IS '件塑料数量';
COMMENT ON COLUMN ODS_SODTL5.FDSLTYPE
  IS '袋塑料类型';
COMMENT ON COLUMN ODS_SODTL5.FDSLSL
  IS '袋塑料数量';
COMMENT ON COLUMN ODS_SODTL5.FSELFTMNO
  IS '自条码号';
COMMENT ON COLUMN ODS_SODTL5.FSELFTMTYPE
  IS '自条码类型';
COMMENT ON COLUMN ODS_SODTL5.FSELFTMNO1
  IS '自条码号1';
COMMENT ON COLUMN ODS_SODTL5.FSELFTMTYPE1
  IS '自码类型1';
COMMENT ON COLUMN ODS_SODTL5.FSELFTMSL
  IS '自条码数量';
COMMENT ON COLUMN ODS_SODTL5.FSELFTMSL1
  IS '自码数量1';
COMMENT ON COLUMN ODS_SODTL5.FSELFBQNO
  IS '自标签号';
COMMENT ON COLUMN ODS_SODTL5.FSELFBQTYPE
  IS '自标签类型';
COMMENT ON COLUMN ODS_SODTL5.FSELFBQNO1
  IS '自标签号1';
COMMENT ON COLUMN ODS_SODTL5.FSELFBQTYPE1
  IS '自签类型1';
COMMENT ON COLUMN ODS_SODTL5.FSELFBQSL
  IS '自标签数量';
COMMENT ON COLUMN ODS_SODTL5.FSELFBQSL1
  IS '自标签数量1';
COMMENT ON COLUMN ODS_SODTL5.FTPSL
  IS '托盘数量';
COMMENT ON COLUMN ODS_SODTL5.FNCTYPE
  IS '内衬类型';
COMMENT ON COLUMN ODS_SODTL5.NCLX
  IS '内衬类型';
COMMENT ON COLUMN ODS_SODTL5.NCSL
  IS '内衬数量';
COMMENT ON COLUMN ODS_SODTL5.FHH1
  IS '货号1';
COMMENT ON COLUMN ODS_SODTL5.UT
  IS '数量单元';
COMMENT ON COLUMN ODS_SODTL5.FFDLX
  IS '封堵类型';
COMMENT ON COLUMN ODS_SODTL5.FFDSL
  IS '封堵数量';
COMMENT ON COLUMN ODS_SODTL5.FMPLX
  IS '铭牌类型';
COMMENT ON COLUMN ODS_SODTL5.FMPSL
  IS '铭牌数量';
COMMENT ON COLUMN ODS_SODTL5.FULMPLX
  IS 'UL序列号铭牌';
COMMENT ON COLUMN ODS_SODTL5.FULMPSL
  IS 'UL序列号铭牌数量';
COMMENT ON COLUMN ODS_SODTL5.FZDYMPLX
  IS '自定义铭牌';
COMMENT ON COLUMN ODS_SODTL5.FZDYMPSL
  IS '自定义铭牌数量';
COMMENT ON COLUMN ODS_SODTL5.FDPLX
  IS '吊牌类型';
COMMENT ON COLUMN ODS_SODTL5.FDPSL
  IS '吊牌数量';
COMMENT ON COLUMN ODS_SODTL5.FHGZLX
  IS '合格证类型';
COMMENT ON COLUMN ODS_SODTL5.FHGZSL
  IS '合格证数量';
COMMENT ON COLUMN ODS_SODTL5.FCPAZLX
  IS '产品安装指南';
COMMENT ON COLUMN ODS_SODTL5.FCPAZSL
  IS '产品安装指南数量';
COMMENT ON COLUMN ODS_SODTL5.FGCLX
  IS '隔层类型';
COMMENT ON COLUMN ODS_SODTL5.FGCSL
  IS '隔层数量';
COMMENT ON COLUMN ODS_SODTL5.ETL_CRT_DT
  IS 'ETL创建日期';
COMMENT ON COLUMN ODS_SODTL5.ETL_UPD_DT
  IS 'ETL更新日期';
