INSERT INTO DWD_WEIGHT_PIECE_BIKB (
    KBID,
    PERIOD,
    GROUP_ID,
    ORDER_ID,
    PRODUCT_VARIETY,
    PRODUCT_FORM,
    PRODUCT_SPECIFICATION,
    PRODUCT_TEXTURE,
    SURFACE_TREATMENT,
    PROCESS_STEP,
    UPDATE_TIME,
    CNT,
    UNIT_WEIGHT
)
SELECT 
    KBID,
    TO_DATE(A.RQ,'MM.YY.DD') AS PERIOD,
    A.ZH AS GROUP_ID,
    A.DDH AS ORDER_ID,
    A.PZ AS PRODUCT_VARIETY,
    A.GG AS PRODUCT_FORM,
    A.XS AS PRODUCT_SPECIFICATION,
    A.CZFL AS PRODUCT_TEXTURE,
    A.BMCL AS SURFACE_TREATMENT,
    A.GB AS PROCESS_STEP,
    MAX(A.GXSJ) AS UPDATE_TIME,
    JS AS CNT,
    B.NWGT AS UNIT_WEIGHT
FROM ODS_FMZPMXB A
LEFT JOIN ODS_ERP.ODS_INVITEM B
    ON A.PZ = B.TYPE2
    AND A.GG = B.TYPE3
    AND A.XS = B.TYPE4
    AND A.CZFL = B.CZFL
    AND A.BMCL = B.BMCL
WHERE A.GB IN ('成套','质检')
GROUP BY 
    KBID,
    A.ZH,
    A.DDH,
    A.PZ,
    A.GG,
    A.XS,
    A.CZFL,
    A.BMCL,
    A.GB,
    JS,
    NWGT;