CREATE TABLE DWD_DELIVERY_BIKB
(
  DELIVERY_LINE_ID NUMBER,
  ORDER_ID NUMBER,
  ORDER_NUM VARCHAR2(2000),
  DELIVERY_DATE DATE,
  PLAN_SHIP_DATE DATE,
  LATEST_DELIVERY_DATE DATE,
  ATTRIBUTE4 VARCHAR2(2000),
  ETL_CRT_DT DATE DEFAULT SYSDATE,
  ETL_UPD_DT DATE DEFAULT SYSDATE
);


INSERT INTO DWD_DELIVERY_BIKB (
  DELIVERY_LINE_ID,
  ORDER_ID,
  ORDER_NUM,
  DELIVERY_DATE,
  PLAN_SHIP_DATE,
  LATEST_DELIVERY_DATE,
  ATTRIBUTE4,
  ETL_CRT_DT,
  ETL_UPD_DT
)
SELECT 
  a.DELIVERY_LINE_ID,
  a.DELIVERY_STATUS,
  c.order_id,
  c.ORDER_NUM,
  c.delivery_date,
  D.Plan_Ship_Date,
  D.Latest_Delivery_Date,
  t.ATTRIBUTE4,
  SYSDATE,
  SYSDATE
FROM ods_CRM_LG_DELIVERY_PLAN T
LEFT JOIN ods_ims.CRM_LG_DELIVERY_HEADER A ON t.DELIVERY_HEAD_ID = a.DELIVERY_HEAD_ID
LEFT JOIN ods_ims.CRM_LG_DELIVERY_LINE B ON A.DELIVERY_HEAD_ID = B.DELIVERY_HEAD_ID
LEFT JOIN ods_ims.CRM_SO_ORDER_HEADER C ON C.ORDER_ID = B.ORDER_ID
LEFT JOIN ods_ims.ods_CRM_LG_DELIVERY_BOOKING D ON D.DELIVERY_HEAD_ID = A.DELIVERY_HEAD_ID;