WITH SUM_CNT AS (
        SELECT TH ,COUNT(*) AS CNT,SUM(JE)AS TOTAL_AMOUNT FROM ODS_FM_YHJHB WHERE TO_DATE(JYRQ,'YY.MM.DD')>=TRUNC(SYSDATE-1,'MM') AND HGL<1 AND (DW IN ('止回阀装配线','蝶阀装配线') )
        GROUP BY TH
)
SELECT TH--生产线号
       ,CNT--次数
       ,TOTAL_AMOUNT--金额
       ,DENSE_RANK() OVER(ORDER BY CNT DESC,TOTAL_AMOUNT DESC) RK--排名
       
   FROM SUM_CNT WHERE TH IS NOT NULL




-- 创建表语句
CREATE TABLE DWS_COUNT_GROUP_RANK (
    TH VARCHAR2(2000),          -- 生产线号
    CNT NUMBER,                 -- 次数
    TOTAL_AMOUNT NUMBER,        -- 金额
    RK NUMBER,                  -- 排名
    ETL_CRT_DT DATE DEFAULT SYSDATE,
    ETL_UPD_DT DATE DEFAULT SYSDATE
);

-- 添加表注释
COMMENT ON TABLE DWS_COUNT_GROUP_RANK IS '生产线号统计排名表';

-- 添加列注释
COMMENT ON COLUMN DWS_COUNT_GROUP_RANK.TH IS '生产线号';
COMMENT ON COLUMN DWS_COUNT_GROUP_RANK.CNT IS '次数';
COMMENT ON COLUMN DWS_COUNT_GROUP_RANK.TOTAL_AMOUNT IS '金额';
COMMENT ON COLUMN DWS_COUNT_GROUP_RANK.RK IS '排名';
COMMENT ON COLUMN DWS_COUNT_GROUP_RANK.ETL_CRT_DT IS 'ETL创建日期';
COMMENT ON COLUMN DWS_COUNT_GROUP_RANK.ETL_UPD_DT IS 'ETL更新日期';



INSERT INTO DWS_COUNT_GROUP_RANK (TH, CNT, TOTAL_AMOUNT, RK)
WITH SUM_CNT AS (
    SELECT TH, COUNT(*) AS CNT, SUM(JE) AS TOTAL_AMOUNT 
    FROM ODS_FM_YHJHB 
    WHERE TO_DATE(JYRQ,'YY.MM.DD') >= TRUNC(SYSDATE-1,'MM') 
      AND HGL < 1 
      AND (DW IN ('止回阀装配线','蝶阀装配线'))
    GROUP BY TH
)
SELECT TH,                 -- 生产线号
       CNT,                -- 次数
       TOTAL_AMOUNT,       -- 金额
       DENSE_RANK() OVER(ORDER BY CNT DESC, TOTAL_AMOUNT DESC) RK  -- 排名
FROM SUM_CNT 
WHERE TH IS NOT NULL;

COMMIT;