CREATE TABLE ODS_CRM_LG_DELIVERY_PLAN
(
  DPL_ID NUMBER,
  ORG_ID NUMBER,
  DELIVERY_HEAD_ID NUMBER,
  DELIVERY_CODE VARCHAR2(2000),
  PALLETS_ID NUMBER,
  CONTAINER_QTY NUMBER,
  DEPARTURE_DATE DATE,
  REMARK VARCHAR2(2000),
  CREATED_BY NUMBER,
  CREATION_DATE DATE,
  LAST_UPDATED_BY NUMBER,
  LAST_UPDATE_DATE DATE,
  ATTRIBUTE1 VARCHAR2(2000),
  ATTRIBUTE2 VARCHAR2(2000),
  ATTRIBUTE3 VARCHAR2(2000),
  ATTRIBUTE4 VARCHAR2(2000),
  ATTRIBUTE5 VARCHAR2(2000),
  ATTRIBUTE6 VARCHAR2(2000),
  ATTRIBUTE7 VARCHAR2(2000),
  ATTRIBUTE8 VARCHAR2(2000),
  ATTRIBUTE9 VARCHAR2(2000),
  ATTRIBUTE10 VARCHAR2(2000),
  WAREHOUSE_FACTORY_TRAY VARCHAR2(2000),
  ETL_CRT_DT DATE DEFAULT SYSDATE,
  ETL_UPD_DT DATE DEFAULT SYSDATE
);


COMMENT ON COLUMN ODS_CRM_LG_DELIVERY_PLAN.DPL_ID IS '配送计划ID';
COMMENT ON COLUMN ODS_CRM_LG_DELIVERY_PLAN.ORG_ID IS '组织ID';
COMMENT ON COLUMN ODS_CRM_LG_DELIVERY_PLAN.DELIVERY_HEAD_ID IS '配送单头ID';
COMMENT ON COLUMN ODS_CRM_LG_DELIVERY_PLAN.DELIVERY_CODE IS '配送单号';
COMMENT ON COLUMN ODS_CRM_LG_DELIVERY_PLAN.PALLETS_ID IS '托盘ID';
COMMENT ON COLUMN ODS_CRM_LG_DELIVERY_PLAN.CONTAINER_QTY IS '容器数量';
COMMENT ON COLUMN ODS_CRM_LG_DELIVERY_PLAN.DEPARTURE_DATE IS '出发日期';
COMMENT ON COLUMN ODS_CRM_LG_DELIVERY_PLAN.REMARK IS '备注';
COMMENT ON COLUMN ODS_CRM_LG_DELIVERY_PLAN.CREATED_BY IS '创建人';
COMMENT ON COLUMN ODS_CRM_LG_DELIVERY_PLAN.CREATION_DATE IS '创建日期';
COMMENT ON COLUMN ODS_CRM_LG_DELIVERY_PLAN.LAST_UPDATED_BY IS '最后更新人';
COMMENT ON COLUMN ODS_CRM_LG_DELIVERY_PLAN.LAST_UPDATE_DATE IS '最后更新日期';
COMMENT ON COLUMN ODS_CRM_LG_DELIVERY_PLAN.ATTRIBUTE1 IS '属性1';
COMMENT ON COLUMN ODS_CRM_LG_DELIVERY_PLAN.ATTRIBUTE2 IS '属性2';
COMMENT ON COLUMN ODS_CRM_LG_DELIVERY_PLAN.ATTRIBUTE3 IS '属性3';
COMMENT ON COLUMN ODS_CRM_LG_DELIVERY_PLAN.ATTRIBUTE4 IS '属性4';
COMMENT ON COLUMN ODS_CRM_LG_DELIVERY_PLAN.ATTRIBUTE5 IS '属性5';
COMMENT ON COLUMN ODS_CRM_LG_DELIVERY_PLAN.ATTRIBUTE6 IS '属性6';
COMMENT ON COLUMN ODS_CRM_LG_DELIVERY_PLAN.ATTRIBUTE7 IS '属性7';
COMMENT ON COLUMN ODS_CRM_LG_DELIVERY_PLAN.ATTRIBUTE8 IS '属性8';
COMMENT ON COLUMN ODS_CRM_LG_DELIVERY_PLAN.ATTRIBUTE9 IS '属性9';
COMMENT ON COLUMN ODS_CRM_LG_DELIVERY_PLAN.ATTRIBUTE10 IS '属性10';
COMMENT ON COLUMN ODS_CRM_LG_DELIVERY_PLAN.WAREHOUSE_FACTORY_TRAY IS '仓库工厂托盘';
COMMENT ON COLUMN ODS_CRM_LG_DELIVERY_PLAN.ETL_CRT_DT IS 'ETL创建日期';
COMMENT ON COLUMN ODS_CRM_LG_DELIVERY_PLAN.ETL_UPD_DT IS 'ETL更新日期';