CREATE TABLE ODS_SODTL5 (
    SONOSYS NUMBER,  -- 标识列
    FITEMNO VARCHAR2(2000),  -- 产品名称
    SONO VARCHAR2(2000),  -- 合同号
    FHH NVARCHAR2(2000),  -- 货号
    FJHXS NUMBER,  -- 计划箱数
    FJHSL NUMBER,  -- 计划件数
    FMXJS NUMBER,  -- 每箱件数
    FMXXHS NUMBER,  -- 每箱小盒数
    FMXHJS NUMBER,  -- 每小盒件数
    FMTXS NUMBER,  -- 每托箱数
    FMXTJ NUMBER,  -- 每箱体积
    FWXNO VARCHAR2(2000),  -- 外箱标号
    FWXSL NUMBER,  -- 外箱数量
    FWXTYPE VARCHAR2(2000),  -- 外箱说明
    FNHNO VARCHAR2(2000),  -- 内盒标号
    FNHSL NUMBER,  -- 内盒数量
    FNHTYPE VARCHAR2(2000),  -- 内盒说明
    FJTMNO NVARCHAR2(2000),  -- 件条码编号
    FNHTMNO NVARCHAR2(2000),  -- 内盒码编号
    FWXTMNO NVARCHAR2(2000),  -- 外箱码编号
    FTPTMNO NVARCHAR2(2000),  -- 托盘条码编号
    FJTMTYPE VARCHAR2(2000),  -- 件条码类型
    FJTMSL NUMBER,  -- 件条码数量
    FNHTMTYPE VARCHAR2(2000),  -- 内盒码类型
    FNHTMSL NUMBER,  -- 内盒码数量
    FWHTMNO NVARCHAR2(2000),  -- FWHTMNo
    FWHTMTYPE VARCHAR2(2000),  -- 外盒码类型
    FWHTMSL NUMBER,  -- 外盒码数量
    FWXTMTYPE VARCHAR2(2000),  -- 外箱码类型
    FWXTMSL NUMBER,  -- 外箱码数量
    FTPTYPE VARCHAR2(2000),  -- 托盘类型
    FTPTMTYPE VARCHAR2(2000),  -- 托盘码类型
    FTPTMSL NUMBER,  -- 托盘码数量
    FDBQTYPE VARCHAR2(2000),  -- 袋标签类型
    FDBQSL NUMBER,  -- 袋标签数量
    FNHBQTYPE VARCHAR2(2000),  -- 内盒签类型
    FNHBQSL NUMBER,  -- 内盒签数量
    FWHBQTYPE VARCHAR2(2000),  -- 外盒签类型
    FWHBQSL NUMBER,  -- 外盒签数量
    FWXBQTYPE VARCHAR2(2000),  -- 外箱签类型
    FWXBQSL NUMBER,  -- 外箱签数量
    FJZMTYPE VARCHAR2(2000),  -- 件子母类型
    FJZMSL NUMBER,  -- 件子母数量
    FDZMTYPE VARCHAR2(2000),  -- 袋子母类型
    FDZMSL NUMBER,  -- 袋子母数量
    FJSLTYPE VARCHAR2(2000),  -- 件塑料类型
    FJSLSL NUMBER,  -- 件塑料数量
    FDSLTYPE VARCHAR2(2000),  -- 袋塑料类型
    FDSLSL NUMBER,  -- 袋塑料数量
    FSELFTMNO NVARCHAR2(2000),  -- 自条码号
    FSELFTMTYPE VARCHAR2(2000),  -- 自条码类型
    FSELFTMNO1 NVARCHAR2(2000),  -- 自条码号1
    FSELFTMTYPE1 VARCHAR2(2000),  -- 自码类型1
    FSELFTMSL NUMBER,  -- 自条码数量
    FSELFTMSL1 NUMBER,  -- 自码数量1
    FSELFBQNO VARCHAR2(2000),  -- 自标签号
    FSELFBQTYPE VARCHAR2(2000),  -- 自标签类型
    FSELFBQNO1 VARCHAR2(2000),  -- 自标签号1
    FSELFBQTYPE1 VARCHAR2(2000),  -- 自签类型1
    FSELFBQSL NUMBER,  -- 自标签数量
    FSELFBQSL1 NUMBER,  -- 自标签数量1
    FTPSL NUMBER,  -- 托盘数量
    FNCTYPE VARCHAR2(2000),  -- 内衬类型
    NCLX VARCHAR2(2000),  -- 内衬类型
    NCSL NUMBER,  -- 内衬数量
    FHH1 NVARCHAR2(2000),  -- 货号1
    UT VARCHAR2(2000),  -- 数量单元
    SLMLX VARCHAR2(2000),  -- 
    SLMSL NUMBER,  -- 
    CZFL VARCHAR2(2000),  -- 
    BMCL VARCHAR2(2000),  -- 
    SCGY VARCHAR2(2000),  -- 
    SCX VARCHAR2(2000),  -- 
    FFDLX VARCHAR2(2000),  -- 封堵类型
    FFDSL NUMBER,  -- 封堵数量
    FMPLX VARCHAR2(2000),  -- 铭牌类型
    FMPSL NUMBER,  -- 铭牌数量
    FULMPLX VARCHAR2(2000),  -- UL序列号铭牌
    FULMPSL NUMBER,  -- UL序列号铭牌数量
    FZDYMPLX VARCHAR2(2000),  -- 自定义铭牌
    FZDYMPSL NUMBER,  -- 自定义铭牌数量
    FDPLX VARCHAR2(2000),  -- 吊牌类型
    FDPSL NUMBER,  -- 吊牌数量
    FHGZLX VARCHAR2(2000),  -- 合格证类型
    FHGZSL NUMBER,  -- 合格证数量
    FCPAZLX VARCHAR2(2000),  -- 产品安装指南
    FCPAZSL NUMBER,  -- 产品安装指南数量
    FGCLX VARCHAR2(2000),  -- 隔层类型
    FGCSL NUMBER,  -- 隔层数量
    SDLX VARCHAR2(2000),  -- 
    SDSL NUMBER,  -- 
    DBDLX VARCHAR2(2000),  -- 
    DBDSL NUMBER,  -- 
    FSBLX VARCHAR2(2000),  -- 
    FSBSL NUMBER,  -- 
    DZDLX VARCHAR2(2000),  -- 
    DZDSL NUMBER,  -- 
    KBQLX VARCHAR2(2000),  -- 
    KBQSL NUMBER,  -- 
    ZTMH VARCHAR2(2000),  -- 
    ZTBLX VARCHAR2(2000),  -- 
    ZTMSL NUMBER,  -- 
    KTMH VARCHAR2(2000),  -- 
    KTMLX VARCHAR2(2000),  -- 
    KTMSL NUMBER,  -- 
    WXGGXH VARCHAR2(2000),  -- 
    TPGGXH VARCHAR2(2000),  -- 
    WHTMH VARCHAR2(2000),  -- 
    DTMH VARCHAR2(2000),  -- 
    IMSBZMXID NUMBER,  -- 
    IMSMXID NUMBER,  -- 
    IMSDTID NUMBER,  -- 
    XDBQSL NUMBER,  -- 
    CPMS1 VARCHAR2(2000),  -- 
    CPMS2 VARCHAR2(2000),  -- 
    CPMS3 VARCHAR2(2000),  -- 
    CPMS4 VARCHAR2(2000),  -- 
    CPMS5 VARCHAR2(2000),  -- 
    CPMS6 VARCHAR2(2000),  -- 
    CPMS7 VARCHAR2(2000),  -- 
    CPMS8 VARCHAR2(2000),  -- 
    ETL_CRT_DT DATE DEFAULT SYSDATE,  -- ETL创建日期
    ETL_UPD_DT DATE DEFAULT SYSDATE  -- ETL更新日期
);

-- 添加表注释
COMMENT ON TABLE ODS_SODTL5 IS '包装参数表';

-- 添加列注释
COMMENT ON COLUMN ODS_SODTL5.SONOSYS IS '标识列';
COMMENT ON COLUMN ODS_SODTL5.FITEMNO IS '产品名称';
COMMENT ON COLUMN ODS_SODTL5.SONO IS '合同号';
COMMENT ON COLUMN ODS_SODTL5.FHH IS '货号';
COMMENT ON COLUMN ODS_SODTL5.FJHXS IS '计划箱数';
COMMENT ON COLUMN ODS_SODTL5.FJHSL IS '计划件数';
COMMENT ON COLUMN ODS_SODTL5.FMXJS IS '每箱件数';
COMMENT ON COLUMN ODS_SODTL5.FMXXHS IS '每箱小盒数';
COMMENT ON COLUMN ODS_SODTL5.FMXHJS IS '每小盒件数';
COMMENT ON COLUMN ODS_SODTL5.FMTXS IS '每托箱数';
COMMENT ON COLUMN ODS_SODTL5.FMXTJ IS '每箱体积';
COMMENT ON COLUMN ODS_SODTL5.FWXNO IS '外箱标号';
COMMENT ON COLUMN ODS_SODTL5.FWXSL IS '外箱数量';
COMMENT ON COLUMN ODS_SODTL5.FWXTYPE IS '外箱说明';
COMMENT ON COLUMN ODS_SODTL5.FNHNO IS '内盒标号';
COMMENT ON COLUMN ODS_SODTL5.FNHSL IS '内盒数量';
COMMENT ON COLUMN ODS_SODTL5.FNHTYPE IS '内盒说明';
COMMENT ON COLUMN ODS_SODTL5.FJTMNO IS '件条码编号';
COMMENT ON COLUMN ODS_SODTL5.FNHTMNO IS '内盒码编号';
COMMENT ON COLUMN ODS_SODTL5.FWXTMNO IS '外箱码编号';
COMMENT ON COLUMN ODS_SODTL5.FTPTMNO IS '托盘条码编号';
COMMENT ON COLUMN ODS_SODTL5.FJTMTYPE IS '件条码类型';
COMMENT ON COLUMN ODS_SODTL5.FJTMSL IS '件条码数量';
COMMENT ON COLUMN ODS_SODTL5.FNHTMTYPE IS '内盒码类型';
COMMENT ON COLUMN ODS_SODTL5.FNHTMSL IS '内盒码数量';
COMMENT ON COLUMN ODS_SODTL5.FWHTMNO IS 'FWHTMNo';
COMMENT ON COLUMN ODS_SODTL5.FWHTMTYPE IS '外盒码类型';
COMMENT ON COLUMN ODS_SODTL5.FWHTMSL IS '外盒码数量';
COMMENT ON COLUMN ODS_SODTL5.FWXTMTYPE IS '外箱码类型';
COMMENT ON COLUMN ODS_SODTL5.FWXTMSL IS '外箱码数量';
COMMENT ON COLUMN ODS_SODTL5.FTPTYPE IS '托盘类型';
COMMENT ON COLUMN ODS_SODTL5.FTPTMTYPE IS '托盘码类型';
COMMENT ON COLUMN ODS_SODTL5.FTPTMSL IS '托盘码数量';
COMMENT ON COLUMN ODS_SODTL5.FDBQTYPE IS '袋标签类型';
COMMENT ON COLUMN ODS_SODTL5.FDBQSL IS '袋标签数量';
COMMENT ON COLUMN ODS_SODTL5.FNHBQTYPE IS '内盒签类型';
COMMENT ON COLUMN ODS_SODTL5.FNHBQSL IS '内盒签数量';
COMMENT ON COLUMN ODS_SODTL5.FWHBQTYPE IS '外盒签类型';
COMMENT ON COLUMN ODS_SODTL5.FWHBQSL IS '外盒签数量';
COMMENT ON COLUMN ODS_SODTL5.FWXBQTYPE IS '外箱签类型';
COMMENT ON COLUMN ODS_SODTL5.FWXBQSL IS '外箱签数量';
COMMENT ON COLUMN ODS_SODTL5.FJZMTYPE IS '件子母类型';
COMMENT ON COLUMN ODS_SODTL5.FJZMSL IS '件子母数量';
COMMENT ON COLUMN ODS_SODTL5.FDZMTYPE IS '袋子母类型';
COMMENT ON COLUMN ODS_SODTL5.FDZMSL IS '袋子母数量';
COMMENT ON COLUMN ODS_SODTL5.FJSLTYPE IS '件塑料类型';
COMMENT ON COLUMN ODS_SODTL5.FJSLSL IS '件塑料数量';
COMMENT ON COLUMN ODS_SODTL5.FDSLTYPE IS '袋塑料类型';
COMMENT ON COLUMN ODS_SODTL5.FDSLSL IS '袋塑料数量';
COMMENT ON COLUMN ODS_SODTL5.FSELFTMNO IS '自条码号';
COMMENT ON COLUMN ODS_SODTL5.FSELFTMTYPE IS '自条码类型';
COMMENT ON COLUMN ODS_SODTL5.FSELFTMNO1 IS '自条码号1';
COMMENT ON COLUMN ODS_SODTL5.FSELFTMTYPE1 IS '自码类型1';
COMMENT ON COLUMN ODS_SODTL5.FSELFTMSL IS '自条码数量';
COMMENT ON COLUMN ODS_SODTL5.FSELFTMSL1 IS '自码数量1';
COMMENT ON COLUMN ODS_SODTL5.FSELFBQNO IS '自标签号';
COMMENT ON COLUMN ODS_SODTL5.FSELFBQTYPE IS '自标签类型';
COMMENT ON COLUMN ODS_SODTL5.FSELFBQNO1 IS '自标签号1';
COMMENT ON COLUMN ODS_SODTL5.FSELFBQTYPE1 IS '自签类型1';
COMMENT ON COLUMN ODS_SODTL5.FSELFBQSL IS '自标签数量';
COMMENT ON COLUMN ODS_SODTL5.FSELFBQSL1 IS '自标签数量1';
COMMENT ON COLUMN ODS_SODTL5.FTPSL IS '托盘数量';
COMMENT ON COLUMN ODS_SODTL5.FNCTYPE IS '内衬类型';
COMMENT ON COLUMN ODS_SODTL5.NCLX IS '内衬类型';
COMMENT ON COLUMN ODS_SODTL5.NCSL IS '内衬数量';
COMMENT ON COLUMN ODS_SODTL5.FHH1 IS '货号1';
COMMENT ON COLUMN ODS_SODTL5.UT IS '数量单元';
COMMENT ON COLUMN ODS_SODTL5.SLMLX IS '';
COMMENT ON COLUMN ODS_SODTL5.SLMSL IS '';
COMMENT ON COLUMN ODS_SODTL5.CZFL IS '';
COMMENT ON COLUMN ODS_SODTL5.BMCL IS '';
COMMENT ON COLUMN ODS_SODTL5.SCGY IS '';
COMMENT ON COLUMN ODS_SODTL5.SCX IS '';
COMMENT ON COLUMN ODS_SODTL5.FFDLX IS '封堵类型';
COMMENT ON COLUMN ODS_SODTL5.FFDSL IS '封堵数量';
COMMENT ON COLUMN ODS_SODTL5.FMPLX IS '铭牌类型';
COMMENT ON COLUMN ODS_SODTL5.FMPSL IS '铭牌数量';
COMMENT ON COLUMN ODS_SODTL5.FULMPLX IS 'UL序列号铭牌';
COMMENT ON COLUMN ODS_SODTL5.FULMPSL IS 'UL序列号铭牌数量';
COMMENT ON COLUMN ODS_SODTL5.FZDYMPLX IS '自定义铭牌';
COMMENT ON COLUMN ODS_SODTL5.FZDYMPSL IS '自定义铭牌数量';
COMMENT ON COLUMN ODS_SODTL5.FDPLX IS '吊牌类型';
COMMENT ON COLUMN ODS_SODTL5.FDPSL IS '吊牌数量';
COMMENT ON COLUMN ODS_SODTL5.FHGZLX IS '合格证类型';
COMMENT ON COLUMN ODS_SODTL5.FHGZSL IS '合格证数量';
COMMENT ON COLUMN ODS_SODTL5.FCPAZLX IS '产品安装指南';
COMMENT ON COLUMN ODS_SODTL5.FCPAZSL IS '产品安装指南数量';
COMMENT ON COLUMN ODS_SODTL5.FGCLX IS '隔层类型';
COMMENT ON COLUMN ODS_SODTL5.FGCSL IS '隔层数量';
COMMENT ON COLUMN ODS_SODTL5.SDLX IS '';
COMMENT ON COLUMN ODS_SODTL5.SDSL IS '';
COMMENT ON COLUMN ODS_SODTL5.DBDLX IS '';
COMMENT ON COLUMN ODS_SODTL5.DBDSL IS '';
COMMENT ON COLUMN ODS_SODTL5.FSBLX IS '';
COMMENT ON COLUMN ODS_SODTL5.FSBSL IS '';
COMMENT ON COLUMN ODS_SODTL5.DZDLX IS '';
COMMENT ON COLUMN ODS_SODTL5.DZDSL IS '';
COMMENT ON COLUMN ODS_SODTL5.KBQLX IS '';
COMMENT ON COLUMN ODS_SODTL5.KBQSL IS '';
COMMENT ON COLUMN ODS_SODTL5.ZTMH IS '';
COMMENT ON COLUMN ODS_SODTL5.ZTBLX IS '';
COMMENT ON COLUMN ODS_SODTL5.ZTMSL IS '';
COMMENT ON COLUMN ODS_SODTL5.KTMH IS '';
COMMENT ON COLUMN ODS_SODTL5.KTMLX IS '';
COMMENT ON COLUMN ODS_SODTL5.KTMSL IS '';
COMMENT ON COLUMN ODS_SODTL5.WXGGXH IS '';
COMMENT ON COLUMN ODS_SODTL5.TPGGXH IS '';
COMMENT ON COLUMN ODS_SODTL5.WHTMH IS '';
COMMENT ON COLUMN ODS_SODTL5.DTMH IS '';
COMMENT ON COLUMN ODS_SODTL5.IMSBZMXID IS '';
COMMENT ON COLUMN ODS_SODTL5.IMSMXID IS '';
COMMENT ON COLUMN ODS_SODTL5.IMSDTID IS '';
COMMENT ON COLUMN ODS_SODTL5.XDBQSL IS '';
COMMENT ON COLUMN ODS_SODTL5.CPMS1 IS '';
COMMENT ON COLUMN ODS_SODTL5.CPMS2 IS '';
COMMENT ON COLUMN ODS_SODTL5.CPMS3 IS '';
COMMENT ON COLUMN ODS_SODTL5.CPMS4 IS '';
COMMENT ON COLUMN ODS_SODTL5.CPMS5 IS '';
COMMENT ON COLUMN ODS_SODTL5.CPMS6 IS '';
COMMENT ON COLUMN ODS_SODTL5.CPMS7 IS '';
COMMENT ON COLUMN ODS_SODTL5.CPMS8 IS '';
COMMENT ON COLUMN ODS_SODTL5.ETL_CRT_DT IS 'ETL创建日期';
COMMENT ON COLUMN ODS_SODTL5.ETL_UPD_DT IS 'ETL更新日期';