
CREATE TABLE ODS_ERP.ODS_FMZPMXB (
    ID NUMBER,
    ZH VARCHAR2(2000),
    GH VARCHAR2(2000),
    PZ VARCHAR2(2000),
    GG VARCHAR2(2000),
    XS VARCHAR2(2000),
    CZFL VARCHAR2(2000),
    BMCL VARCHAR2(2000),
    JS NUMBER,
    GBBM VARCHAR2(2000),
    GB VARCHAR2(2000),
    DYHGJS NUMBER,
    ZJMPH VARCHAR2(2000),
    ZJFTLCH VARCHAR2(2000),
    ZJFGLCH VARCHAR2(2000),
    ZJXFLCH VARCHAR2(2000),
    ZJFBLCH VARCHAR2(2000),
    LRY VARCHAR2(2000),
    GXSJ DATE,
    DW VARCHAR2(2000),
    DWBM VARCHAR2(2000),
    DDH VARCHAR2(2000),
    RQ VARCHAR2(2000),
    KBID VARCHAR2(2000),
    BZ VARCHAR2(2000),
    ETL_CRT_DT DATE,
    ETL_UPD_DT DATE
);


-- 添加字段注释
COMMENT ON COLUMN ODS_ERP.ODS_FMZPMXB.ID IS '序号';
COMMENT ON COLUMN ODS_ERP.ODS_FMZPMXB.ZH IS '组号';
COMMENT ON COLUMN ODS_ERP.ODS_FMZPMXB.GH IS '工号';
COMMENT ON COLUMN ODS_ERP.ODS_FMZPMXB.PZ IS '品种';
COMMENT ON COLUMN ODS_ERP.ODS_FMZPMXB.GG IS '规格';
COMMENT ON COLUMN ODS_ERP.ODS_FMZPMXB.XS IS '形式';
COMMENT ON COLUMN ODS_ERP.ODS_FMZPMXB.CZFL IS '材质';
COMMENT ON COLUMN ODS_ERP.ODS_FMZPMXB.BMCL IS '表面';
COMMENT ON COLUMN ODS_ERP.ODS_FMZPMXB.JS IS '件数';
COMMENT ON COLUMN ODS_ERP.ODS_FMZPMXB.GBBM IS '工步编码';
COMMENT ON COLUMN ODS_ERP.ODS_FMZPMXB.GB IS '工步';
COMMENT ON COLUMN ODS_ERP.ODS_FMZPMXB.DYHGJS IS '打压-合格件数';
COMMENT ON COLUMN ODS_ERP.ODS_FMZPMXB.ZJMPH IS '质检-铭牌号';
COMMENT ON COLUMN ODS_ERP.ODS_FMZPMXB.ZJFTLCH IS '质检-阀体炉次号';
COMMENT ON COLUMN ODS_ERP.ODS_FMZPMXB.ZJFGLCH IS '质检-阀杆炉次号';
COMMENT ON COLUMN ODS_ERP.ODS_FMZPMXB.ZJXFLCH IS '质检-下阀杆炉次号';
COMMENT ON COLUMN ODS_ERP.ODS_FMZPMXB.ZJFBLCH IS '质检-阀板炉次号';
COMMENT ON COLUMN ODS_ERP.ODS_FMZPMXB.LRY IS '录入员';
COMMENT ON COLUMN ODS_ERP.ODS_FMZPMXB.GXSJ IS '录入时间';
COMMENT ON COLUMN ODS_ERP.ODS_FMZPMXB.DW IS '单位';
COMMENT ON COLUMN ODS_ERP.ODS_FMZPMXB.DWBM IS '单位编码';
COMMENT ON COLUMN ODS_ERP.ODS_FMZPMXB.BZ IS '备注';








