CREATE TABLE ODS_FPSJB (
    ID NUMBER,
    RQ VARCHAR2(2000),
    TFPBM VARCHAR2(2000),
    TFPDW VARCHAR2(2000),
    ZFKBM VARCHAR2(2000),
    ZFKDW VARCHAR2(2000),
    JJCBM VARCHAR2(2000),
    JJCDW VARCHAR2(2000),
    LXBS VARCHAR2(2000),
    FPLX VARCHAR2(2000),
    PZ VARCHAR2(2000),
    GG VARCHAR2(2000),
    XS VARCHAR2(2000),
    DZ NUMBER,
    JS NUMBER,
    LRY VARCHAR2(2000),
    GXSJ DATE,
    ZJGH VARCHAR2(2000),
    ZJGXM VARCHAR2(2000),
    KFG VARCHAR2(2000),
    LCH VARCHAR2(2000),
    JH VARCHAR2(2000),
    CZZDM VARCHAR2(2000),
    FKBM1 VARCHAR2(2000),
    FKDW1 VARCHAR2(2000),
    BC VARCHAR2(2000),
    MPDZ NUMBER,
    SPFP VARCHAR2(2000),
    MH VARCHAR2(2000),
    MJBH VARCHAR2(2000),
    XJS NUMBER,
    FPLX1 VARCHAR2(2000),
    BS VARCHAR2(2000),
    DJ NUMBER,
    SSDJ1 NUMBER,
    SSDJ2 NUMBER,
    JE NUMBER,
    FPSSE NUMBER,
    FPSSE1 NUMBER,
    ZXS VARCHAR2(2000),
    LJTDD NUMBER,
    ZFKDWSCRQ VARCHAR2(2000),
    CD NUMBER,
    JSRQ VARCHAR2(2000),
    FPH VARCHAR2(2000),
    JSBJ VARCHAR2(2000),
    JSDH VARCHAR2(2000),
    HWH VARCHAR2(2000),
    CZFL VARCHAR2(2000),
    BMCL VARCHAR2(2000),
    SCGY VARCHAR2(2000),
    SCX VARCHAR2(2000),
    DYJS NUMBER,
    ZL NUMBER,
    SPDJ NUMBER,
    SPE NUMBER,
    DJGXBZ VARCHAR2(2000),
    FPSSDJ NUMBER,
    SSDJGXBZ VARCHAR2(2000),
    BZ VARCHAR2(2000),
    ZZHGLDW VARCHAR2(2000),
    ZFDW VARCHAR2(2000),
    KJ NUMBER,
    ZLCZFL VARCHAR2(2000),
    TFPGX VARCHAR2(2000),
    ZZHGLJSDW VARCHAR2(2000),
    BZWLX VARCHAR2(2000),
    GDH VARCHAR2(2000),
    KBH VARCHAR2(2000),
    SJLY VARCHAR2(2000),
    CDBS NUMBER,
    CPBM VARCHAR2(2000),
    GYS VARCHAR2(2000),
    ZJBID NUMBER,
    UT VARCHAR2(2000),
    TCXMLX VARCHAR2(2000),
    ETL_CRT_DT DATE DEFAULT SYSDATE,
    ETL_UPD_DT DATE DEFAULT SYSDATE
);

COMMENT ON COLUMN ODS_FPSJB.ID IS '序号';
COMMENT ON COLUMN ODS_FPSJB.RQ IS '日期';
COMMENT ON COLUMN ODS_FPSJB.TFPBM IS '退废品编码';
COMMENT ON COLUMN ODS_FPSJB.TFPDW IS '退废品单位';
COMMENT ON COLUMN ODS_FPSJB.ZFKBM IS '支罚款编码';
COMMENT ON COLUMN ODS_FPSJB.ZFKDW IS '支罚款单位';
COMMENT ON COLUMN ODS_FPSJB.JJCBM IS '减结存编码';
COMMENT ON COLUMN ODS_FPSJB.JJCDW IS '减结存单位';
COMMENT ON COLUMN ODS_FPSJB.LXBS IS '类型标示';
COMMENT ON COLUMN ODS_FPSJB.FPLX IS '废品类型';
COMMENT ON COLUMN ODS_FPSJB.PZ IS '品种';
COMMENT ON COLUMN ODS_FPSJB.GG IS '规格';
COMMENT ON COLUMN ODS_FPSJB.XS IS '形式';
COMMENT ON COLUMN ODS_FPSJB.DZ IS '单重';
COMMENT ON COLUMN ODS_FPSJB.JS IS '件数';
COMMENT ON COLUMN ODS_FPSJB.LRY IS '录入员';
COMMENT ON COLUMN ODS_FPSJB.GXSJ IS '更新时间';
COMMENT ON COLUMN ODS_FPSJB.ZJGH IS '质检工号';
COMMENT ON COLUMN ODS_FPSJB.ZJGXM IS '质检工姓名';
COMMENT ON COLUMN ODS_FPSJB.KFG IS '库分工';
COMMENT ON COLUMN ODS_FPSJB.LCH IS '炉次号';
COMMENT ON COLUMN ODS_FPSJB.JH IS '件号';
COMMENT ON COLUMN ODS_FPSJB.CZZDM IS '操作者代码';
COMMENT ON COLUMN ODS_FPSJB.FKBM1 IS '罚款编码1';
COMMENT ON COLUMN ODS_FPSJB.FKDW1 IS '罚款单位1';
COMMENT ON COLUMN ODS_FPSJB.BC IS '班次';
COMMENT ON COLUMN ODS_FPSJB.MPDZ IS '毛坯单重';
COMMENT ON COLUMN ODS_FPSJB.SPFP IS '生坯废品';
COMMENT ON COLUMN ODS_FPSJB.MH IS '模号';
COMMENT ON COLUMN ODS_FPSJB.MJBH IS '模具编号';
COMMENT ON COLUMN ODS_FPSJB.XJS IS '箱件数';
COMMENT ON COLUMN ODS_FPSJB.FPLX1 IS '废品类型1';
COMMENT ON COLUMN ODS_FPSJB.BS IS '标示';
COMMENT ON COLUMN ODS_FPSJB.DJ IS '单价';
COMMENT ON COLUMN ODS_FPSJB.SSDJ1 IS '损失单价1';
COMMENT ON COLUMN ODS_FPSJB.SSDJ2 IS '损失单价2';
COMMENT ON COLUMN ODS_FPSJB.JE IS '罚款额1';
COMMENT ON COLUMN ODS_FPSJB.FPSSE IS '废品损失额';
COMMENT ON COLUMN ODS_FPSJB.FPSSE1 IS '废品损失1';
COMMENT ON COLUMN ODS_FPSJB.ZXS IS '主形式';
COMMENT ON COLUMN ODS_FPSJB.LJTDD IS '累计投订单';
COMMENT ON COLUMN ODS_FPSJB.ZFKDWSCRQ IS '';
COMMENT ON COLUMN ODS_FPSJB.CD IS '长度';
COMMENT ON COLUMN ODS_FPSJB.JSRQ IS '';
COMMENT ON COLUMN ODS_FPSJB.FPH IS '';
COMMENT ON COLUMN ODS_FPSJB.JSBJ IS '';
COMMENT ON COLUMN ODS_FPSJB.JSDH IS '结算单号';
COMMENT ON COLUMN ODS_FPSJB.HWH IS '货位号';
COMMENT ON COLUMN ODS_FPSJB.CZFL IS '材质分类';
COMMENT ON COLUMN ODS_FPSJB.BMCL IS '表面处理';
COMMENT ON COLUMN ODS_FPSJB.SCGY IS '';
COMMENT ON COLUMN ODS_FPSJB.SCX IS '生产线';
COMMENT ON COLUMN ODS_FPSJB.DYJS IS '';
COMMENT ON COLUMN ODS_FPSJB.ZL IS '重量';
COMMENT ON COLUMN ODS_FPSJB.SPDJ IS '索赔单价';
COMMENT ON COLUMN ODS_FPSJB.SPE IS '索赔额';
COMMENT ON COLUMN ODS_FPSJB.DJGXBZ IS '单价更新备注';
COMMENT ON COLUMN ODS_FPSJB.FPSSDJ IS '废品损失单价';
COMMENT ON COLUMN ODS_FPSJB.SSDJGXBZ IS '损失单价更新备注';
COMMENT ON COLUMN ODS_FPSJB.BZ IS '班组';
COMMENT ON COLUMN ODS_FPSJB.ZZHGLDW IS '铸造合格率单位';
COMMENT ON COLUMN ODS_FPSJB.ZFDW IS '支付单位';
COMMENT ON COLUMN ODS_FPSJB.KJ IS '口径';
COMMENT ON COLUMN ODS_FPSJB.ZLCZFL IS '质量材质分类';
COMMENT ON COLUMN ODS_FPSJB.TFPGX IS '退废品工序';
COMMENT ON COLUMN ODS_FPSJB.ZZHGLJSDW IS '合格率单位';
COMMENT ON COLUMN ODS_FPSJB.BZWLX IS '';
COMMENT ON COLUMN ODS_FPSJB.GDH IS '工单号';
COMMENT ON COLUMN ODS_FPSJB.KBH IS '看板号';
COMMENT ON COLUMN ODS_FPSJB.SJLY IS '';
COMMENT ON COLUMN ODS_FPSJB.CDBS IS '';
COMMENT ON COLUMN ODS_FPSJB.CPBM IS '产品编码';
COMMENT ON COLUMN ODS_FPSJB.GYS IS '';
COMMENT ON COLUMN ODS_FPSJB.ZJBID IS '';
COMMENT ON COLUMN ODS_FPSJB.UT IS '';
COMMENT ON COLUMN ODS_FPSJB.TCXMLX IS '';
COMMENT ON COLUMN ODS_FPSJB.ETL_CRT_DT IS '';
COMMENT ON COLUMN ODS_FPSJB.ETL_UPD_DT IS '';