表名  DIM_PRODUCT_SORT

CREATE TABLE DIM_PRODUCT_SORT

PRODUCT_SORT1  PRODUCT_SORT2 PRODUCT_SORT3 PRODUCT_VARIETY



CREATE TABLE DIM_PRODUCT_SORT (
PRODUCT_SORT1 VARCHAR(100) COMMENT '产品大类', 
PRODUCT_SORT2 VARCHAR(100) COMMENT '产品中类', 
PRODUCT_SORT3 VARCHAR(100) COMMENT '产品小类', 
PRODUCT_VARIETY VARCHAR(100) COMMENT '品类' 
) COMMENT"产品大中小类基础库" ;




CREATE TABLE DIM_PRODUCT_SORT (
    PRODUCT_SORT1 VARCHAR2(200), 
    PRODUCT_SORT2 VARCHAR2(200), 
    PRODUCT_SORT3 VARCHAR2(200), 
    PRODUCT_VARIETY VARCHAR2(200) 
) 




CREATE TABLE DIM_PRODUCT_SORT (
    PRODUCT_SORT1 VARCHAR2(200), 
    PRODUCT_SORT2 VARCHAR2(200), 
    PRODUCT_SORT3 VARCHAR2(200), 
    PRODUCT_VARIETY VARCHAR2(200)
);

COMMENT ON TABLE DIM_PRODUCT_SORT IS '产品分类维度表-记录产品的多级分类信息';

COMMENT ON COLUMN DIM_PRODUCT_SORT.PRODUCT_SORT1 IS '产品一级分类（大类）';
COMMENT ON COLUMN DIM_PRODUCT_SORT.PRODUCT_SORT2 IS '产品二级分类（中类）';
COMMENT ON COLUMN DIM_PRODUCT_SORT.PRODUCT_SORT3 IS '产品三级分类（小类）';
COMMENT ON COLUMN DIM_PRODUCT_SORT.PRODUCT_VARIETY IS '产品品种/品类';