
TRUNCATE TABLE ADS_PACKAGE_WAREHOUSE_SUM_TG
INSERT INTO ADS_PACKAGE_WAREHOUSE_SUM_TG (
    PERIOD,
    WAREHOUSING_TYPE,
    GROUP_NAME,
    WAREHOUSING_WEIGHT_T,
    FINE_PACKAGING_CNT,
    FINE_PACKAGING_WGT_T

)

WITH ALL_TO_ONE AS (
     SELECT DDH ,
            CASE WHEN KHJC='丛德贸易' THEN '1' ELSE FJZ END AS ISJBZ,
            FBUYNUM AS JBZ_CNT ,
            TOTALNW AS JBZ_WGT
            FROM  ODS_ERP.ODS_SOCTRL_TG
)
,ORDER_CLEAN AS (
            SELECT 
               TO_DATE(RQ,'YY.MM.DD') AS PERIOD,
               DDH,
               RKDW,
               SUM(ZL) AS ZL
            FROM ODS_ERP.ODS_BZRKB_TG
            WHERE RQ NOT LIKE'  %'
            GROUP BY DDH,RKDW,TO_DATE(RQ,'YY.MM.DD')
            
)

--SELECT COUNT(*),DDH FROM ORDER_CLEAN GROUP BY DDH
SELECT 
      A.PERIOD,
      C.RKCZ,
      A.RKDW,
      SUM(A.ZL)/1000,
      --MAX(B.ISJBZ),
      SUM(CASE WHEN B.ISJBZ='1' THEN B.JBZ_CNT ELSE 0 END) AS FINE_PACKAGING_CNT,
      SUM(CASE WHEN B.ISJBZ='1'THEN B.JBZ_WGT ELSE 0 END)/1000 AS FINE_PACKAGING_WGT_T
FROM ORDER_CLEAN A 
     LEFT JOIN ALL_TO_ONE B ON A.DDH=B.DDH 
     LEFT JOIN MDDIM.DIM_GROUP_TO_TYPE_TG C  ON C.BZDW=A.RKDW
GROUP BY A.PERIOD,C.RKCZ,A.RKDW



----------------------------------------------------------------------------------------------------


CREATE TABLE ADS_PACKAGE_WAREHOUSE_SUM_TG (
    PERIOD DATE,
    WAREHOUSING_TYPE VARCHAR2(2000),
    GROUP_NAME VARCHAR2(2000),
    WAREHOUSING_WEIGHT_T NUMBER,
    FINE_PACKAGING_CNT NUMBER,
    FINE_PACKAGING_WGT_T NUMBER,
    ETL_CRT_DT DATE DEFAULT SYSDATE,
    ETL_UPD_DT DATE DEFAULT SYSDATE
);

COMMENT ON TABLE ADS_PACKAGE_WAREHOUSE_SUM_TG IS '包装入库汇总表';

COMMENT ON COLUMN ADS_PACKAGE_WAREHOUSE_SUM_TG.PERIOD IS '日期';
COMMENT ON COLUMN ADS_PACKAGE_WAREHOUSE_SUM_TG.WAREHOUSING_TYPE IS '入库材质';
COMMENT ON COLUMN ADS_PACKAGE_WAREHOUSE_SUM_TG.GROUP_NAME IS '入库单位';
COMMENT ON COLUMN ADS_PACKAGE_WAREHOUSE_SUM_TG.WAREHOUSING_WEIGHT_T IS '入库重量';
COMMENT ON COLUMN ADS_PACKAGE_WAREHOUSE_SUM_TG.FINE_PACKAGING_CNT IS '精装件数';
COMMENT ON COLUMN ADS_PACKAGE_WAREHOUSE_SUM_TG.FINE_PACKAGING_WGT_T IS '精装吨位';
COMMENT ON COLUMN ADS_PACKAGE_WAREHOUSE_SUM_TG.ETL_CRT_DT IS 'ETL创建日期';
COMMENT ON COLUMN ADS_PACKAGE_WAREHOUSE_SUM_TG.ETL_UPD_DT IS 'ETL更新日期';


----------------------------------------------------------------20251013

INSERT INTO ADS_PACKAGE_WAREHOUSE_SUM_TG (
    PERIOD,
    WAREHOUSING_TYPE,
    GROUP_NAME,
    WAREHOUSING_WEIGHT_T,
    FINE_PACKAGING_CNT,
    FINE_PACKAGING_WGT_T

)
WITH ALL_TO_ONE AS (
     SELECT DDH ,
            CASE WHEN KHJC='丛德贸易' THEN '1' ELSE FJZ END AS ISJBZ,
            FBUYNUM AS JBZ_CNT ,
            TOTALNW AS JBZ_WGT
            FROM  ODS_ERP.ODS_SOCTRL_TG
)
,ORDER_CLEAN AS (
            SELECT 
               TO_DATE(RQ,'YY.MM.DD') AS PERIOD,
               DDH,
               RKDW,
               SUM(JS) AS JS,
               SUM(ZL) AS ZL
            FROM ODS_ERP.ODS_BZRKB_TG
            WHERE RQ NOT LIKE'  %'
            GROUP BY DDH,RKDW,TO_DATE(RQ,'YY.MM.DD')
            
            
)

SELECT 
      A.PERIOD,
      C.RKCZ,
      A.RKDW,
      SUM(A.ZL)/1000,
      SUM(CASE WHEN (B.ISJBZ='1' AND D.DDQZ IS NOT NULL) THEN A.JS ELSE 0 END) AS FINE_PACKAGING_CNT,
      SUM(CASE WHEN (B.ISJBZ='1' AND D.DDQZ IS NOT NULL) THEN A.ZL ELSE 0 END)/1000 AS FINE_PACKAGING_WGT_T
FROM ORDER_CLEAN A 
     LEFT JOIN ALL_TO_ONE B ON A.DDH=B.DDH 
     LEFT JOIN MDDIM.DIM_GROUP_TO_TYPE_TG C  ON C.BZDW=A.RKDW
     LEFT JOIN (
        SELECT 
        DDQZ
        FROM MDDIM.DIM_ORDER_TO_TEXTURE
        WHERE LX='BZ'
     ) D  ON SUBSTR(A.DDH, 1, 3) = D.DDQZ

GROUP BY A.PERIOD,C.RKCZ,A.RKDW



---------------------------------------------------------20251013



TRUNCATE TABLE ADS_PACKAGE_WAREHOUSE_SUM_TG ;
INSERT INTO ADS_PACKAGE_WAREHOUSE_SUM_TG (
    PERIOD,
    WAREHOUSING_TYPE,
    GROUP_NAME,
    WAREHOUSING_WEIGHT_T,
    FINE_PACKAGING_CNT,
    FINE_PACKAGING_WGT_T

)

WITH ALL_TO_ONE AS (
     SELECT DDH ,
            CASE WHEN KHJC='丛德贸易' THEN '1' ELSE FJZ END AS ISJBZ,
            FBUYNUM AS JBZ_CNT ,
            TOTALNW AS JBZ_WGT
            FROM  ODS_ERP.ODS_SOCTRL_TG
)
,ORDER_CLEAN AS (
            SELECT 
               TO_DATE(RQ,'YY.MM.DD') AS PERIOD,
               DDH,
               RKDW,
               SUM(CASE WHEN KHXSH<0 AND DDH='内销' THEN JS*-1 ELSE JS END ) AS JS,
               SUM(CASE WHEN KHXSH<0 AND DDH='内销' THEN ZL*-1 ELSE ZL END) AS ZL
            FROM ODS_ERP.ODS_BZRKB_TG
            WHERE RQ NOT LIKE'  %'
            GROUP BY DDH,RKDW,TO_DATE(RQ,'YY.MM.DD')
            
            
)

SELECT 
      A.PERIOD,
      C.RKCZ,
      A.RKDW,
      SUM(case when (c.rkcz='玛钢转产' and d.ddqz is null) then 0 else A.ZL end)/1000 as zl,
      SUM(CASE WHEN (B.ISJBZ='1') THEN A.JS ELSE 0 END) AS FINE_PACKAGING_CNT,
      SUM(CASE WHEN (B.ISJBZ='1') THEN A.ZL ELSE 0 END)/1000 AS FINE_PACKAGING_WGT_T
FROM ORDER_CLEAN A 
     LEFT JOIN ALL_TO_ONE B ON A.DDH=B.DDH 
     LEFT JOIN MDDIM.DIM_GROUP_TO_TYPE_TG C  ON C.BZDW=A.RKDW
     LEFT JOIN (
        SELECT 
        DDQZ
        FROM MDDIM.DIM_ORDER_TO_TEXTURE
        WHERE LX='bz'
     ) D  ON SUBSTR(A.DDH, 1, 3) = D.DDQZ
GROUP BY A.PERIOD,C.RKCZ,A.RKDW

