CREATE TABLE ADS_SHIPMENT_SUM_TG (
    PERIOD DATE,
    PRODUCT_NAME VARCHAR2(2000),
    IN_WEIGHT_T NUMBER,
    OUT_WEIGHT_T NUMBER,
    SHIP_WGT_T_SAMEP NUMBER,
    ETL_CRT_DT DATE DEFAULT SYSDATE,
    ETL_UPD_DT DATE DEFAULT SYSDATE
);

COMMENT ON TABLE ADS_SHIPMENT_SUM_TG IS '泰钢发货汇总表';

COMMENT ON COLUMN ADS_SHIPMENT_SUM_TG.PERIOD IS '发货日期';
COMMENT ON COLUMN ADS_SHIPMENT_SUM_TG.PRODUCT_NAME IS '材质';
COMMENT ON COLUMN ADS_SHIPMENT_SUM_TG.IN_WEIGHT_T IS '内销重量';
COMMENT ON COLUMN ADS_SHIPMENT_SUM_TG.OUT_WEIGHT_T IS '外销重量';
COMMENT ON COLUMN ADS_SHIPMENT_SUM_TG.SHIP_WGT_T_SAMEP IS '上月同期累计发货';
COMMENT ON COLUMN ADS_SHIPMENT_SUM_TG.ETL_CRT_DT IS 'ETL创建日期';
COMMENT ON COLUMN ADS_SHIPMENT_SUM_TG.ETL_UPD_DT IS 'ETL更新日期';