CREATE TABLE DIM_ORDER_TO_TEXTURE (
    ID NUMBER,
    CZBZ VARCHAR2(2000),
    DDQZ VARCHAR2(2000),
    LX VARCHAR2(2000),
    LRY VARCHAR2(2000),
    GXSJ DATE,
    ETL_CRT_DT DATE DEFAULT SYSDATE,
    ETL_UPD_DT DATE DEFAULT SYSDATE
);

COMMENT ON TABLE DIM_ORDER_TO_TEXTURE IS '泰钢订单与材质/步骤映射表';

COMMENT ON COLUMN DIM_ORDER_TO_TEXTURE.ID IS '序号';
COMMENT ON COLUMN DIM_ORDER_TO_TEXTURE.CZBZ IS '材质步骤';
COMMENT ON COLUMN DIM_ORDER_TO_TEXTURE.DDQZ IS '订单前缀';
COMMENT ON COLUMN DIM_ORDER_TO_TEXTURE.LX IS '类型';
COMMENT ON COLUMN DIM_ORDER_TO_TEXTURE.LRY IS '录入员';
COMMENT ON COLUMN DIM_ORDER_TO_TEXTURE.GXSJ IS '更新时间';
COMMENT ON COLUMN DIM_ORDER_TO_TEXTURE.ETL_CRT_DT IS 'ETL创建日期';
COMMENT ON COLUMN DIM_ORDER_TO_TEXTURE.ETL_UPD_DT IS 'ETL更新日期';


grant select on DIM_ORDER_TO_TEXTURE to MDADS;
grant select on DIM_ORDER_TO_TEXTURE to MDDWD;
grant select on DIM_ORDER_TO_TEXTURE to MDDWS;
grant select on DIM_ORDER_TO_TEXTURE to ODS_ERP;