CREATE TABLE DIM_GROUP_TO_TYPE_TG (
    ID NUMBER,
    BZDW VARCHAR2(2000),
    RKCZ VARCHAR2(2000),
    LRY VARCHAR2(2000),
    GXSJ DATE,
    ETL_CRT_DT DATE DEFAULT SYSDATE,
    ETL_UPD_DT DATE DEFAULT SYSDATE
);

COMMENT ON TABLE DIM_GROUP_TO_TYPE_TG IS '泰钢单位与入库材质映射表';

COMMENT ON COLUMN DIM_GROUP_TO_TYPE_TG.ID IS '序号';
COMMENT ON COLUMN DIM_GROUP_TO_TYPE_TG.BZDW IS '包装单位';
COMMENT ON COLUMN DIM_GROUP_TO_TYPE_TG.RKCZ IS '入库材质';
COMMENT ON COLUMN DIM_GROUP_TO_TYPE_TG.LRY IS '录入员';
COMMENT ON COLUMN DIM_GROUP_TO_TYPE_TG.GXSJ IS '更新时间';
COMMENT ON COLUMN DIM_GROUP_TO_TYPE_TG.ETL_CRT_DT IS 'ETL创建日期';
COMMENT ON COLUMN DIM_GROUP_TO_TYPE_TG.ETL_UPD_DT IS 'ETL更新日期';


INSERT INTO DIM_GROUP_TO_TYPE_TG (
    ID,
    BZDW,
    RKCZ,
    LRY,
    GXSJ,
    ETL_CRT_DT,
    ETL_UPD_DT
)
