
 SELECT * FROM CRM_SO_ORDER_HEADER    DIM  ORG_ID DELIVERY_ORG   STATUS  DELIVERY_REQUEST  ORDER_TYPE_ID   IS_INTERNATIONAL_TRADE
 
 SELECT * FROM ODS_CRM_LG_DELIVERY_PLAN
 
 SELECT * FROM 
 
 
 
 SELECT * FROM mddim.dim_org_d where SOURCE_SYS='IMS' and ORG_NAME like'%泰钢管配件%'
 SELECT distinct DELIVERY_ORG FROM CRM_SO_ORDER_HEADER 


SELECT DISTINCT  A.CUSTOMER_ID,a.order_num,B.COMPANY_REGISTER_NAME
FROM CRM_SO_ORDER_HEADER A 
LEFT JOIN ODS_CRM_CTM_CUST_INTRODUCE B 
     ON A.CUSTOMER_ID=B.CUSTOMER_ID
left join ods_erp.ODS_SOCTRL_TG C
     ON C.DDH=A.ORDER_NUM
WHERE 
     a.org_id in(19,20,97) --得一  卓睿  香港
    AND A.DELIVERY_ORG =1112--68_泰钢管配件2402
    AND A.STATUS=  'C'           --订单状态
    AND A.IS_INTERNATIONAL_TRADE='Y' --外销
    AND A.ORDER_TYPE_ID= 1000580     --订单类型
    AND A.DELIVERY_REQUEST IS NULL --发货状态？



转产：1T1  1s2  1s3  1t9 19e  
