
TRUNCATE TABLE MDADS.ADS_KEY_PRODUCTION_CAPACITY ;
INSERT INTO MDADS.ADS_KEY_PRODUCTION_CAPACITY 
(
    PERIOD ,                             -- 日期
    PRODUCTION_NAME ,           -- 生产线
    CAPACITY_TYPE ,            -- 产能类型
    MONTHLY_CAPACITY ,                 -- 月产能
    MIN_CAPACITY_RATE ,        -- 最低产能负荷率
    MEASUREMENT_NAME ,         -- 计量单位
    WEIGHT_M_SHIP_T, --重量月度发货_吨
    WEIGHT_M_SHIP_T_LAST, --重量上月发货_吨
    WEIGHT_M_SHIP_T_SAMEP, --重量同期发货_吨
    WEIGHT_M_SHIP_TAR_T, --重量月度目标_吨
    WEIGHT_M_TARGET_T, -- 重量月度目标_吨_不含储备
    WEIGHT_M_ACTUAL_T, -- 重量月度实际_吨_不含储备
    WEIGHT_LAST_M_ACTUAL_T, -- 重量上月实际_吨_不含储备
    WEIGHT_M_SAMEP_T, -- 重量本月同期_吨_不含储备
    WEIGHT_M_TARGET_T_ALL, -- 重量月度目标_吨_含储备
    WEIGHT_M_ACTUAL_T_ALL, -- 重量月度实际_吨_含储备
    WEIGHT_LAST_M_ACTUAL_T_ALL, -- 重量上月实际_吨_含储备
    WEIGHT_M_SAMEP_T_ALL, -- 重量本月同期_吨_含储备
    ACC_CAPACITY, -- 累计产能
    ACC_FINISH, -- 累计完成
    ACC_FINISH_SAMEP, -- 累计同期产能
   IS_KEY_FOCUS , -- 是否重点关注
    ETL_CRT_DT , -- ETL创建时间
    ETL_UPD_DT      -- ETL更新时间
)

SELECT 
    A.PERIOD PERIOD ,                -- 日期
    A.PRODUCT_LINE ,           -- 生产线
    B.CAPACITY_TYPE,  -- 产能类型
    C.MONTHLY_CAPACITY,
    C.MIN_CAPACITY_RATE ,        -- 最低产能负荷率
    C.UNIT ,         -- 计量单位
    D.WEIGHT_M_ACTUAL_T --重量月度发货_吨
    ,D.WEIGHT_LAST_M_ACTUAL_T --重量上月发货_
    ,D.WEIGHT_M_SAMEP_T --重量同期发货_
    ,D.WEIGHT_M_TARGET_T --重量月度目标_吨
    ,A.WEIGHT_M_TARGET_T-- 重量月度目标_吨_不含储备
    ,A.WEIGHT_M_ACTUAL_T_UNSAVE-- 重量月度实际_吨_不含储备
    ,A.WEIGHT_LM_ACTUAL_T_UNSAVE-- 重量上月实际_吨_不含储备
    ,A.WEIGHT_SAMEP_M_TARGET_T-- 重量本月同期_吨_不含储备
    ,A.WEIGHT_M_TARGET_T-- 重量月度目标_吨_含储备
    ,A.WEIGHT_M_ACTUAL_T_SAVE+A.WEIGHT_M_ACTUAL_T_UNSAVE--- 重量月度实际_吨_含储备
    ,A.WEIGHT_LM_ACTUAL_T_SAVE+A.WEIGHT_LM_ACTUAL_T_UNSAVE-- 重量上月实际_吨_含储备
    ,A.WEIGHT_SAMEP_M_ACTUAL_T_SAVE+A.WEIGHT_SAMEP_M_ACTUAL_T_UNSAVE-- 重量本月同期_吨_含储备
    ,C.MONTHLY_CAPACITY*(EXTRACT(MONTH FROM ADD_MONTHS(SYSDATE,-1)))--累计产能
    ,A.WEIGHT_M_ACC_ACTUAL_T_UNSAVE  ---累计完成
    ,A.WEIGHT_SAMEP_MACC_ACT_T_UNSAVE-- 累计同期产能
    ,CASE 
        WHEN (A.WEIGHT_M_ACC_ACTUAL_T_UNSAVE< (C.MIN_CAPACITY_T * EXTRACT(MONTH FROM ADD_MONTHS(SYSDATE,-1))))
                OR (A.WEIGHT_LM_ACTUAL_T_UNSAVE < C.MIN_CAPACITY_T AND A.WEIGHT_LSM_ACTUAL_T_UNSAVE<C.MIN_CAPACITY_T)
        THEN '是'
    ELSE '否'
    END AS IS_KEY_FOCUS 

    ,SYSDATE ETL_CRT_DT     -- ETL创建时间
    ,SYSDATE  ETL_UPD_DT       -- ETL更新时间



    FROM  MDDWS.DWS_PRODUCT_ORDER_REVENUE A--生产订单业绩汇总表

LEFT JOIN  (
    SELECT DISTINCT PRODUCTION_LINE, PRODUCT_SORT1,PRODUCT_SORT2,PRODUCT_SORT3,PRODUCT_SORT4,CAPACITY_TYPE
    FROM MDDWD.DWD_CNLXDZB
)B
    ON A.PRODUCT_LINE = B.PRODUCTION_LINE
    AND A.PRODUCT_SORT1=B.PRODUCT_SORT1
    AND A.PRODUCT_SORT2=B.PRODUCT_SORT2
    AND A.PRODUCT_SORT3=B.PRODUCT_SORT3
    AND A.PRODUCT_SORT4=B.PRODUCT_SORT4

    LEFT JOIN MDDWD.DWD_CNJCB C--产能基础表
    ON A.PRODUCT_LINE=C.PRODUCTION_LINE
        AND B.CAPACITY_TYPE=C.CAPACITY_TYPE
    
    LEFT JOIN
    (
        SELECT to_char(PERIOD,'yyyymm') PERIOD,CORPORATE_ENTITY_NAME_SN,PRODUCT_SORT1,PRODUCT_SORT2,PRODUCT_SORT3,
        SUM(WEIGHT_M_ACTUAL_T) WEIGHT_M_ACTUAL_T,
        SUM(WEIGHT_LAST_M_ACTUAL_T) WEIGHT_LAST_M_ACTUAL_T,
        SUM(WEIGHT_M_SAMEP_T) WEIGHT_M_SAMEP_T,
        SUM(WEIGHT_M_TARGET_T) WEIGHT_M_TARGET_T
        FROM 
        MDADS.ADS_SALE_REVENUE 
        WHERE SALES_TARGET_TYPE='挑战目标'  and (to_char(PERIOD,'yyyymmdd') = to_char(sysdate -1,'yyyymmdd') or to_char(PERIOD,'yyyymm') <to_char(sysdate -1,'yyyymm'))
        GROUP BY to_char(PERIOD,'yyyymm'),CORPORATE_ENTITY_NAME_SN,PRODUCT_SORT1,PRODUCT_SORT2,PRODUCT_SORT3
    )D

    ON  to_char(A.PERIOD,'yyyymm') =D.PERIOD AND A.PRODUCT_LINE=D.CORPORATE_ENTITY_NAME_SN
    AND A.PRODUCT_SORT1=D.PRODUCT_SORT1
    AND A.PRODUCT_SORT2=D.PRODUCT_SORT2
    AND A.PRODUCT_SORT3=D.PRODUCT_SORT3
where  to_char(A.PERIOD,'yyyymm')  >= '202507'
    ;


DELETE from  MDADS.ADS_KEY_PRODUCTION_CAPACITY  WHERE IS_KEY_FOCUS  = '否';