SELECT * FROM DWD_CNJCB

SELECT * FROM DWD_CNLXDZB






-- DWD层产能基础表
CREATE TABLE "MDDWD"."DWD_CNJCB" 
(
    "ID" VARCHAR2(2000), 
    "PRODUCTION_LINE" VARCHAR2(2000), 
    "FACTORY" VARCHAR2(2000), 
    "CAPACITY_TYPE" VARCHAR2(2000), 
    "WORKING_DAYS" VARCHAR2(2000), 
    "MONTHLY_CAPACITY" VARCHAR2(2000), 
    "UNIT" VARCHAR2(2000), 
    "MAX_CAPACITY_RATE" VARCHAR2(2000), 
    "MAX_CAPACITY_UNIT" VARCHAR2(2000), 
    "CAPACITY_RESPONSIBLE" VARCHAR2(2000), 
    "CREATED_BY" VARCHAR2(2000), 
    "UPDATE_TIME" DATE, 
    "ETL_CREATE_DATE" DATE, 
    "ETL_UPDATE_DATE" DATE
) 


-- DWD层产能基础表注释
COMMENT ON TABLE "MDDWD"."DWD_CNJCB" IS '产能基础表 - DWD层';
COMMENT ON COLUMN "MDDWD"."DWD_CNJCB"."ID" IS '唯一标识ID';
COMMENT ON COLUMN "MDDWD"."DWD_CNJCB"."PRODUCTION_LINE" IS '生产线名称';
COMMENT ON COLUMN "MDDWD"."DWD_CNJCB"."FACTORY" IS '厂区';
COMMENT ON COLUMN "MDDWD"."DWD_CNJCB"."CAPACITY_TYPE" IS '产能类型';
COMMENT ON COLUMN "MDDWD"."DWD_CNJCB"."WORKING_DAYS" IS '生产天数';
COMMENT ON COLUMN "MDDWD"."DWD_CNJCB"."MONTHLY_CAPACITY" IS '月产能';
COMMENT ON COLUMN "MDDWD"."DWD_CNJCB"."UNIT" IS '计量单位';
COMMENT ON COLUMN "MDDWD"."DWD_CNJCB"."MAX_CAPACITY_RATE" IS '最大产能负荷率';
COMMENT ON COLUMN "MDDWD"."DWD_CNJCB"."MAX_CAPACITY_UNIT" IS '最大产能单位';
COMMENT ON COLUMN "MDDWD"."DWD_CNJCB"."CAPACITY_RESPONSIBLE" IS '产能责任人';
COMMENT ON COLUMN "MDDWD"."DWD_CNJCB"."CREATED_BY" IS '录入人';
COMMENT ON COLUMN "MDDWD"."DWD_CNJCB"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "MDDWD"."DWD_CNJCB"."ETL_CREATE_DATE" IS 'ETL创建时间';
COMMENT ON COLUMN "MDDWD"."DWD_CNJCB"."ETL_UPDATE_DATE" IS 'ETL更新时间';

-- DWD层产能类型对照表
CREATE TABLE "MDDWD"."DWD_CNLXDZB" 
(
    "ID" VARCHAR2(2000), 
    "PRODUCTION_LINE" VARCHAR2(2000), 
    "PRODUCT_CATEGORY" VARCHAR2(2000), 
    "PRODUCT_SUBCATEGORY" VARCHAR2(2000), 
    "PRODUCT_TYPE" VARCHAR2(2000), 
    "PRODUCT_LINE" VARCHAR2(2000), 
    "CAPACITY_TYPE" VARCHAR2(2000), 
    "START_DATE" VARCHAR2(2000), 
    "END_DATE" VARCHAR2(2000), 
    "CREATED_BY" VARCHAR2(2000), 
    "UPDATE_TIME" DATE, 
    "ETL_CREATE_DATE" DATE, 
    "ETL_UPDATE_DATE" DATE
) 


-- DWD层产能类型对照表注释
COMMENT ON TABLE "MDDWD"."DWD_CNLXDZB" IS '产能类型对照表 - DWD层';
COMMENT ON COLUMN "MDDWD"."DWD_CNLXDZB"."ID" IS '唯一标识ID';
COMMENT ON COLUMN "MDDWD"."DWD_CNLXDZB"."PRODUCTION_LINE" IS '生产线';
COMMENT ON COLUMN "MDDWD"."DWD_CNLXDZB"."PRODUCT_CATEGORY" IS '产品大类';
COMMENT ON COLUMN "MDDWD"."DWD_CNLXDZB"."PRODUCT_SUBCATEGORY" IS '产品中类';
COMMENT ON COLUMN "MDDWD"."DWD_CNLXDZB"."PRODUCT_TYPE" IS '产品小类';
COMMENT ON COLUMN "MDDWD"."DWD_CNLXDZB"."PRODUCT_LINE" IS '品类';
COMMENT ON COLUMN "MDDWD"."DWD_CNLXDZB"."CAPACITY_TYPE" IS '产能类型';
COMMENT ON COLUMN "MDDWD"."DWD_CNLXDZB"."START_DATE" IS '开始日期';
COMMENT ON COLUMN "MDDWD"."DWD_CNLXDZB"."END_DATE" IS '截止日期';
COMMENT ON COLUMN "MDDWD"."DWD_CNLXDZB"."CREATED_BY" IS '录入人';
COMMENT ON COLUMN "MDDWD"."DWD_CNLXDZB"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "MDDWD"."DWD_CNLXDZB"."ETL_CREATE_DATE" IS 'ETL创建时间';
COMMENT ON COLUMN "MDDWD"."DWD_CNLXDZB"."ETL_UPDATE_DATE" IS 'ETL更新时间';