SELECT * FROM DWD_CNJCB

SELECT * FROM DWD_CNLXDZB



CREATE TABLE "MDDWD"."DWD_CNJCB" 
   (	"ID" VARCHAR2(2000), 
	"PRODUCTION_LINE" VARCHAR2(2000), 
	"FACTORY" VARCHAR2(2000), 
	"CAPACITY_TYPE" VARCHAR2(2000), 
	"WORKING_DAYS" VARCHAR2(2000), 
	"MONTHLY_CAPACITY" VARCHAR2(2000), 
	"UNIT" VARCHAR2(2000), 
	"MIN_CAPACITY_RATE" VARCHAR2(2000), 
	"MIN_CAPACITY_T" VARCHAR2(2000), 
	"CAPACITY_RESPONSIBLE" VARCHAR2(2000), 
	"CREATED_BY" VARCHAR2(2000), 
	"UPDATE_TIME" DATE, 
	"ETL_CREATE_DATE" DATE, 
	"ETL_UPDATE_DATE" DATE
   )




CREATE TABLE "MDDWD"."DWD_CNLXDZB" 
   (	"ID" VARCHAR2(2000), 
	"PRODUCTION_LINE" VARCHAR2(2000), 
	"PRODUCT_SORT1" VARCHAR2(2000), 
	"PRODUCT_SORT2" VARCHAR2(2000), 
	"PRODUCT_SORT3" VARCHAR2(2000), 
	"PRODUCT_SORT4" VARCHAR2(2000), 
	"CAPACITY_TYPE" VARCHAR2(2000), 
	"START_DATE" VARCHAR2(2000), 
	"END_DATE" VARCHAR2(2000), 
	"CREATED_BY" VARCHAR2(2000), 
	"UPDATE_TIME" DATE, 
	"ETL_CREATE_DATE" DATE, 
	"ETL_UPDATE_DATE" DATE, 
	"PRODUCE_COMPANY_NAME_SN" VARCHAR2(2000)
   )







truncate table MDDWD.DWD_CNLXDZB;

insert into  MDDWD.DWD_CNLXDZB(
   ID , 
  PRODUCTION_LINE , 
  PRODUCT_SORT1 , 
  PRODUCT_SORT2 , 
  PRODUCT_SORT3 , 
  PRODUCT_SORT4 , 
  CAPACITY_TYPE , 
  START_DATE , 
  END_DATE , 
  CREATED_BY , 
  UPDATE_TIME , 
  ETL_CRT_DT , 
  ETL_UPD_DT , 
  PRODUCE_COMPANY_NAME_SN 

)

SELECT
     id
   , scx
   , cpdl
   , cpzl
   , cpxl
   , pl
   , cnlx
   , ksrq
   , jzrq
   , lry
   , gxsj
   ,etl_crt_dt
   ,etl_upd_dt
   ,scgs
FROM ODS_ERP.ODS_CNLXDZB




----------------------------------------------------


truncate table MDDWD.DWD_CNJCB;

INSERT INTO MDDWD.DWD_CNJCB(

   ID , 
  PRODUCTION_LINE , 
  FACTORY , 
  CAPACITY_TYPE , 
  WORKING_DAYS , 
  MONTHLY_CAPACITY , 
  UNIT , 
  MIN_CAPACITY_RATE , 
  MIN_CAPACITY_T , 
  CAPACITY_RESPONSIBLE , 
  CREATED_BY , 
  UPDATE_TIME , 
  ETL_CRT_DT , 
  ETL_UPD_DT 
)
SELECT 
     id
   , scx
   , cq
   , cnlx
   , scts
   , ycn
   , jldw
   , zdcnfhl
   , zdcndw
   , cnzrr
   , lry
   , gxsj
   , etl_crt_dt
   , etl_upd_dt
FROM ODS_ERP.ODS_CNJCB

