-- 添加表注释
COMMENT ON TABLE "ODS_ERP"."ODS_CNLXDZB" IS '产能类型对照表';

-- 添加字段注释
COMMENT ON COLUMN "ODS_ERP"."ODS_CNLXDZB"."ID" IS '唯一标识ID';
COMMENT ON COLUMN "ODS_ERP"."ODS_CNLXDZB"."SCX" IS '生产线';
COMMENT ON COLUMN "ODS_ERP"."ODS_CNLXDZB"."CPDL" IS '产品大类';
COMMENT ON COLUMN "ODS_ERP"."ODS_CNLXDZB"."CPZL" IS '产品中类';
COMMENT ON COLUMN "ODS_ERP"."ODS_CNLXDZB"."CPXL" IS '产品小类';
COMMENT ON COLUMN "ODS_ERP"."ODS_CNLXDZB"."PL" IS '品类';
COMMENT ON COLUMN "ODS_ERP"."ODS_CNLXDZB"."CNLX" IS '产能类型';
COMMENT ON COLUMN "ODS_ERP"."ODS_CNLXDZB"."KSRQ" IS '开始日期';
COMMENT ON COLUMN "ODS_ERP"."ODS_CNLXDZB"."JZRQ" IS '截止日期';
COMMENT ON COLUMN "ODS_ERP"."ODS_CNLXDZB"."LRY" IS '录入人';
COMMENT ON COLUMN "ODS_ERP"."ODS_CNLXDZB"."GXSJ" IS '更新时间';
COMMENT ON COLUMN "ODS_ERP"."ODS_CNLXDZB"."ETL_CRT_DT" IS '创建时间';
COMMENT ON COLUMN "ODS_ERP"."ODS_CNLXDZB"."ETL_UPD_DT" IS '更新时间';