
MDADS.ADS_YEARLY_PLAN_VS_CAP_tmp


pro_id  --序号  
period  --日期
production_name --生产线	
FACTORY_NAME --厂区名称
capacity_type --产能类型
monthly_working_days --月生产天数
monthly_capacity  --月产能
year_capacity  --年产能
Measurement_name  --计量单位
SALE_FORE_inter --国内销售预测
sale_fore_over  --  国外销售预测
order_qty_inter --国内接单量
order_qty_over --国外接单量
order_qty_inter_last --国内接单量
order_qty_over_last --国外接单量

is_meet_standard   --是否达标

NUM_INNER  --今年国内某数值
NUM_OVER    --今年海外某数值

NUM_INNER_LAST--去年某数值
NUM_OVER_LAST--去年某数值

序号 天数  产能  销售预测 接单量  是number
period  是date
剩下的是varchar