重点关注产线X月产能满负荷率报表
    "PERIOD" DATE,                             -- 日期

    "PRODUCTION_NAME" VARCHAR2(2000),           -- 生产线
    "CAPACITY_TYPE" VARCHAR2(2000),             -- 产能类型
    "MONTHLY_CAPACITY" NUMBER,                 -- 月产能
    MIN_CAPACITY_RATE VARCHAR2(2000),  
    "MEASUREMENT_NAME" VARCHAR2(2000),           -- 计量单位

    WEIGHT_M_TARGET_T   number   --重量月度目标_吨_不含储备
    WEIGHT_M_ACTUAL_T number  --重量月度实际_吨_不含储备
    WEIGHT_LAST_M_ACTUAL_T number--重量上月实际_吨_不含储备
    WEIGHT_M_SAMEP_T number--重量本月同期_吨_不含储备

    WEIGHT_M_TARGET_T_ALL   number   --重量月度目标_吨_含储备
    WEIGHT_M_ACTUAL_T_ALL number  --重量月度实际_吨_含储备
    WEIGHT_LAST_M_ACTUAL_T_ALL number--重量上月实际_吨_含储备
    WEIGHT_M_SAMEP_T_ALL number--重量本月同期_吨_含储备
    ACC_CAPACITY NUMBER  --累计产能
    acc_finish number --累计完成
    IS_KEY_FOCUS  varchar2(2000)--是否重点关注
    ACC_CAPACITY_LAST NUMBER  --去年累计同期产能







CREATE TABLE "MDADS"."ADS_KEY_PRODUCTION_CAPACITY" 
(
    "PERIOD" DATE,                             -- 日期
    "PRODUCTION_NAME" VARCHAR2(2000),           -- 生产线
    "CAPACITY_TYPE" VARCHAR2(2000),            -- 产能类型
    "MONTHLY_CAPACITY" NUMBER,                 -- 月产能
    "MIN_CAPACITY_RATE" NUMBER,        -- 最小产能利用率
    "MEASUREMENT_NAME" VARCHAR2(2000),         -- 计量单位

--发货
WEIGHT_M_SHIP_T NUMBER, --重量月度发货_吨
WEIGHT_M_SHIP_T_LAST NUMBER, --重量上月发货_吨
WEIGHT_M_SHIP_T_SAMEP NUMBER, --重量同期发货_吨
WEIGHT_M_SHIP_TAR_T NUMBER, --重量月度目标_吨

-- 不含储备的重量指标
"WEIGHT_M_TARGET_T" NUMBER, -- 重量月度目标_吨_不含储备
"WEIGHT_M_ACTUAL_T" NUMBER, -- 重量月度实际_吨_不含储备
"WEIGHT_LAST_M_ACTUAL_T" NUMBER, -- 重量上月实际_吨_不含储备
"WEIGHT_M_SAMEP_T" NUMBER, -- 重量本月同期_吨_不含储备

-- 含储备的重量指标
"WEIGHT_M_TARGET_T_ALL" NUMBER, -- 重量月度目标_吨_含储备
"WEIGHT_M_ACTUAL_T_ALL" NUMBER, -- 重量月度实际_吨_含储备
"WEIGHT_LAST_M_ACTUAL_T_ALL" NUMBER, -- 重量上月实际_吨_含储备
"WEIGHT_M_SAMEP_T_ALL" NUMBER, -- 重量本月同期_吨_含储备

-- 累计指标
"ACC_CAPACITY" NUMBER, -- 累计产能
"ACC_FINISH" NUMBER, -- 累计完成
"ACC_CAPACITY_LAST" NUMBER, -- 去年累计同期产能

-- 标志位
"IS_KEY_FOCUS" VARCHAR2 (2000), -- 是否重点关注

-- ETL相关字段
"ETL_CRT_DT" DATE DEFAULT SYSDATE,    -- ETL创建时间
    "ETL_UPD_DT" DATE DEFAULT SYSDATE     -- ETL更新时间
) 
;
-- 添加表注释
COMMENT ON TABLE "MDADS"."ADS_KEY_PRODUCTION_CAPACITY" IS '重点关注产线X月产能满负荷率报表';

-- 添加字段注释
COMMENT ON COLUMN "MDADS"."ADS_KEY_PRODUCTION_CAPACITY"."PERIOD" IS '日期';

COMMENT ON COLUMN "MDADS"."ADS_KEY_PRODUCTION_CAPACITY"."PRODUCTION_NAME" IS '生产线名称';

COMMENT ON COLUMN "MDADS"."ADS_KEY_PRODUCTION_CAPACITY"."CAPACITY_TYPE" IS '产能类型';

COMMENT ON COLUMN "MDADS"."ADS_KEY_PRODUCTION_CAPACITY"."MONTHLY_CAPACITY" IS '月产能';

COMMENT ON COLUMN "MDADS"."ADS_KEY_PRODUCTION_CAPACITY"."MIN_CAPACITY_RATE" IS '最小产能利用率';

COMMENT ON COLUMN "MDADS"."ADS_KEY_PRODUCTION_CAPACITY"."MEASUREMENT_NAME" IS '计量单位';

-- 不含储备重量指标注释
COMMENT ON COLUMN "MDADS"."ADS_KEY_PRODUCTION_CAPACITY"."WEIGHT_M_TARGET_T" IS '重量月度目标(吨)-不含储备';

COMMENT ON COLUMN "MDADS"."ADS_KEY_PRODUCTION_CAPACITY"."WEIGHT_M_ACTUAL_T" IS '重量月度实际(吨)-不含储备';

COMMENT ON COLUMN "MDADS"."ADS_KEY_PRODUCTION_CAPACITY"."WEIGHT_LAST_M_ACTUAL_T" IS '重量上月实际(吨)-不含储备';

COMMENT ON COLUMN "MDADS"."ADS_KEY_PRODUCTION_CAPACITY"."WEIGHT_M_SAMEP_T" IS '重量本月同期(吨)-不含储备';

-- 含储备重量指标注释
COMMENT ON COLUMN "MDADS"."ADS_KEY_PRODUCTION_CAPACITY"."WEIGHT_M_TARGET_T_ALL" IS '重量月度目标(吨)-含储备';

COMMENT ON COLUMN "MDADS"."ADS_KEY_PRODUCTION_CAPACITY"."WEIGHT_M_ACTUAL_T_ALL" IS '重量月度实际(吨)-含储备';

COMMENT ON COLUMN "MDADS"."ADS_KEY_PRODUCTION_CAPACITY"."WEIGHT_LAST_M_ACTUAL_T_ALL" IS '重量上月实际(吨)-含储备';

COMMENT ON COLUMN "MDADS"."ADS_KEY_PRODUCTION_CAPACITY"."WEIGHT_M_SAMEP_T_ALL" IS '重量本月同期(吨)-含储备';

-- 累计指标注释
COMMENT ON COLUMN "MDADS"."ADS_KEY_PRODUCTION_CAPACITY"."ACC_CAPACITY" IS '累计产能';

COMMENT ON COLUMN "MDADS"."ADS_KEY_PRODUCTION_CAPACITY"."ACC_FINISH" IS '累计完成量';

COMMENT ON COLUMN "MDADS"."ADS_KEY_PRODUCTION_CAPACITY"."ACC_CAPACITY_LAST" IS '去年累计同期产能';

-- 标志位注释
COMMENT ON COLUMN "MDADS"."ADS_KEY_PRODUCTION_CAPACITY"."IS_KEY_FOCUS" IS '是否重点关注';

-- ETL字段注释
COMMENT ON COLUMN "MDADS"."ADS_KEY_PRODUCTION_CAPACITY"."ETL_CRT_DT" IS 'ETL创建时间';

COMMENT ON COLUMN "MDADS"."ADS_KEY_PRODUCTION_CAPACITY"."ETL_UPD_DT" IS 'ETL更新时间';