CREATE TABLE ADS_MKFM_PRODUTION_SUM (
    PERIOD DATE,
    WORK_ORG_NAME VARCHAR2(2000),
    NOW_INVENTORY_LAST NUMBER,
    NON_PLANNED_INVENTORY_LAST NUMBER,
    NOW_INVENTORY NUMBER,
    NON_PLANNED_INVENTORY NUMBER,
    SELF_PRODUCED_PIECE_COUNT NUMBER,
    SELF_PRODUCED_WEIGHT_T NUMBER,
    PURCHASED_PIECE_COUNT NUMBER,
    PURCHASED_WEIGHT_T NUMBER,
    SELF_PRODUCED_PIECE_M NUMBER,
    SELF_PRODUCED_M_T NUMBER,
    PURCHASED_PIECE_M NUMBER,
    PURCHASED_M_T NUMBER,
    ETL_CRT_DT DATE DEFAULT SYSDATE,
    ETL_UPD_DT DATE DEFAULT SYSDATE
);

COMMENT ON TABLE ADS_MKFM_PRODUTION_SUM IS 'MKFM生产汇总表';

COMMENT ON COLUMN ADS_MKFM_PRODUTION_SUM.PERIOD IS '日期';
COMMENT ON COLUMN ADS_MKFM_PRODUTION_SUM.WORK_ORG_NAME IS '工作组';
COMMENT ON COLUMN ADS_MKFM_PRODUTION_SUM.NOW_INVENTORY_LAST IS '上月今结存';
COMMENT ON COLUMN ADS_MKFM_PRODUTION_SUM.NON_PLANNED_INVENTORY_LAST IS '上月计外存';
COMMENT ON COLUMN ADS_MKFM_PRODUTION_SUM.NOW_INVENTORY IS '今结存';
COMMENT ON COLUMN ADS_MKFM_PRODUTION_SUM.NON_PLANNED_INVENTORY IS '计外存';
COMMENT ON COLUMN ADS_MKFM_PRODUTION_SUM.SELF_PRODUCED_PIECE_COUNT IS '日自产件数';
COMMENT ON COLUMN ADS_MKFM_PRODUTION_SUM.SELF_PRODUCED_WEIGHT_T IS '日自产重量（吨）';
COMMENT ON COLUMN ADS_MKFM_PRODUTION_SUM.PURCHASED_PIECE_COUNT IS '日外购件数';
COMMENT ON COLUMN ADS_MKFM_PRODUTION_SUM.PURCHASED_WEIGHT_T IS '日外购重量（吨）';
COMMENT ON COLUMN ADS_MKFM_PRODUTION_SUM.SELF_PRODUCED_PIECE_M IS '自产件数汇总';
COMMENT ON COLUMN ADS_MKFM_PRODUTION_SUM.SELF_PRODUCED_M_T IS '月自产重量汇总（吨）';
COMMENT ON COLUMN ADS_MKFM_PRODUTION_SUM.PURCHASED_PIECE_M IS '月外购件数汇总';
COMMENT ON COLUMN ADS_MKFM_PRODUTION_SUM.PURCHASED_M_T IS '月外购重量汇总（吨）';
COMMENT ON COLUMN ADS_MKFM_PRODUTION_SUM.ETL_CRT_DT IS 'ETL创建日期';
COMMENT ON COLUMN ADS_MKFM_PRODUTION_SUM.ETL_UPD_DT IS 'ETL更新日期';


--------------------------------------------------------------



INSERT INTO ADS_MKFM_PRODUTION_SUM (
    PERIOD,
    WORK_ORG_NAME,
    NOW_INVENTORY_LAST,
    NON_PLANNED_INVENTORY_LAST,
    NOW_INVENTORY,
    NON_PLANNED_INVENTORY,
    SELF_PRODUCED_PIECE_COUNT,
    SELF_PRODUCED_WEIGHT_T,
    PURCHASED_PIECE_COUNT,
    PURCHASED_WEIGHT_T,
    SELF_PRODUCED_PIECE_M,
    SELF_PRODUCED_M_T,
    PURCHASED_PIECE_M,
    PURCHASED_M_T,
    ETL_CRT_DT,
    ETL_UPD_DT
)
SELECT
    COALESCE(A.PERIOD, B.PERIOD_M) AS PERIOD,
    COALESCE(A.WORK_ORG_NAME, B.RKDW) AS WORK_ORG_NAME,
    A.NOW_INVENTORY_LAST,
    A.NON_PLANNED_INVENTORY_LAST,
    A.NOW_INVENTORY,
    A.NON_PLANNED_INVENTORY,
    B.SELF_PRODUCED_PIECE_COUNT,
    B.SELF_PRODUCED_WEIGHT_T,
    B.PURCHASED_PIECE_COUNT,
    B.PURCHASED_WEIGHT_T,
    B.SELF_PRODUCED_PIECE_M,
    B.SELF_PRODUCED_M_T,
    B.PURCHASED_PIECE_M,
    B.PURCHASED_M_T,
    SYSDATE,
    SYSDATE
FROM
    MDDWS.DWS_MKFM_SEMIFINISH_INVENTORY A
FULL JOIN MDDWS.DWS_MKFM_PRODUCTION_MONTHLY B
    ON A.PERIOD = B.PERIOD_M
    AND A.WORK_ORG_NAME = B.RKDW;

    -------------------------------------------------------------------------------



INSERT INTO ADS_MKFM_PRODUTION_SUM(
       PERIOD
       ,WORK_ORG_NAME
       ,NOW_INVENTORY
       ,NOW_INVENTORY_LAST
       
)

WITH TMP_CB AS(
     SELECT DISTINCT DW,CB FROM ODS_ERP.ODS_FRGXGB WHERE CB IN('孝直分厂','玫德临沂')
),
TMP_IN AS(
       SELECT DISTINCT DW FROM ODS_ERP.ODS_FRGXGB
)

,
TMP_DWD AS(
  SELECT TRUNC(A.PERIOD,'MM') AS PERIOD 
         ,CASE WHEN A.WORK_ORG_NAME NOT IN (SELECT DW FROM TMP_IN) THEN '外协'
               ELSE (CASE WHEN B.CB ='孝直分厂' THEN '孝直分厂'
                          WHEN B.CB='玫德临沂' THEN '临沂分厂'
                     END)
          END AS WORK_ORG_NAME
          ,WEIGHT
          ,PIECE_COUNT
  FROM MDDWD.DWD_MAIN_TRANSFER_SUMMARY A 
  LEFT JOIN TMP_CB B
  ON A.WORK_ORG_NAME=B.DW 
  WHERE 
      A.RECEIVING_ORG IN('迈克阀门毛坯周转组','迈克阀门分流组')

)
SELECT PERIOD
       ,WORK_ORG_NAME
       ,SUM(WEIGHT)/1000 AS NOW_INVENTOY
       ,LAG(SUM(WEIGHT)/1000,1) OVER(PARTITION BY WORK_ORG_NAME ORDER BY PERIOD) NOW_INVENTOY_LAST
       --,SUM(PIECE_COUNT)
   FROM TMP_DWD 
   WHERE WORK_ORG_NAME IS NOT NULL  
GROUP BY PERIOD,WORK_ORG_NAME

SELECT * FROM ADS_FINISH_GOOD_STOCK
SELECT * FROM ODS_JNMD.BZRKB



--------------------------------------20251016

SELECT
    COALESCE(A.PERIOD, B.PERIOD_M) AS PERIOD,
    COALESCE(A.WORK_ORG_NAME, B.RKDW) AS WORK_ORG_NAME,
    A.NOW_INVENTORY_LAST,
    A.NON_PLANNED_INVENTORY_LAST,
    A.NOW_INVENTORY,
    A.NON_PLANNED_INVENTORY,
    B.SELF_PRODUCED_PIECE_COUNT,
    B.SELF_PRODUCED_WEIGHT_T,
    B.PURCHASED_PIECE_COUNT,
    B.PURCHASED_WEIGHT_T,
    B.SELF_PRODUCED_PIECE_M,
    B.SELF_PRODUCED_M_T,
    B.PURCHASED_PIECE_M,
    B.PURCHASED_M_T,
    SYSDATE,
    SYSDATE
FROM
    MDDWS.DWS_MKFM_SEMIFINISH_INVENTORY A
FULL JOIN(
    SELECT
        B.PERIOD_M,
        B.RKDW,
        B.SELF_PRODUCED_PIECE_COUNT,
        B.SELF_PRODUCED_WEIGHT_T,
        B.PURCHASED_PIECE_COUNT,
        B.PURCHASED_WEIGHT_T,
        B.SELF_PRODUCED_PIECE_M,
        B.SELF_PRODUCED_M_T,
        B.PURCHASED_PIECE_M,
        B.PURCHASED_M_T
    FROM MDDWS.DWS_MKFM_PRODUCTION_MONTHLY B 
    UNION ALL
    SELECT 
          TRUNC(PERIOD,'MM') AS PERIOD_M,
          WORK_ORG_NAME AS RKDW,
          NULL,
          SUM(CASE WHEN D.UT!='SETW' THEN WEIGHT ELSE 0 END) AS SELF_PRODUCED_WEIGHT_T,
          NULL,
          SUM(CASE WHEN D.UT='SETW' THEN WEIGHT ELSE 0 END) AS PURCHASED_WEIGHT_T,
          NULL,
          NULL,
          NULL,
          NULL
          
     FROM 
          MDDWD.DWD_MAIN_TRANSFER_SUMMARY C
     LEFT JOIN ODS_ERP.ODS_INVITEM D 
     ON C.PRODUCT_CODE=D.XCLBM
     GROUP BY TRUNC(PERIOD,'MM'),WORK_ORG_NAME
    
) E
    ON A.PERIOD = E.PERIOD_M
    AND A.WORK_ORG_NAME = E.RKDW;