-- 创建DWD表
CREATE TABLE DWD_MKFM_PRODUCTION_DATA (
    PERIOD DATE,  -- 日期
    RKDW VARCHAR2(2000),  -- 入库单位
    SELF_PRODUCED_PIECE_COUNT NUMBER,  -- 自产件数
    SELF_PRODUCED_WEIGHT_T NUMBER,  -- 自产重量（吨）
    PURCHASED_PIECE_COUNT NUMBER,  -- 外购件数
    PURCHASED_WEIGHT_T NUMBER,  -- 外购重量（吨）
    ETL_CRT_DT DATE DEFAULT SYSDATE,  -- ETL创建日期
    ETL_UPD_DT DATE DEFAULT SYSDATE  -- ETL更新日期
);

-- 添加表注释
COMMENT ON TABLE DWD_MKFM_PRODUCTION_DATA IS '迈克阀门生产数据初步汇总';

-- 添加列注释
COMMENT ON COLUMN DWD_MKFM_PRODUCTION_DATA.PERIOD IS '日期';
COMMENT ON COLUMN DWD_MKFM_PRODUCTION_DATA.RKDW IS '入库单位';
COMMENT ON COLUMN DWD_MKFM_PRODUCTION_DATA.SELF_PRODUCED_PIECE_COUNT IS '自产件数';
COMMENT ON COLUMN DWD_MKFM_PRODUCTION_DATA.SELF_PRODUCED_WEIGHT_T IS '自产重量（吨）';
COMMENT ON COLUMN DWD_MKFM_PRODUCTION_DATA.PURCHASED_PIECE_COUNT IS '外购件数';
COMMENT ON COLUMN DWD_MKFM_PRODUCTION_DATA.PURCHASED_WEIGHT_T IS '外购重量（吨）';
COMMENT ON COLUMN DWD_MKFM_PRODUCTION_DATA.ETL_CRT_DT IS 'ETL创建日期';
COMMENT ON COLUMN DWD_MKFM_PRODUCTION_DATA.ETL_UPD_DT IS 'ETL更新日期';