CREATE TABLE DWD_MAIN_TRANSFER_SUMMARY (
    PERIOD DATE,                      -- 日期
    WORK_ORG_NAME VARCHAR2(2000),     -- 转出单位/工作组织名称
    WEIGHT NUMBER,                    -- 重量(原始单位)
    PIECE_COUNT NUMBER,               -- 件数
    SURFACE_TREATMENT,
    PRODUCT_TEXTURE,
    PRODUCT_VARIETY,
    PRODUCT_SPECIFICATION,
    PRODUCT_FORM,
    ETL_CRT_DT DATE DEFAULT SYSDATE,  -- ETL创建日期
    ETL_UPD_DT DATE DEFAULT SYSDATE   -- ETL更新日期
);

-- 表注释
COMMENT ON TABLE DWD_MAIN_TRANSFER_SUMMARY IS '统一领转重量件数汇总表';

-- 列注释
COMMENT ON COLUMN DWD_MAIN_TRANSFER_SUMMARY.PERIOD IS '日期';
COMMENT ON COLUMN DWD_MAIN_TRANSFER_SUMMARY.WORK_ORG_NAME IS '转出单位';
COMMENT ON COLUMN DWD_MAIN_TRANSFER_SUMMARY.WEIGHT IS '重量';
COMMENT ON COLUMN DWD_MAIN_TRANSFER_SUMMARY.PIECE_COUNT IS '件数';
COMMENT ON COLUMN DWD_MAIN_TRANSFER_SUMMARY.ETL_CRT_DT IS 'ETL创建日期';
COMMENT ON COLUMN DWD_MAIN_TRANSFER_SUMMARY.ETL_UPD_DT IS 'ETL更新日期';

-- 从ODS层抽取并转换数据到DWD层
INSERT INTO DWD_MAIN_TRANSFER_SUMMARY (
    PERIOD, 
    WORK_ORG_NAME, 
    WEIGHT, 
    PIECE_COUNT,
    SURFACE_TREATMENT,
    PRODUCT_TEXTURE,
    PRODUCT_VARIETY,
    PRODUCT_SPECIFICATION,
    PRODUCT_FORM
)
SELECT 
    TO_DATE(RQ,'YY.MM.DD') AS PERIOD,
    ZCDW AS WORK_ORG_NAME,
    ZL AS WEIGHT,
    JS AS PIECE_COUNT,
    BMCL AS SURFACE_TREATMENT,
    CZFL AS PRODUCT_TEXTURE,
    PZ AS PRODUCT_VARIETY,
    GG AS PRODUCT_SPECIFICATION,
    XS AS PRODUCT_FORM
FROM 
    ODS_QCSJB_CKYW
