DWS_MKFM_SEMIFINISH_INVENTORY 


CREATE TABLE DWS_MKFM_SEMIFINISH_INVENTORY (
    PERIOD DATE,                      -- 日期
    WORK_ORG_NAME VARCHAR2(2000),     -- 工作组织/部门名称
    NOW_INVENTORY NUMBER,             -- 当前库存(吨)
    NON_PLANNED_INVENTORY NUMBER,     -- 非计划库存(千件)
    NOW_INVENTORY_LAST NUMBER,        -- 上期当前库存(吨)
    NON_PLANNED_INVENTORY_LAST NUMBER,-- 上期非计划库存(千件)
    ETL_CRT_DT DATE DEFAULT SYSDATE,  -- ETL创建日期
    ETL_UPD_DT DATE DEFAULT SYSDATE   -- ETL更新日期
);

-- 表注释
COMMENT ON TABLE DWS_MKFM_SEMIFINISH_INVENTORY IS '迈克阀门半成品库存汇总表';

-- 列注释
COMMENT ON COLUMN DWS_MKFM_SEMIFINISH_INVENTORY.PERIOD IS '日期';
COMMENT ON COLUMN DWS_MKFM_SEMIFINISH_INVENTORY.WORK_ORG_NAME IS '入库单位';
COMMENT ON COLUMN DWS_MKFM_SEMIFINISH_INVENTORY.NOW_INVENTORY IS '今结存';
COMMENT ON COLUMN DWS_MKFM_SEMIFINISH_INVENTORY.NON_PLANNED_INVENTORY IS '计外存';
COMMENT ON COLUMN DWS_MKFM_SEMIFINISH_INVENTORY.NOW_INVENTORY_LAST IS '上月今结存';
COMMENT ON COLUMN DWS_MKFM_SEMIFINISH_INVENTORY.NON_PLANNED_INVENTORY_LAST IS '上月计外存';
COMMENT ON COLUMN DWS_MKFM_SEMIFINISH_INVENTORY.ETL_CRT_DT IS 'ETL创建日期';
COMMENT ON COLUMN DWS_MKFM_SEMIFINISH_INVENTORY.ETL_UPD_DT IS 'ETL更新日期';

-- 从DWD层汇总数据并插入DWS表
INSERT INTO DWS_MKFM_SEMIFINISH_INVENTORY (
    PERIOD, 
    WORK_ORG_NAME, 
    NOW_INVENTORY, 
    NON_PLANNED_INVENTORY,
    NOW_INVENTORY_LAST,
    NON_PLANNED_INVENTORY_LAST
)
WITH TMP AS (
    SELECT 
        A.period,
        A.WORK_ORG_NAME,
        SUM(A.WEIGHT_BALANCE_NOW_KG)/1000 AS NOW_INVENTORY,
        SUM(A.COUNT_OUT_BALANCE_PCS)/1000 AS NON_PLANNED_INVENTORY
    FROM MDDWD.DWD_SEMIFINISH_GOOD A 
    WHERE A.factory_name='迈克阀门' 
    GROUP BY 
        A.period,
        A.WORK_ORG_NAME
)
SELECT 
    period,
    WORK_ORG_NAME,
    NOW_INVENTORY,
    NON_PLANNED_INVENTORY,
    LAG(NOW_INVENTORY,1) OVER(PARTITION BY WORK_ORG_NAME ORDER BY PERIOD) AS NOW_INVENTORY_LAST,
    LAG(NON_PLANNED_INVENTORY,1) OVER(PARTITION BY WORK_ORG_NAME ORDER BY PERIOD) AS NON_PLANNED_INVENTORY_LAST
FROM TMP;