CREATE TABLE DWS_MKFM_PRODUCTION_MONTHLY (
    PERIOD DATE,                  -- 日期（日粒度）
    PERIOD_M DATE,            -- 月份（月粒度，存储为当月第一天）
    RKDW VARCHAR2(2000),          -- 入库单位
    SELF_PRODUCED_PIECE_COUNT NUMBER,  -- 自产件数（日粒度）
    SELF_PRODUCED_WEIGHT_T NUMBER,     -- 自产重量（吨）（日粒度）
    PURCHASED_PIECE_COUNT NUMBER,      -- 外购件数（日粒度）
    PURCHASED_WEIGHT_T NUMBER,         -- 外购重量（吨）（日粒度）
    SELF_PRODUCED_PIECE_M NUMBER,  -- 月自产件数汇总
    SELF_PRODUCED_M_T NUMBER,     -- 月自产重量汇总（吨）
    PURCHASED_PIECE_M NUMBER,      -- 月外购件数汇总
    PURCHASED_M_T NUMBER,         -- 月外购重量汇总（吨）
    ETL_CRT_DT DATE DEFAULT SYSDATE,           -- ETL创建日期
    ETL_UPD_DT DATE DEFAULT SYSDATE            -- ETL更新日期
);
INSERT INTO DWS_MKFM_PRODUCTION_MONTHLY (
    PERIOD,
    PERIOD_M,
    RKDW,
    SELF_PRODUCED_PIECE_COUNT,
    SELF_PRODUCED_WEIGHT_T,
    PURCHASED_PIECE_COUNT,
    PURCHASED_WEIGHT_T,
    SELF_PRODUCED_PIECE_M,
    SELF_PRODUCED_M_T,
    PURCHASED_PIECE_M,
    PURCHASED_M_T,
    ETL_CRT_DT,
    ETL_UPD_DT
)
SELECT 
    d.PERIOD,
    TRUNC(d.PERIOD, 'MM') AS PERIOD_M,
    d.RKDW,
    d.SELF_PRODUCED_PIECE_COUNT,
    d.SELF_PRODUCED_WEIGHT_T,
    d.PURCHASED_PIECE_COUNT,
    d.PURCHASED_WEIGHT_T,
    SUM(d.SELF_PRODUCED_PIECE_COUNT) OVER (PARTITION BY TRUNC(d.PERIOD, 'MM'), d.RKDW) AS SELF_PRODUCED_PIECE_M,
    SUM(d.SELF_PRODUCED_WEIGHT_T) OVER (PARTITION BY TRUNC(d.PERIOD, 'MM'), d.RKDW) AS SELF_PRODUCED_M_T,
    SUM(d.PURCHASED_PIECE_COUNT) OVER (PARTITION BY TRUNC(d.PERIOD, 'MM'), d.RKDW) AS PURCHASED_PIECE_M,
    SUM(d.PURCHASED_WEIGHT_T) OVER (PARTITION BY TRUNC(d.PERIOD, 'MM'), d.RKDW) AS PURCHASED_M_T,
    SYSDATE AS ETL_CRT_DT,
    SYSDATE AS ETL_UPD_DT
FROM 
    DWD_MKFM_PRODUCTION_DATA d;