CREATE TABLE ODS_QCSJB_CKYW (
    ID NUMBER,  -- 序号
    PZ VARCHAR2(2000),  -- 品种
    GG VARCHAR2(2000),  -- 规格
    XS VARCHAR2(2000),  -- 形式
    JS NUMBER,  -- 件数
    DZ NUMBER,  -- 单重
    ZCBM VARCHAR2(2000),  -- 转出编码
    ZCDW VARCHAR2(2000),  -- 转出单位
    LQBM VARCHAR2(2000),  -- 领取编码
    LQDW VARCHAR2(2000),  -- 领取单位
    RQ VARCHAR2(2000),  -- 日期
    GXSJ DATE,  -- 更新时间
    LRY VARCHAR2(2000),  -- 录入员
    MZ NUMBER,  -- 毛重
    PZH NUMBER,  -- 皮重
    SCZL NUMBER,  -- 实测重量
    SCJS NUMBER,  -- 实测件数
    SCDZ NUMBER,  -- 实测单重
    CH VARCHAR2(2000),  -- 车号
    BC VARCHAR2(2000),  -- 班次
    LHGH VARCHAR2(2000),  -- 拉货工号
    LH VARCHAR2(2000),  -- 炉号
    JSRQ VARCHAR2(2000),  -- 结算日期
    LCH VARCHAR2(2000),  -- 炉次号
    SKHH VARCHAR2(2000),  -- 数控华晃
    CD NUMBER,  -- 长度
    JGBM VARCHAR2(2000),  -- 经过编码
    JGDW VARCHAR2(2000),  -- 经过单位
    GBZH VARCHAR2(2000),  -- gb转换
    JC NUMBER,  -- 结存
    LS NUMBER,  -- 根数
    QK NUMBER,  -- 切口
    LRYGH VARCHAR2(2000),  -- 录入员工号
    BJBM VARCHAR2(2000),  -- 半加编码
    BJDW VARCHAR2(2000),  -- 半加单位
    ZT VARCHAR2(2000),  -- 状态
    BZWZT VARCHAR2(2000),  -- 包装物状态
    CLS NUMBER,  -- 出炉数
    KJ VARCHAR2(2000),  -- 口径
    DJGH VARCHAR2(2000),  -- 倒角工号
    DDH VARCHAR2(2000),  -- 订单号
    BMJ NUMBER,  -- 表面积
    SFGZ VARCHAR2(2000),  -- 是否改制
    SBJTH VARCHAR2(2000),  -- 设备机台号
    SCFS VARCHAR2(2000),  -- 生产方式
    SBBS VARCHAR2(2000),  -- 设备标示
    CLDZ NUMBER,  -- 材料单重
    FGPBS VARCHAR2(2000),  -- 返工品标示
    YCJZ VARCHAR2(2000),  -- 一次交转
    LJZC NUMBER,  -- 累计转出
    ZCRQ DATE,  -- 转出日期
    DXSI DATE,  -- 镀锌时间
    KBKHBS VARCHAR2(2000),  -- 看板考核标示
    LJTDD NUMBER,  -- 累计投订单
    ZXS VARCHAR2(2000),  -- 主形式
    ZCBS VARCHAR2(2000),  -- 转出标示
    LQBS VARCHAR2(2000),  -- 领取标示
    XPL VARCHAR2(2000),  -- 小批量
    KZSP VARCHAR2(2000),  -- 科长审批
    JGDE NUMBER,  -- 加工定额
    HWH VARCHAR2(2000),  -- 货位号
    GYS VARCHAR2(2000),  -- 供应商
    ZCBH VARCHAR2(2000),  -- 资产编号
    ZLGH VARCHAR2(2000),  -- 装炉工号
    ZLJS VARCHAR2(2000),  -- 装炉件数
    ZLRQ VARCHAR2(2000),  -- 装炉日期
    ZLS NUMBER,  -- 装炉数
    BZL VARCHAR2(2000),  -- 不装炉
    CLBM VARCHAR2(2000),  -- 材料编码
    CLMC VARCHAR2(2000),  -- 材料名称
    GGXH VARCHAR2(2000),  -- 规格型号
    TKBS NUMBER,  -- 投看板数
    DJLSH VARCHAR2(2000),  -- 单据流水号
    LX VARCHAR2(2000),  -- 类型
    JSJS NUMBER,  -- 结算件数
    JE NUMBER,  -- 结算金额
    DJ NUMBER,  -- 单价
    JSR VARCHAR2(2000),  -- 结算人
    SFJS NUMBER(1),  -- 是否结算
    JSDH VARCHAR2(2000),  -- 结算单号
    DY VARCHAR2(2000),  -- 打压
    LT NUMBER,  -- 料头
    FPH VARCHAR2(2000),  -- 
    JSBJ VARCHAR2(2000),  -- 计算标记
    CZ VARCHAR2(2000),  -- 一级分类
    CPLB VARCHAR2(2000),  -- 二级分类
    CPXL VARCHAR2(2000),  -- 三级分类
    LW VARCHAR2(2000),  -- 螺纹
    YLDJ VARCHAR2(2000),  -- 压力等级
    SB VARCHAR2(2000),  -- 商标
    UT VARCHAR2(2000),  -- 数量单位
    ZL NUMBER,  -- 重量
    CLDW VARCHAR2(2000),  -- 产量单位
    CQ VARCHAR2(2000),  -- 厂区
    SBLX VARCHAR2(2000),  -- 设备类型
    SBMC VARCHAR2(2000),  -- 设备名称
    GS NUMBER,  -- 工时
    JZRQ VARCHAR2(2000),  -- 记账日期
    ZCHWH VARCHAR2(2000),  -- 转出货位号
    IP VARCHAR2(2000),  -- ip地址
    KCZT VARCHAR2(2000),  -- 库存状态
    TMH VARCHAR2(2000),  -- 条码号
    JCGX VARCHAR2(2000),  -- 结存更新标记
    JCGXSJ DATE,  -- 结存更新时间
    GYLX VARCHAR2(2000),  -- 工艺类型
    CZFL VARCHAR2(2000),  -- 材质
    BMCL VARCHAR2(2000),  -- 表面处理
    SCGY VARCHAR2(2000),  -- 生产工艺
    SCX VARCHAR2(2000),  -- 生产线
    FHGH VARCHAR2(2000),  -- 发货工号
    SHGH VARCHAR2(2000),  -- 收货工号
    JCGDH VARCHAR2(2000),  -- 结存工单号
    JHGDH VARCHAR2(2000),  -- 计划工单号
    KBH VARCHAR2(2000),  -- 看板号
    XBS VARCHAR2(2000),  -- 
    CPBM VARCHAR2(2000),  -- 
    TLBM VARCHAR2(2000),  -- 投料编码
    CDBS NUMBER,  -- 
    CDSJ DATE,  -- 
    SJLY VARCHAR2(2000),  -- 数据来源
    ZBID NUMBER,  -- 
    TL NUMBER,  -- 
    WG NUMBER,  -- 
    ZKZY NUMBER,  -- 
    RKLB VARCHAR2(2000),  -- 入库类别
    CPFLX VARCHAR2(2000),  -- 产品分类新
    SX1 VARCHAR2(2000),  -- 属性一
    SX2 VARCHAR2(2000),  -- 属性二
    SX3 VARCHAR2(2000),  -- 属性三
    YKBH VARCHAR2(2000),  -- 
    QSBM VARCHAR2(2000),  -- 欠数表面
    ZJBID NUMBER,  -- 
    HXXX VARCHAR2(2000),  -- 核销信息
    ZCZPZ VARCHAR2(2000),  -- 转出主品种
    ZCZGG VARCHAR2(2000),  -- 转出主规格
    ZCZXS VARCHAR2(2000),  -- 转出主形式
    ZCZCZFL VARCHAR2(2000),  -- 转出主材质
    ZCZBMCL VARCHAR2(2000),  -- 转出主表面
    ETL_CRT_DT DATE DEFAULT SYSDATE,  -- ETL创建日期
    ETL_UPD_DT DATE DEFAULT SYSDATE  -- ETL更新日期
);

-- 添加表注释
COMMENT ON TABLE ODS_QCSJB_CKYW IS '主erp统一领转查询';

-- 添加列注释
COMMENT ON COLUMN ODS_QCSJB_CKYW.ID IS '序号';
COMMENT ON COLUMN ODS_QCSJB_CKYW.PZ IS '品种';
COMMENT ON COLUMN ODS_QCSJB_CKYW.GG IS '规格';
COMMENT ON COLUMN ODS_QCSJB_CKYW.XS IS '形式';
COMMENT ON COLUMN ODS_QCSJB_CKYW.JS IS '件数';
COMMENT ON COLUMN ODS_QCSJB_CKYW.DZ IS '单重';
COMMENT ON COLUMN ODS_QCSJB_CKYW.ZCBM IS '转出编码';
COMMENT ON COLUMN ODS_QCSJB_CKYW.ZCDW IS '转出单位';
COMMENT ON COLUMN ODS_QCSJB_CKYW.LQBM IS '领取编码';
COMMENT ON COLUMN ODS_QCSJB_CKYW.LQDW IS '领取单位';
COMMENT ON COLUMN ODS_QCSJB_CKYW.RQ IS '日期';
COMMENT ON COLUMN ODS_QCSJB_CKYW.GXSJ IS '更新时间';
COMMENT ON COLUMN ODS_QCSJB_CKYW.LRY IS '录入员';
COMMENT ON COLUMN ODS_QCSJB_CKYW.MZ IS '毛重';
COMMENT ON COLUMN ODS_QCSJB_CKYW.PZH IS '皮重';
COMMENT ON COLUMN ODS_QCSJB_CKYW.SCZL IS '实测重量';
COMMENT ON COLUMN ODS_QCSJB_CKYW.SCJS IS '实测件数';
COMMENT ON COLUMN ODS_QCSJB_CKYW.SCDZ IS '实测单重';
COMMENT ON COLUMN ODS_QCSJB_CKYW.CH IS '车号';
COMMENT ON COLUMN ODS_QCSJB_CKYW.BC IS '班次';
COMMENT ON COLUMN ODS_QCSJB_CKYW.LHGH IS '拉货工号';
COMMENT ON COLUMN ODS_QCSJB_CKYW.LH IS '炉号';
COMMENT ON COLUMN ODS_QCSJB_CKYW.JSRQ IS '结算日期';
COMMENT ON COLUMN ODS_QCSJB_CKYW.LCH IS '炉次号';
COMMENT ON COLUMN ODS_QCSJB_CKYW.SKHH IS '数控华晃';
COMMENT ON COLUMN ODS_QCSJB_CKYW.CD IS '长度';
COMMENT ON COLUMN ODS_QCSJB_CKYW.JGBM IS '经过编码';
COMMENT ON COLUMN ODS_QCSJB_CKYW.JGDW IS '经过单位';
COMMENT ON COLUMN ODS_QCSJB_CKYW.GBZH IS 'gb转换';
COMMENT ON COLUMN ODS_QCSJB_CKYW.JC IS '结存';
COMMENT ON COLUMN ODS_QCSJB_CKYW.LS IS '根数';
COMMENT ON COLUMN ODS_QCSJB_CKYW.QK IS '切口';
COMMENT ON COLUMN ODS_QCSJB_CKYW.LRYGH IS '录入员工号';
COMMENT ON COLUMN ODS_QCSJB_CKYW.BJBM IS '半加编码';
COMMENT ON COLUMN ODS_QCSJB_CKYW.BJDW IS '半加单位';
COMMENT ON COLUMN ODS_QCSJB_CKYW.ZT IS '状态';
COMMENT ON COLUMN ODS_QCSJB_CKYW.BZWZT IS '包装物状态';
COMMENT ON COLUMN ODS_QCSJB_CKYW.CLS IS '出炉数';
COMMENT ON COLUMN ODS_QCSJB_CKYW.KJ IS '口径';
COMMENT ON COLUMN ODS_QCSJB_CKYW.DJGH IS '倒角工号';
COMMENT ON COLUMN ODS_QCSJB_CKYW.DDH IS '订单号';
COMMENT ON COLUMN ODS_QCSJB_CKYW.BMJ IS '表面积';
COMMENT ON COLUMN ODS_QCSJB_CKYW.SFGZ IS '是否改制';
COMMENT ON COLUMN ODS_QCSJB_CKYW.SBJTH IS '设备机台号';
COMMENT ON COLUMN ODS_QCSJB_CKYW.SCFS IS '生产方式';
COMMENT ON COLUMN ODS_QCSJB_CKYW.SBBS IS '设备标示';
COMMENT ON COLUMN ODS_QCSJB_CKYW.CLDZ IS '材料单重';
COMMENT ON COLUMN ODS_QCSJB_CKYW.FGPBS IS '返工品标示';
COMMENT ON COLUMN ODS_QCSJB_CKYW.YCJZ IS '一次交转';
COMMENT ON COLUMN ODS_QCSJB_CKYW.LJZC IS '累计转出';
COMMENT ON COLUMN ODS_QCSJB_CKYW.ZCRQ IS '转出日期';
COMMENT ON COLUMN ODS_QCSJB_CKYW.DXSI IS '镀锌时间';
COMMENT ON COLUMN ODS_QCSJB_CKYW.KBKHBS IS '看板考核标示';
COMMENT ON COLUMN ODS_QCSJB_CKYW.LJTDD IS '累计投订单';
COMMENT ON COLUMN ODS_QCSJB_CKYW.ZXS IS '主形式';
COMMENT ON COLUMN ODS_QCSJB_CKYW.ZCBS IS '转出标示';
COMMENT ON COLUMN ODS_QCSJB_CKYW.LQBS IS '领取标示';
COMMENT ON COLUMN ODS_QCSJB_CKYW.XPL IS '小批量';
COMMENT ON COLUMN ODS_QCSJB_CKYW.KZSP IS '科长审批';
COMMENT ON COLUMN ODS_QCSJB_CKYW.JGDE IS '加工定额';
COMMENT ON COLUMN ODS_QCSJB_CKYW.HWH IS '货位号';
COMMENT ON COLUMN ODS_QCSJB_CKYW.GYS IS '供应商';
COMMENT ON COLUMN ODS_QCSJB_CKYW.ZCBH IS '资产编号';
COMMENT ON COLUMN ODS_QCSJB_CKYW.ZLGH IS '装炉工号';
COMMENT ON COLUMN ODS_QCSJB_CKYW.ZLJS IS '装炉件数';
COMMENT ON COLUMN ODS_QCSJB_CKYW.ZLRQ IS '装炉日期';
COMMENT ON COLUMN ODS_QCSJB_CKYW.ZLS IS '装炉数';
COMMENT ON COLUMN ODS_QCSJB_CKYW.BZL IS '不装炉';
COMMENT ON COLUMN ODS_QCSJB_CKYW.CLBM IS '材料编码';
COMMENT ON COLUMN ODS_QCSJB_CKYW.CLMC IS '材料名称';
COMMENT ON COLUMN ODS_QCSJB_CKYW.GGXH IS '规格型号';
COMMENT ON COLUMN ODS_QCSJB_CKYW.TKBS IS '投看板数';
COMMENT ON COLUMN ODS_QCSJB_CKYW.DJLSH IS '单据流水号';
COMMENT ON COLUMN ODS_QCSJB_CKYW.LX IS '类型';
COMMENT ON COLUMN ODS_QCSJB_CKYW.JSJS IS '结算件数';
COMMENT ON COLUMN ODS_QCSJB_CKYW.JE IS '结算金额';
COMMENT ON COLUMN ODS_QCSJB_CKYW.DJ IS '单价';
COMMENT ON COLUMN ODS_QCSJB_CKYW.JSR IS '结算人';
COMMENT ON COLUMN ODS_QCSJB_CKYW.SFJS IS '是否结算';
COMMENT ON COLUMN ODS_QCSJB_CKYW.JSDH IS '结算单号';
COMMENT ON COLUMN ODS_QCSJB_CKYW.DY IS '打压';
COMMENT ON COLUMN ODS_QCSJB_CKYW.LT IS '料头';
COMMENT ON COLUMN ODS_QCSJB_CKYW.FPH IS '';
COMMENT ON COLUMN ODS_QCSJB_CKYW.JSBJ IS '计算标记';
COMMENT ON COLUMN ODS_QCSJB_CKYW.CZ IS '一级分类';
COMMENT ON COLUMN ODS_QCSJB_CKYW.CPLB IS '二级分类';
COMMENT ON COLUMN ODS_QCSJB_CKYW.CPXL IS '三级分类';
COMMENT ON COLUMN ODS_QCSJB_CKYW.LW IS '螺纹';
COMMENT ON COLUMN ODS_QCSJB_CKYW.YLDJ IS '压力等级';
COMMENT ON COLUMN ODS_QCSJB_CKYW.SB IS '商标';
COMMENT ON COLUMN ODS_QCSJB_CKYW.UT IS '数量单位';
COMMENT ON COLUMN ODS_QCSJB_CKYW.ZL IS '重量';
COMMENT ON COLUMN ODS_QCSJB_CKYW.CLDW IS '产量单位';
COMMENT ON COLUMN ODS_QCSJB_CKYW.CQ IS '厂区';
COMMENT ON COLUMN ODS_QCSJB_CKYW.SBLX IS '设备类型';
COMMENT ON COLUMN ODS_QCSJB_CKYW.SBMC IS '设备名称';
COMMENT ON COLUMN ODS_QCSJB_CKYW.GS IS '工时';
COMMENT ON COLUMN ODS_QCSJB_CKYW.JZRQ IS '记账日期';
COMMENT ON COLUMN ODS_QCSJB_CKYW.ZCHWH IS '转出货位号';
COMMENT ON COLUMN ODS_QCSJB_CKYW.IP IS 'ip地址';
COMMENT ON COLUMN ODS_QCSJB_CKYW.KCZT IS '库存状态';
COMMENT ON COLUMN ODS_QCSJB_CKYW.TMH IS '条码号';
COMMENT ON COLUMN ODS_QCSJB_CKYW.JCGX IS '结存更新标记';
COMMENT ON COLUMN ODS_QCSJB_CKYW.JCGXSJ IS '结存更新时间';
COMMENT ON COLUMN ODS_QCSJB_CKYW.GYLX IS '工艺类型';
COMMENT ON COLUMN ODS_QCSJB_CKYW.CZFL IS '材质';
COMMENT ON COLUMN ODS_QCSJB_CKYW.BMCL IS '表面处理';
COMMENT ON COLUMN ODS_QCSJB_CKYW.SCGY IS '生产工艺';
COMMENT ON COLUMN ODS_QCSJB_CKYW.SCX IS '生产线';
COMMENT ON COLUMN ODS_QCSJB_CKYW.FHGH IS '发货工号';
COMMENT ON COLUMN ODS_QCSJB_CKYW.SHGH IS '收货工号';
COMMENT ON COLUMN ODS_QCSJB_CKYW.JCGDH IS '结存工单号';
COMMENT ON COLUMN ODS_QCSJB_CKYW.JHGDH IS '计划工单号';
COMMENT ON COLUMN ODS_QCSJB_CKYW.KBH IS '看板号';
COMMENT ON COLUMN ODS_QCSJB_CKYW.XBS IS '';
COMMENT ON COLUMN ODS_QCSJB_CKYW.CPBM IS '';
COMMENT ON COLUMN ODS_QCSJB_CKYW.TLBM IS '投料编码';
COMMENT ON COLUMN ODS_QCSJB_CKYW.CDBS IS '';
COMMENT ON COLUMN ODS_QCSJB_CKYW.CDSJ IS '';
COMMENT ON COLUMN ODS_QCSJB_CKYW.SJLY IS '数据来源';
COMMENT ON COLUMN ODS_QCSJB_CKYW.ZBID IS '';
COMMENT ON COLUMN ODS_QCSJB_CKYW.TL IS '';
COMMENT ON COLUMN ODS_QCSJB_CKYW.WG IS '';
COMMENT ON COLUMN ODS_QCSJB_CKYW.ZKZY IS '';
COMMENT ON COLUMN ODS_QCSJB_CKYW.RKLB IS '入库类别';
COMMENT ON COLUMN ODS_QCSJB_CKYW.CPFLX IS '产品分类新';
COMMENT ON COLUMN ODS_QCSJB_CKYW.SX1 IS '属性一';
COMMENT ON COLUMN ODS_QCSJB_CKYW.SX2 IS '属性二';
COMMENT ON COLUMN ODS_QCSJB_CKYW.SX3 IS '属性三';
COMMENT ON COLUMN ODS_QCSJB_CKYW.YKBH IS '';
COMMENT ON COLUMN ODS_QCSJB_CKYW.QSBM IS '欠数表面';
COMMENT ON COLUMN ODS_QCSJB_CKYW.ZJBID IS '';
COMMENT ON COLUMN ODS_QCSJB_CKYW.HXXX IS '核销信息';
COMMENT ON COLUMN ODS_QCSJB_CKYW.ZCZPZ IS '转出主品种';
COMMENT ON COLUMN ODS_QCSJB_CKYW.ZCZGG IS '转出主规格';
COMMENT ON COLUMN ODS_QCSJB_CKYW.ZCZXS IS '转出主形式';
COMMENT ON COLUMN ODS_QCSJB_CKYW.ZCZCZFL IS '转出主材质';
COMMENT ON COLUMN ODS_QCSJB_CKYW.ZCZBMCL IS '转出主表面';
COMMENT ON COLUMN ODS_QCSJB_CKYW.ETL_CRT_DT IS 'ETL创建日期';
COMMENT ON COLUMN ODS_QCSJB_CKYW.ETL_UPD_DT IS 'ETL更新日期';