CREATE TABLE ODS_JCHZJL_TG (
    id NUMBER,
    rq VARCHAR2(2000),
    dw VARCHAR2(2000),
    bs VARCHAR2(2000),
    cb VARCHAR2(2000),
    js NUMBER,
    zl NUMBER,
    cz VARCHAR2(2000),
    fl VARCHAR2(2000),
    sxh NUMBER,
    lry VARCHAR2(2000),
    gxsj DATE,
    jwc NUMBER,
    jwcz NUMBER,
    cplb VARCHAR2(2000),
    cpxl VARCHAR2(2000),
    je NUMBER,
    jwce NUMBER,
    pjjs NUMBER,
    pjzl NUMBER,
    ycz VARCHAR2(2000),
    oemjs NUMBER,
    oemzl NUMBER,
    etl_crt_dt DATE DEFAULT SYSDATE,
    etl_upd_dt DATE DEFAULT SYSDATE
);