CREATE TABLE "MDADS"."ADS_CUX_ITEM_BALANCE_V" 
(	
    "LINE_ID" VARCHAR2(2000), -- 行编号
    "ORG_ID" VARCHAR2(2000), -- 组织ID
    "ORG_NAME" VARCHAR2(2000), --生产线
    "PERIOD_NAME" VARCHAR2(2000), -- 期间(格式:YYYY-MM)
    "ORGANIZATION_ID" VARCHAR2(2000), -- 库存组织ID
    "ITEM_ID" NUMBER, -- 物料ID
    "ITEM_CODE" VARCHAR2(2000), -- 物料编码
    "ITEM_DESC" VARCHAR2(2000), -- 物料名称
    "FIN_CATE_CODE" VARCHAR2(2000), -- 财务类别
    "FIN_CATE_DESC" VARCHAR2(2000), -- 物料分类
    "BEGIN_QTY" NUMBER, -- 期初库存量
    "BEGIN_AMT" NUMBER, -- 期初库存金额
    "BEGIN_DIFFE_AMT" NUMBER, -- 期初差异金额
    "PERIOD_QTY_DR" NUMBER, -- 本月入库量
    "PERIOD_AMT_DR" NUMBER, -- 本月入库金额
    "PERIOD_QTY_CR" NUMBER, -- 本月出库量
    "PERIOD_AMT_CR" NUMBER, -- 本月出库金额
    "PERIOD_DIFFE_AMT_DR" NUMBER, -- 本月新增差异
    "PERIOD_DIFFE_AMT_CR" NUMBER, -- 本月结转差异
    "STAND_DIFFE_AMT" NUMBER, -- 标准成本更新差异
    "ITEM_END_QTY" NUMBER, -- 本月数量
    "ITEM_END_AMT" NUMBER, -- 本月金额（万元）
    "LAST_ITEM_END_QTY" NUMBER, -- 上月数量
    "LAST_ITEM_END_AMT" NUMBER, -- 上月金额（万元）
    "END_DIFFE_AMT" NUMBER, -- 期末差异金额
    "ACTUAL_UNIT_COST" NUMBER, -- 实际成本
    "ITEM_TYPE" VARCHAR2(2000), -- 物料类型
    "ETL_UPD_DT" DATE, -- 创建日期
    "ETL_CRT_DT" DATE -- 更新日期

)



COMMENT ON COLUMN "MDADS"."ADS_CUX_ITEM_BALANCE_V"."LINE_ID" IS '行编号';
COMMENT ON COLUMN "MDADS"."ADS_CUX_ITEM_BALANCE_V"."ORG_ID" IS '组织ID';
COMMENT ON COLUMN "MDADS"."ADS_CUX_ITEM_BALANCE_V"."ORG_NAME" IS '生产线';
COMMENT ON COLUMN "MDADS"."ADS_CUX_ITEM_BALANCE_V"."PERIOD_NAME" IS '期间';
COMMENT ON COLUMN "MDADS"."ADS_CUX_ITEM_BALANCE_V"."ORGANIZATION_ID" IS '库存组织ID';
COMMENT ON COLUMN "MDADS"."ADS_CUX_ITEM_BALANCE_V"."ITEM_ID" IS '物料ID';
COMMENT ON COLUMN "MDADS"."ADS_CUX_ITEM_BALANCE_V"."ITEM_CODE" IS '物料编码';
COMMENT ON COLUMN "MDADS"."ADS_CUX_ITEM_BALANCE_V"."ITEM_DESC" IS '物料名称';
COMMENT ON COLUMN "MDADS"."ADS_CUX_ITEM_BALANCE_V"."FIN_CATE_CODE" IS '财务类别';
COMMENT ON COLUMN "MDADS"."ADS_CUX_ITEM_BALANCE_V"."FIN_CATE_DESC" IS '物料分类';
COMMENT ON COLUMN "MDADS"."ADS_CUX_ITEM_BALANCE_V"."BEGIN_QTY" IS '期初库存量';
COMMENT ON COLUMN "MDADS"."ADS_CUX_ITEM_BALANCE_V"."BEGIN_AMT" IS '期初库存金额';
COMMENT ON COLUMN "MDADS"."ADS_CUX_ITEM_BALANCE_V"."BEGIN_DIFFE_AMT" IS '期初差异金额';
COMMENT ON COLUMN "MDADS"."ADS_CUX_ITEM_BALANCE_V"."PERIOD_QTY_DR" IS '本月入库量';
COMMENT ON COLUMN "MDADS"."ADS_CUX_ITEM_BALANCE_V"."PERIOD_AMT_DR" IS '本月入库金额';
COMMENT ON COLUMN "MDADS"."ADS_CUX_ITEM_BALANCE_V"."PERIOD_QTY_CR" IS '本月出库量';
COMMENT ON COLUMN "MDADS"."ADS_CUX_ITEM_BALANCE_V"."PERIOD_AMT_CR" IS '本月出库金额';
COMMENT ON COLUMN "MDADS"."ADS_CUX_ITEM_BALANCE_V"."PERIOD_DIFFE_AMT_DR" IS '本月新增差异';
COMMENT ON COLUMN "MDADS"."ADS_CUX_ITEM_BALANCE_V"."PERIOD_DIFFE_AMT_CR" IS '本月结转差异';
COMMENT ON COLUMN "MDADS"."ADS_CUX_ITEM_BALANCE_V"."STAND_DIFFE_AMT" IS '标准成本更新差异';
COMMENT ON COLUMN "MDADS"."ADS_CUX_ITEM_BALANCE_V"."ITEM_END_QTY" IS '本月数量';
COMMENT ON COLUMN "MDADS"."ADS_CUX_ITEM_BALANCE_V"."ITEM_END_AMT" IS '本月金额（万元）';
COMMENT ON COLUMN "MDADS"."ADS_CUX_ITEM_BALANCE_V"."PREV_END_QTY" IS '上月数量';
COMMENT ON COLUMN "MDADS"."ADS_CUX_ITEM_BALANCE_V"."PREV_END_AMT" IS '上月金额（万元）';
COMMENT ON COLUMN "MDADS"."ADS_CUX_ITEM_BALANCE_V"."END_DIFFE_AMT" IS '期末差异金额';
COMMENT ON COLUMN "MDADS"."ADS_CUX_ITEM_BALANCE_V"."ACTUAL_UNIT_COST" IS '实际成本';
COMMENT ON COLUMN "MDADS"."ADS_CUX_ITEM_BALANCE_V"."ITEM_TYPE" IS '物料类型';
COMMENT ON COLUMN "MDADS"."ADS_CUX_ITEM_BALANCE_V"."ETL_UPD_DT" IS '创建日期';
COMMENT ON COLUMN "MDADS"."ADS_CUX_ITEM_BALANCE_V"."ETL_CRT_DT" IS '更新日期';