WITH TMP_DWD_2 AS(

SELECT ORDER_NUM,'今日发车' STATUS
FROM MDDWD.DWD_DELIVERY_BIKB
WHERE ORDER_NUM LIKE '9%'AND PLAN_SHIP_DATE=TRUNC(SYSDATE,'DD')
AND (ATTRIBUTE2 LIKE'%BY%' OR ATTRIBUTE2 IS NULL) 
UNION ALL
SELECT ORDER_NUM,'今日发车' 状态
FROM MDDWD.DWD_DELIVERY_BIKB
WHERE ORDER_NUM LIKE '508%'   AND PLAN_SHIP_DATE=TRUNC(SYSDATE,'DD')
AND (ATTRIBUTE2 LIKE'%BY%' OR ATTRIBUTE2 IS NULL) 
),
TMP_DWD_1 AS (

SELECT ID,DW,TH,RQ, JHQ,A.DDH,KHM,A.PZ,A.GG,A.XS,A.CZFL,A.BMCL,XJS,QXS,DDQS,B.JS 报工件数
FROM ODS_ERP.ODS_QTKBLSB  A
LEFT JOIN (SELECT KBID,ZH,DDH, PZ,GG,XS,CZFL,BMCL,GB,SUM(JS) JS
FROM ODS_ERP.ODS_FMZPMXB
WHERE GB IN('成套','质检')
GROUP BY KBID,ZH,DDH, PZ,GG,XS,CZFL,BMCL,GB ) B 
ON A.ID=B.KBID AND A.DDH=B.DDH
WHERE  DW = '蝶阀装配线' 
AND PCJS  IS NOT NULL 

)

SELECT A.*,B.STATUS FROM TMP_DWD_1 A LEFT JOIN TMP_DWD_2 B ON A.DDH=B.ORDER_NUM

ADS_WORK_REPORTING_BIKB

